### ISSUE TITLE
Investigate and fix performance issues in the IDE extension

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1000]
## Problem

@jonator Has various performance issues with the vscode extension:

> One of our devs experienced the same issue with performance on save :/ we're disabling it until a fix arrives. Please let me know and we'll reactivate it.

<img width="450" alt="Screenshot_2023-06-26_at_8 50 22_PM" src="https://github.com/inlang/inlang/assets/34959078/00e958b1-6b6e-4361-8dcd-938ed59cc464">

<img width="543" alt="CleanShot_2023-06-21_at_22 53 572x" src="https://github.com/inlang/inlang/assets/34959078/ba613150-9917-420d-8b48-94f789d1df53">

### Expected behavior

- should be "faster"
- decorations could be denounced? 
- analysing files for messages could be more efficient?
- lifecycle improvement to not run everything every time?

**Comment by felixhaeberle** [comment]
@openscript Do you want to take over this task and share your ideas on what could be fixed here and where you see potential performance improvements? 

I have also collected some loose thoughts above under the "expected behavior" section.

**Comment by samuelstroschein** [comment]
I have two hours and will investigate the causes. Maybe even fix the issues.

**Comment by samuelstroschein** [comment]
A ton of bugs and performance seem to stem from naively restarting the ide extension when the active window changes. 

The naive restarting was implemented a long time ago for "ah easy just restart the extension and move on". I will remove the constant restarting. 

<img width="867" alt="CleanShot 2023-06-27 at 07 02 19@2x" src="https://github.com/inlang/inlang/assets/35429197/ca005c88-9dc8-40e1-85df-626ea768c8f2">

**Comment by samuelstroschein** [comment]
In addition: One keystroke change triggers update decorations 4x times. Investigation pending.

**Comment by felixhaeberle** [comment]
@samuelstroschein yep, guessed so too – but the solution is not to disable that subscribing/unsubscribe, but to find ways to reload/activate the individual features on their own.

**Comment by samuelstroschein** [comment]
I don't understand why OOP would be better suited. Can you elaborate?

**Comment by felixhaeberle** [comment]
> I don't understand why OOP would be better suited. Can you elaborate?

I'm not sure. = 

> I once thought a OOP structure

The suggestion I once had was that with OOP, we could enhance the situation of having multiple lifecycles with different components/features and their relationships – that the concept of objects and mutable data could help us to achieve better encapsulation and dynamic dispatch.

In particular, I found the decision to go class-based [here](https://github.com/lokalise/i18n-ally/tree/main/src/core) not bad, so I wanted to suggest it here too, if we see any benefit. 

**I don't see any urge to do this rn. **
I would even advise against it because the rest of the codebase is also written functional.

**Comment by samuelstroschein** [comment]
> I don't see any urge to do this rn.
> I would even advise against it because the rest of the codebase is also written functional.

👍 

>  that the concept of objects and mutable data could help us to achieve better encapsulation and dynamic dispatch.

Implemented in https://github.com/inlang/inlang/pull/1001/files#. Function are now using global vscode state instead of state passed from main which avoids the need to restart main on every change. 

Anyhow, #1001 should fix this issue. Releasing as minor bump (v0.8) to be able to communicate "v0.8 fixed the performance issues"
