### ISSUE TITLE
Add integration tests for ide extension

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#1002]
## Problem

The `ide-extension` is quite a black box now. Bugs and errors start to happen more and more which should have been caught by testing. These errors can scare potential users.

## Proposal

Add a simple single integration test, which checks if the `ide-extension` loads on a simple inlang project.

**Comment by felixhaeberle** [comment]
@inlang/team Something I want to discuss with the whole team.

### We lack the possibility to test properly because simple small test projects are missing.

We currently offer:
- i18next
- typesafe-i18n
- inlang/sdk-js (& json)
- json (we want to deprecate this soon) 

We currently only have one [example repo which only provides testing for json (deprecated soon)](https://github.com/inlang/example/blob/main/inlang.config.js) – which is not sufficient.

### We can offer these small test projects also als `starter templates` not only for internal tests, but also for external first use

**Comment by NilsJacobsen** [comment]
At least a i18next project would be great. From a plugin site that sound also useful.

**Comment by openscript** [comment]
Maybe we can utilize https://todomvc.com/ or something similar to get quickly to some simple test projects or examples.

**Comment by felixhaeberle** [comment]
### Suggestion examples

1. nextjs x inlang (with i18next) – built already @NiklasBuchfink 
2. svelte x inlang (with inlang/sdk) – built already --> test-app inside inlang/sdk-js
3. current example x inlang (with json plugin) – built already 
4. tbd x inlang (with typesafe-i18n) – has to be done

#### It seems we have builder 3/4 of them. The only challenge is to unify them into a single place and make them behave equally for better maintenance & testing.

**Comment by samuelstroschein** [comment]
> bring them to one place -> inlang/example with subfolders

Monorepo. Bring them in the monorepo to have easy end-to-end tests.

**Comment by felixhaeberle** [comment]
> Monorepo. Bring them in the monorepo to have easy end-to-end tests.

Haha dumb me. For sure!!!

**Comment by felixhaeberle** [comment]
I'll put these test projects together into the monorepo

**Comment by felixhaeberle** [comment]
added:
- nextjs x inlang (with i18next) 
- svelte x inlang (with inlang/sdk)

**Comment by felixhaeberle** [comment]
@openscript Yes! I would also go for the minimum for now and see if we need to scale it further.

The most important requirement is that we check if the various commands / functionality of the ide extension is correctly applied in an E2E test scenario.

You can go for it 👍

**Comment by openscript** [comment]
Our `ide-extension` test setup diverges from the recommended VS Code test setup. We are using `vitest` and build with `esbuild`.

I've invested an hour now and I think I can get E2E testing running with this setup, but we live on the edge.

 - https://vitest.dev/advanced/api.html: We need this and it is not stable.
