### ISSUE TITLE
Possible race condition in `triggerPushChanges`

### ISSUE THREAD

**Issue by araknast** [inlang/inlang#1006]
# Problem:
[`setResources` is called before `pushChanges` in the `GitFloat` component](https://github.com/inlang/inlang/blob/baa8acdf6e0ce2a879489f3e9f21112a66f51671/source-code/website/src/pages/editor/%40host/%40owner/%40repository/components/Gitfloat.tsx#L129-L139), however [`setResources` contains a non-awaited call to the async function `writeResources`](https://github.com/inlang/inlang/blob/48f235c280538047df55e529bbb9a798fe938556/source-code/website/src/pages/editor/%40host/%40owner/%40repository/State.tsx#L568-L573). This creates a situation where `pushChanges` attempts to create changes that have not yet been written to the filesystem.

# Reproduction:
## Steps
1. Use the `object-store-fs` branch
2. `npm run dev`
3. Open the editor, clone, fork, make changes, then push
## Expected behavior
Remote branch is update with the new changes
## Actual behavior
The commit is pushed upstream, but the contents are empty because the commit was created before changes were written to the filesystem

# Additional Information:
In the current state, writing to the filesystem is fast enough that `setResources` will always "win" the race, but when using `objectStoreFs`, `pushChanges` wins resulting in an [empty git commit with no files changed](https://github.com/araknast/AppFlowy/commit/b42b7e52f5927435557aa2a701f0b049cc5da3da). 

CC: @NiklasBuchfink and @inlang/editor team

**Comment by NilsJacobsen** [comment]
You should get in the loop with @NiklasBuchfink he was working on that the last days.

**Comment by NiklasBuchfink** [comment]
@araknast I looked into it before and experienced that while debugging with different log statements this week. Funny how that catches up with me again 😅 

I checked the branch and could replicate it. I will solve this at the latest tomorrow👍 An async/await should solve this, am I right?

**Comment by NiklasBuchfink** [comment]
`setResources` and `writeResources` is now awaited. This solves the issue
