### ISSUE TITLE
Loading spinner dissapears too soon when using `objectStoreFs`

### ISSUE THREAD

**Issue by araknast** [inlang/inlang#1007]
## Problem
When using `objectStoreFs`, the loading spinner disappears after the repo is cloned, but before the messages are loaded, which leads to the editor displaying "0 messages found" for some time until they load in.

This can be reproduced by building the editor from the `object-store-fs` branch and then cloning a large repo such as AppFlowy.
  
## Possible cause
At the moment, the display of the loading spinner in the editor is dependent on the repository being cloned and the config being loaded. What seems to be happening is that the loading spinner disappears before the messages have been parsed and are ready to be displayed. With regular `memoryFs`, this delay is imperceptible, but when using `objectStoreFs`, there is a significant delay.

## Proposal
Refactor the loading spinner in some way so that it waits until messages are ready to display before disappearing. For example we could make the messages into their own resource, and add them to the `Match` statement in [index.page.tsx](https://github.com/inlang/inlang/blob/48f235c280538047df55e529bbb9a798fe938556/source-code/website/src/pages/editor/%40host/%40owner/%40repository/index.page.tsx#L108C5-L108C5), or display them using a `Suspense` element.

CC: @inlang/editor @NiklasBuchfink

**Comment by NiklasBuchfink** [comment]
We do that. This would also hide the ugly layout shift in the beginning.

@NilsJacobsen We already thought about placeholders as we should know quite early how many languages will be displayed. A basic tailwind `animation-pulse` could easily make this appealing.

**Comment by NiklasBuchfink** [comment]
@araknast now the spinner is displayed as long as the `message` state is zero. This doesn't prevent the ugly layout shift, but it's okayish for now. Please give me feedback if it's good enough or if we should make another improvement before you merge your changes.

@NilsJacobsen and I will improve it further from a UX perspective.

**Comment by araknast** [comment]
@NiklasBuchfink Looks good, closing the issue now.
