### ISSUE TITLE
Unable to start `dev` server without internet connection

### ISSUE THREAD

**Issue by buhodev** [inlang/inlang#1008]
## Problem
In the `inlang.config.js` file, plugins are loaded from a cdn. Is there any way to cache the necessary files for x amount of time or to import them from `node_modules`?

### Expected behavior
Plugins are downloaded locally or cached, so that I can keep working on my projects when internet connection is lost or when I am in a place without wifi.

## Steps to reproduce

1. Create a new SvelteKit project with prettier enabled
2. Install @inlang/sdk-js and set up inlang manually with the json plugin
3. Disconnect from the internet/wifi
4. Start the `dev` server
5. See error on console

```sh
file:///C:/Users/buhodev/Projects/inlang-test/node_modules/.pnpm/@inlang+sdk-js@0.6.6_@sveltejs+kit@1.20.2_esbuild@0.18.9_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:166


...[omitting the logging of a huge minified file]


ft [Error]: fetch failed
    at Ku (file:///C:/Users/buhodev/Projects/inlang-test/node_modules/.pnpm/@inlang+sdk-js@0.6.6_@sveltejs+kit@1.20.2_esbuild@0.18.9_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:166:1927)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/buhodev/Projects/inlang-test/node_modules/.pnpm/@inlang+sdk-js@0.6.6_@sveltejs+kit@1.20.2_esbuild@0.18.9_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:168:1431
```

### Additional information

- `inlang.config.js` file:

```js
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: pluginJson } = await env.$import(
		'https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@latest/dist/index.js'
	);

	const { default: ideExtensionPlugin } = await env.$import(
		'https://cdn.jsdelivr.net/npm/@inlang/ide-extension-plugin@latest/dist/index.js'
	);

	const { default: standardLintRules } = await env.$import(
		'https://cdn.jsdelivr.net/gh/inlang/standard-lint-rules@latest/dist/index.js'
	);

	const { default: sdkPlugin } = await env.$import(
		'https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.6/dist/index.js'
	);

	return {
		referenceLanguage: 'en',
		plugins: [
			pluginJson({
				pathPattern: './resources/{language}.json',
				variableReferencePattern: ['{', '}']
			}),
			standardLintRules(),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: 'url' }]
				}
			}),
			ideExtensionPlugin()
		]
	};
}

```

- `npx @inlang/cli config validate` output:

```sh
i 🔎 Validating the config file...
√ 🎉 Inlang config is valid!
```

- Browser:
- Operating system: Windows 11
- Screenshots ?

**Comment by samuelstroschein** [comment]
How important is this feature to you?

Caching of plugins is not implemented at the moment. A hacky workaround could be caching via `node_modules` for web projects.

**Comment by buhodev** [comment]
I mean, it's not a showstopper atm. But it would be great if there are plans to progressively enhance that aspect of the DX in the future :)

**Comment by samuelstroschein** [comment]
Closing in favor of https://github.com/inlang/inlang/discussions/1021.

@buhodev, thanks for opening the issue. Given that caching has no immediate priority, I moved the issue to a feature request in accordance with [How we deal with issues](https://github.com/inlang/inlang/issues/928)
