### ISSUE TITLE
Improve performance of `push` event

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1010]
# Problem

the push event causes 3 piles of setResource events

<img width="1209" alt="image" src="https://github.com/inlang/inlang/assets/58360188/d262143a-1675-4fab-98ac-f216a3703dc6">

Is this supposed to be like that?
@inlang/editor 
@inlang/lisa

**Comment by araknast** [comment]
Does this still occur on the `object-store-fs` branch?

**Comment by NiklasBuchfink** [comment]
This is not a problem of `object-store-fs`. It is just triggered too often. I'm able to remove two of the `readResources` calls. I like to refactor more, but doing it with the `object-store-fs` in place makes sense.

@araknast, are you fixing the type errors introduced by the introduction of `object-store-fs`? Please use the `addLanguage` button while testing. The `object-store-fs` seems to have no `mkdir` function required for this feature.

After that, I can try to exclude one more execution of `readResources`.

**Comment by araknast** [comment]
> @araknast, are you fixing the type errors introduced by the introduction of object-store-fs? Please use the addLanguage button while testing. The object-store-fs seems to have no mkdir function required for this feature.

Yes I can do that. If it is possible, can we add validation of the `$fs` schema to  CI/CD?

**Comment by NiklasBuchfink** [comment]
That sounds like a good idea 👍

**Comment by NiklasBuchfink** [comment]
So the performance should have been improved with this change. @araknast, with the fix for #1006, the two race conditions are now not in parallel anymore, which makes the `commit & push` on large repositories slower. I used the Open-Assistant repo to test this.

Can we speed this up by making it partially parallel again?

**Comment by araknast** [comment]
@NiklasBuchfink 
Not sure if this is possible, files must be written to objectStoreFs for the commit to be created. I'll see if there are some places where we can improve performance though.

**Comment by NiklasBuchfink** [comment]
@araknast I close this as the `setResources` events have been reduced. We will improve the `Commit & Push` in the context of other specific issues.
