### ISSUE TITLE
ide extension: i18next plugin update breaks (cause unknown)

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1014]
## Problem

I tested my new plugin locally and can get the ide extension to work. 
It did work with the old plugin but I didn't touch anything ide extension related in the plugin.

Changes of new plugin: https://github.com/inlang/inlang/pull/1015

Loom ->
https://www.loom.com/share/ed11deddf8fc48a7b3d1471d24cd4c6b?sid=ab229f75-8558-4c31-93d2-8c5103d19e8a

Reproduction:
- switch to `plugin-refactoring-explicit-namespaces` branch 
- 'npm run build'
- cd into source-code/plugins/i18next
- copy the code that got build in dist folder.
- Fork Open-Assistant repo: https://github.com/LAION-AI/Open-Assistant
- Clone it locally
- Add a `i18next.js` file to the root
- Paste the plugin code in there.
- Change the inlang.config.js to this:
```ts
export async function defineConfig(env) {
  const { default: i18nextPlugin } = await env.$import(
    "./i18next.js"
  );
  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/gh/inlang/standard-lint-rules@2/dist/index.js"
  );
  return {
    referenceLanguage: "en",
    plugins: [
      i18nextPlugin({
        pathPattern: {
          account: "./website/public/locales/{language}/account.json",
          chat: "./website/public/locales/{language}/chat.json",
          common: "./website/public/locales/{language}/common.json",
          dashboard: "./website/public/locales/{language}/dashboard.json",
          error: "./website/public/locales/{language}/error.json",
          index: "./website/public/locales/{language}/index.json",
          labelling: "./website/public/locales/{language}/labelling.json",
          leaderboard: "./website/public/locales/{language}/leaderboard.json",
          message: "./website/public/locales/{language}/message.json",
          stats: "./website/public/locales/{language}/stats.json",
          tasks: "./website/public/locales/{language}/tasks.json",
          tos: "./website/public/locales/{language}/tos.json",
        }
      }),
      standardLintRules(),
    ],
  };
}
```
- Install ide extension (if u didn't already)
- Reload window
- Try ide extension

@inlang/ide-extension

**Comment by NilsJacobsen** [comment]
https://github.com/inlang/inlang/pull/1015

That are the changes.
To conclude, there is a breaking change for the `pathPattern`. It used to be a string now it can also bey an object with namespace and path as key value. You can find that in the settings file: source-code/plugins/i18next/src/settings.ts

**Comment by felixhaeberle** [comment]
I currently don't see why the input of the plugin should influence the input of the IDE extension, because that normally should be handled by the plugin. Other plugins for example and also the old version of your plugin, are working. 

Can you investigate on your side what you are passing as the `messageReferencePattern` in the `ideExtension` setting that we can verify it works with the IDE extension?

**Comment by NilsJacobsen** [comment]
> Can you investigate on your side what you are passing as the messageReferencePattern in the ideExtension setting that we can verify it works with the IDE extension?

Do you mean what get's matched? I could show you what get's matched in the tests.

> The problem seems to be the message parser which is not working anymore with the added namespaces I guess? 

I can't see where this should happen in the parser. Also, the error says that the inlang.extractMessage function is not defined. In the video you see the behavior. Are you sure you can exclude the error on the ide-extension side?

It is not about the text decorations it just not working completely. As far as I see.

**Comment by felixhaeberle** [comment]
@openscript Can you probably weigh in here and have a look at this?
We are currently not sure why the ide extension is not starting with the latest update to the `i18next` plugin.

**Comment by NilsJacobsen** [comment]
That would be great. It's just weird cause the config is valid. So it should correctly read and write data. So the ide-extension should have no problem functioning properly.

**Comment by NilsJacobsen** [comment]
What is the best way to debug the ide extension with real projects? @felixhaeberle @openscript

**Comment by openscript** [comment]
> What is the best way to debug the ide extension with real projects? @felixhaeberle @openscript

1. Clone and open the inlang repo inside Visual Studio Code.
2. Make a example/real project ready in the same file system available.
3. Point the launch.json `debug ide-extension` configuration to the example/real project:
https://github.com/inlang/inlang/blob/45bdd11de6b1a8f8745ccaa703dede611909af77/.vscode/launch.json#L11
4. Install dependencies of inlang and run `npm run dev`
5. Set some breakpoints
6. Run `debug-ide-extension` via the Run and debug view or F5.

**Comment by NilsJacobsen** [comment]
Okay, latest insights:
During the use of the plugin, I get this error:
```
stack trace: Error: The inlang.config.js is invalid.

# The following errors occurred during the setup of plugins:

None ✅

# The following errors occurred during the validation of the config:

Error: ENOENT: no such file or directory, open '/Users/nilsjacobsen/inlang/inlang/source-code/starters/Open-Assistant/website/public/locales/lt/chat.json'

---

If plugins return errors, chances are high that the plugin errors are the root cause
for the config errors. Try to fix the plugin errors first.

    at setupConfig (/Users/nilsjacobsen/inlang/inlang/source-code/core/src/config/setupConfig.ts:33:9)
    at main (/Users/nilsjacobsen/inlang/inlang/source-code/ide-extension/src/main.ts:99:17)
```

This is weird cause I thought that it should be tested by the 'npx inlang config validate' command, and this function is passing.
It seems to through an error if a namespace is not there for each language which is not required. Let me investigate in the plugin if I can reproduce the error in a test. 

Still I think it should pass if the config validate command passes.

**Comment by felixhaeberle** [comment]
> This is weird cause I thought that it should be tested by the 'npx inlang config validate' command, and this function is passing.

@NilsJacobsen Which function is passing?

**Comment by NilsJacobsen** [comment]
I fixed it.

vscode does not throw 'ENOENT' error code when the file doesn't exist. It throws 'FileNotFound'.
