### ISSUE TITLE
`resource()` is undefined when creating a message for a new language in `objectStoreFs` 

### ISSUE THREAD

**Issue by araknast** [inlang/inlang#1016]
## Problem
When using `objectStoreFs`, new languages can be added, but new messages cannot be added to them. Instead, an error is thrown when attempting to save the new message.

### Expected behavior
New messages should be able to be added to the editor after creating a new language
## Steps to reproduce

1. Open the editor on the `object-store-fs` branch
2. Clone a repo
3. Add a new language
4. Write a new message for the new language
5. Save the message
6. Error is thrown as below, and the message is not saved.

![image](https://github.com/inlang/inlang/assets/84164531/df973eec-c4a6-4a29-8717-de216f9882cd)

CC: @inlang/editor @inlang/lisa

**Comment by NiklasBuchfink** [comment]
Does the commit https://github.com/inlang/inlang/commit/3ba9a6c2a804fd68cf19eedb204ef7c6ca9f2e0d solve the issue? I can now add a new language and commit & push a message in my example repo.

**Comment by araknast** [comment]
@NiklasBuchfink yep, fixed!
