### ISSUE TITLE
`inlang lint` doesn't exit with failure on errors

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1022]
## Problem

The CLI's lint command runs through without exiting the process with failure if lint errors exist.

### Expected behavior

If lint errors exist, the lint command should exit with `failure`. 

## Steps to reproduce

1. https://github.com/osmosis-labs/osmosis-frontend
2. Run `yarn lint`

### Additional information

<img width="1130" alt="CleanShot 2023-07-01 at 17 48 20@2x" src="https://github.com/inlang/inlang/assets/35429197/5af4ecab-3c6d-4a08-8518-082b0bfdc1df">

**Comment by felixhaeberle** [comment]
Yes, this is a bug and needs to be fixed.

Options:
- fix it with default and let the user not decide on fail-over
- fix with `--no-fail` flag, (or `--fail=false`?) – with fail as default

--- 

### Related thoughts 

Also, we have to think about **ignoring messages by id from the lint** process in a declarative way.

Speaking about the CLI design, we have to keep in mind that we could introduce a `--fix` option in the future, which automatically machine translates where possible and even reverse translate to missing reference language if possible.

**Comment by NilsJacobsen** [comment]
1. Error handling -> agree should be more like 'ERROR: 20 missing messages'
2. Summary -> This looks great to me. 
  - You get a summary at one glance
  - You can also look at the logs in detail
  - What devs expect (like other testing logs)

**Comment by samuelstroschein** [comment]
> @felixhaeberle This works as intended, as we decided not to fail on lints because of the current implementation of mapping over the lints of the getLintReports function to output the logs. If we throw an error here, only the first error would be seen.

I don't get it. 

LintReport returns an array of lint reports. The CLI should fail if the array of lint reports contains lint reports that are errors. No need to change anything, except the CLI exiting with `failure` if the returned array contains errors?

**Comment by felixhaeberle** [comment]
@samuelstroschein See this PR https://github.com/inlang/inlang/pull/1027
