### ISSUE TITLE
'@inlang/cli lint' is weirdly formatted

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1038]
## Problem

I executed `npx @inlang/cli@latest lint` on an repo and got the following output.
<img width="1201" alt="image" src="https://github.com/inlang/inlang/assets/58360188/51bc3a32-5573-4693-b93a-e2d7e7ea94eb">

I would expect it to be a nice table. I guess it is too long. How can we fix this?

@inlang/cli

**Comment by felixhaeberle** [comment]
@NilsJacobsen Ouch!! This is not cool. I relied on a library called https://www.npmjs.com/package/console-table-printer
It seems they do not handle text overflow 🙃 I search for a solution.

**Comment by felixhaeberle** [comment]
I will exchange the current library with https://github.com/cli-table/cli-table3 – this seems like a much better library but strangely, on my first research, this one didn't pop up.

**Comment by felixhaeberle** [comment]
fixed in https://github.com/inlang/inlang/commit/9171a18875f8446b71fed4b4e75573f4630754ac
@NilsJacobsen can you please verify and close this then?

**Comment by NilsJacobsen** [comment]
Haha it is still publishing :D give me a sec

**Comment by NilsJacobsen** [comment]
<img width="792" alt="image" src="https://github.com/inlang/inlang/assets/58360188/4a6a27b9-4867-4a6c-ac98-b12cf9eb6adb">

**Comment by felixhaeberle** [comment]
@NilsJacobsen Also removed the red color. This was too overwhelming.
