### ISSUE TITLE
refactor: unified telemetry for commands

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#1045]
## Problem

For the `extractMessage` command there is some code inside the command to track it's usage via telemetry. 

## Proposal

This should be abstracted in a way, that all commands usage are tracked via a single proxy.

**Comment by samuelstroschein** [comment]
> This should be abstracted in a way, that all commands usage are tracked via a single proxy.

Do we need this now? Or is this nice to have? 

FYI @jannesblobel is probably not technical enough to refactor telemetry stuff. Adding new events, yes. Refactor, likely not. Jannes what do you think?

**Comment by openscript** [comment]
There is already some code related to this:

https://github.com/inlang/inlang/blob/020452c5bf38657c42fd6c2af7b0f7f31b33f81c/source-code/ide-extension/src/commands/extractMessage.ts#L109-L112

**Comment by samuelstroschein** [comment]
> There is already some code related to this:

Yeah but can't we simply copy & paste the four lines for every command for now?

**Comment by openscript** [comment]
> > There is already some code related to this:
> 
> Yeah but can't we simply copy & paste the four lines for every command for now?

Sure, it's no problem for me, but it's an increase in technical dept.

**Comment by samuelstroschein** [comment]
> Sure, it's no problem for me, but it's an increase in technical dept.

I argue, minimally :D Please close as not planned to focus on other things if you agree

**Comment by jannesblobel** [comment]
@samuelstroschein  
It sounds nice to have. But you are probably right; I'm not technical enough. But it sounds interesting when I have the capacity to look into it :)
