### ISSUE TITLE
sdk: exclude specific routes from redirecting

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1048]
## Description

https://discord.com/channels/897438559458430986/1083724234142011392/1127730656277958786

A user is currently working with the SvelteKit starter provided by buhodev, which includes the inlang library for internationalization (i18n). The GitHub repository for reference is [buhodev/sveltekit-tailwind-starter](https://github.com/buhodev/sveltekit-tailwind-starter).

While integrating Supabase auth into the project, the user needs to add a new route, /auth/callback, which is crucial for the authentication flow. However, when utilizing the inlang SDK, the route is redirected to /en (the English version) due to the i18n prefix.

The user is seeking guidance on how to exclude specific routes from being redirected with the i18n prefix. They are curious if there is a configuration or workaround available to accomplish this.

## Proposal 
Introduce route excludes or come up with an different API.

@inlang/sdk-js

**Comment by hypnopilae** [comment]
Thank you @felixhaeberle for opening the issue. I am the user in question and I would be happy to provide any additional context / test things in my repo if that helps.

**Comment by ivanhofer** [comment]
Already discussed on discord, but I wan't to also add it here for everyone else:

As a workaround you can change the callback url to `/en/auth/callback`. You probably just need a single callback url and not a dedicated url for all languages.

**Comment by ivanhofer** [comment]
It is now possible to exclude certain routes in version `0.9.0`. Here is the link to the documentation: https://inlang.com/documentation/sdk/configuration#routing
