### ISSUE TITLE
UX flaw? Saving in the editor 

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1049]
This problem arises in this discussion: https://github.com/inlang/inlang/discussions/583#discussioncomment-6401601

## Problem
People do not understand the blue dot as there are unsaved changes. 

## Proposal
1. We can autosave messages and let them revert them if needed.
2. We could ask to save all if they push and have still unsaved changes.

@inlang/editor

**Comment by samuelstroschein** [comment]
I think the concept of "saving" is redundant and the opposite of what people expect in a web app. 

From https://github.com/inlang/inlang/discussions/583#discussioncomment-6401792

> Hey @inlang/editor,
> 
> I think saving overall might be a web UX flaw.
> 
> The web usage expectation is auto save by default. @stefangrotz problem signals that the save every commit, or actually anything, is a UX flaw. We probably copied git workflows too hard here. I, by the way, have autosave on VSCode activated too.
> 
> ### Proposal
> 1. Auto-save changes (get rid of the "saving" concept in the editor).
> 2. Indicate what messages changed.
> 3. Have a revert changes possibility on a message.
> 
> ![CleanShot 2023-07-10 at 10 40 05@2x](https://user-images.githubusercontent.com/35429197/252284012-f550c474-02dc-4a1a-ad97-cbac955a0745.png)



> Hey @inlang/editor,
> 
> I think saving overall might be a web UX flaw.
> 
> The web usage expectation is auto save by default. @stefangrotz problem signals that the save every commit, or actually anything, is a UX flaw. We probably copied git workflows too hard here.
> 
> ### Proposal
> 1. Auto-save changes (get rid of the "saving" concept in the editor).
> 2. Indicate what messages changed.
> 3. Have a revert changes possibility on a message.
> 
> ![CleanShot 2023-07-10 at 10 40 05@2x](https://user-images.githubusercontent.com/35429197/252284012-f550c474-02dc-4a1a-ad97-cbac955a0745.png)

**Comment by jannesblobel** [comment]
I like your proposal, because: 
This means that the user has to take fewer steps when changing many messages, and at the same time, the default autosave is better in terms of experience than manual saving.

**Comment by jannesblobel** [comment]
@NiklasBuchfink 
I like that you mentioned it here again. I don't know that, and it is good to see that you came up with that. 
Why haven't we developed this further? This is not apparent from the Issue. 
But 4 👍 let's continue with your idea from 2 months ago :)

**Comment by samuelstroschein** [comment]
@NiklasBuchfink Let's make a decision here. You are in charge, you decide. 

1. Get rid of the concept of "saving" in the editor.
2. Everything stays as is because the concept of "saving" is good. 
3. Close this issue as no-priority.

**Comment by NiklasBuchfink** [comment]
As a UX designer, I want to remove as many unnecessary actions for the user as possible and autosave is the modern application standard. inlang and project-lisa should support this. So 1. is the way to go.

From the implementation side:
We would have a hidden "save" on leaving the pattern editor to show a reasonable change count in the Gitfloat. We would have a revert button at the end instead of the save button to undo a change. On CMD+S, we can show a toast with the text "inlang saves automatically. Do not forget to push your changes."

**Comment by samuelstroschein** [comment]
@NiklasBuchfink is this complete?

**Comment by NiklasBuchfink** [comment]
It's f***ing done ✅
