### ISSUE TITLE
HMR not working when changing a translation file

### ISSUE THREAD

**Issue by JonL1** [inlang/inlang#1050]
### Expected behavior

When I modify a translation string from a json file I would expect vite to perform an HRM. 
I'm using SDK.

## Steps to reproduce

1. Add a call to the translation function anywhere `{I('key1')}`
2. Change the value of the key `key1` to anything and save
3. You need to manually reload the page to see the changes

### Additional information

- `inlang.config.js` file:

```js
/**
 	* @type { import("@inlang/core/config").DefineConfig }
 	*/
	export async function defineConfig(env) {
    const { default: jsonPlugin } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js');
    const { default: sdkPlugin } = await env.$import("https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.7.0/dist/index.js");
		const { default: standardLintRules } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js');

    return {
      referenceLanguage: 'en',
      plugins: [
        jsonPlugin({ pathPattern: 'src/resources/{language}.json' }),
        standardLintRules(),
        sdkPlugin({
          languageNegotiation: {
            strategies: [{ type: "localStorage" }],
          },
        }),
      ],
    };
  }
```

- `npx @inlang/cli config validate` output:

```sh
ℹ 🔎 Validating the config file...                                                                                                                                                                12:34:51
✔ 🎉 Inlang config is valid!    
```

- `vite.config.js` file:

```js
import { sveltekit } from "@sveltejs/kit/vite"
import { defineConfig } from "vite"
import inlangPlugin from "@inlang/sdk-js/adapter-sveltekit"

export default defineConfig({
	plugins: [inlangPlugin(), sveltekit()],
})
```

- Browser: Chrome 114.0.5735.198
- Operating system: MacOS Ventura

**Comment by ivanhofer** [comment]
Thanks for opening the issue. We will take a look at this probably next week.

_Related to https://github.com/inlang/inlang/issues/646_

**Comment by ivanhofer** [comment]
This issue needs to wait a bit longer as we are currently investigating how to deal with changes throughout the whole inlang ecosystem. The outcome of that discussion will probably affect this implementation.

**Comment by jannesblobel** [comment]
Unfortunately, Ivan has passed away, and we are trying to find a solution.
I will close this issue as not planned for now when we have a solution.
