### ISSUE TITLE
ide extension error "no root found"

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1053]
## Problem

The ide extension gives an error warning when opening a new VSCode window. 

## Expected behavior

Don't show an error message. 

## Steps to reproduce

1. Open a new VSCode window that doesn't open a repository.

### Additional information

<img width="488" alt="CleanShot 2023-07-11 at 10 32 55@2x" src="https://github.com/inlang/inlang/assets/35429197/278ed565-fbb2-46e7-a4f7-c0f77df887d0">

- IDE-extension version 0.8.0

@inlang/ide-extension

**Comment by felixhaeberle** [comment]
@openscript Didn't you fix it in one of the latest version?

**Comment by samuelstroschein** [comment]
Maybe not published yet?

**Comment by openscript** [comment]
It should be fixed with #1024. The latest release was 6/27/2023, 5:12:23 PM but the PR was merged at Jul 3, 2023, 10:48 AM.
