### ISSUE TITLE
`lint` command modifies resources on disk

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1060]
## Problem

When running `npx @inlang/cli lint` all resource files get rewritten to disk.
This can be seen easily by modifying a resource file with e.g. additional whitespace. Once the `lint` command runs, those changes will be reverted back to the previous format because `writeResources` got calledd somewhere during that process.

### Expected behavior

I would expect `lint` to be a read-only operation and therefore not modify any file.

**Comment by felixhaeberle** [comment]
@ivanhofer This confuses me, because writeResource isn't called anywhere, only `readResource`

https://github.com/inlang/inlang/blob/ad6f2b3b1ab369a19002918b75f3ff8ae7921d6a/source-code/cli/src/commands/lint/index.ts#L27-L28

**Comment by felixhaeberle** [comment]
@samuelstroschein Do you have an idea why this could happen despite no write is being executed?

**Comment by felixhaeberle** [comment]
@ivanhofer I also tend to leave it in, as @samuelstroschein said, so coming back later if somebody complains.
