### ISSUE TITLE
add `context tooltip` and `lints` to IDE extension doc

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1070]
## Problem

Since those are merged:

https://github.com/inlang/inlang/pull/1046
https://github.com/inlang/inlang/pull/1051 

We need to update the docs too.

### Expected behavior

Mention those two new features in the README (and, therefore docs)

**Comment by felixhaeberle** [comment]
add required vs code version to docs

**Comment by NiklasBuchfink** [comment]
Please fix deprecated links

**Comment by felixhaeberle** [comment]
Talked to @floriandwt that he will take over this task because he is working on marketing material and docs of ide extension anyway.

**Comment by felixhaeberle** [comment]
@floriandwt Did you already update the docs of the ide extension? 

Both in /apps/ide-extension and on the README which gets populated to the VS code marketplace `source-code/ide-extension/README.md` ?

**Comment by floriandwt** [comment]
@felixhaeberle currently working on it, time wasn't enough today. I will create a draft PR and link it here.

**Comment by floriandwt** [comment]
Closing this because the new features are showcased
