### ISSUE TITLE
ide: change json parser to jsonc-parser

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1071]
## Context
Currently, we use a standard json parser to parse for example the `extensions.json` file.

## Proposal
The correct file formatting is the `jsonc` spec and the parsers should be replaced by this one:

https://github.com/microsoft/node-jsonc-parser

@inlang/ide-extension

**Comment by samuelstroschein** [comment]
@felixhaeberle default assign someone?

**Comment by felixhaeberle** [comment]
@openscript As I'm currently blocked with other tasks, can you take over? This should probably not take that long.
Please prioritize the integration tests first.

**Comment by openscript** [comment]
I can, but my resources are also quite limited until 20th of July

**Comment by felixhaeberle** [comment]
If that's the case, I'll do it. All good 👍
