### ISSUE TITLE
should we unbundle linting system from AST?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1074]
## Problem

There seems to be a design flaw in the linting system. Namely, attaching lints to the AST. 

- some lints are unrelated to the AST, leading to edge cases like https://github.com/inlang/inlang/discussions/574#discussioncomment-5717270 and #974 
- separation of concerns is violated. the AST is a representation of messages in resources. lints use the AST, but are something else. 

## Proposal 

Unbundle the linting system from the AST. 

- no more AST edge cases
- separation of concerns
- the AST types become vastly simpler because the concept of "extending the AST" is redundant (https://github.com/inlang/inlang/blob/09a90ae3d8c6f41906801ce04c0cf05dc3ad65b3/source-code/core/src/ast/schema.ts#L28)

## Additional information

Vote with 👍 or 👎 if we should unbundle the linting system. 

In addition, `query` should likely moved to `ast`. I thought query would become the universal "inlang messages" query but that turns out to lead to a complexity monster will little benefit.

**Comment by samuelstroschein** [comment]
@ivanhofer we implemented the linting system. I vote for yes because the edge cases of requiring lints for the AST are piling up. In other words, we made a design mistake. 

**Edge cases out of my head**

- missing messages (can't attach to the AST because the message doesn't exist). every app uses their own missing message lints which leads to bugs. 
- message used in source code but doesn't exist in resource (again, can't attach to the AST because message doesn't exist)

**Comment by ivanhofer** [comment]
Agree, building a tree parallel to the Resources would make sense e.g.
```ts
const lintReport = {
	de: {
		'some.message': [
			{
				id: 'inlang.missingMessage',
				level: 'error',
				message: `Message with id 'some.message' is missing for 'de'.`
			},
			// ...
		]
	},
	// ...
}

```

**Comment by NiklasBuchfink** [comment]
I have talked with @NilsJacobsen about this, and from the editor side, this would simplify the filtering a lot.

We can remove the string extraction of languages from the message ID to reconstruct what should be shown and what should not since we now have the lint `missingMessage` associated with the correct ID and language.

We need to adjust all inlang apps on one branch accordingly.

**Comment by felixhaeberle** [comment]
-> should we unbundle linting system from AST?
@samuelstroschein 4 people voted yes. -> can we close this create actionable issues / project?

**Comment by samuelstroschein** [comment]
@felixhaeberle I know, and yes will be closed. 

But, I am awaiting the follow-up issue creation which scopes how to unbundle the linting system.

**Comment by felixhaeberle** [comment]
@samuelstroschein Can I help you with that? It seems that multiple apps would profit.

**Comment by samuelstroschein** [comment]
@felixhaeberle Yes, I'll spec the issue today and ping you

**Comment by samuelstroschein** [comment]
will be completed as part of #1142
