### ISSUE TITLE
improve hash link behavior

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1080]
It is great that we now have hash navigation in our docs. Making references more easy.
I have some feedback on what could be improved:

1. clicking on the `#` should update the url. This is a standard-behavior of other documentation plattforms
	![image](https://github.com/inlang/inlang/assets/21335119/0af086d8-11c3-4cc2-9288-c44f7fe9368c)

2. Set a margin (I don't remember the correct CSS line) so the title is not hidden below the header.
	When opening a link, the page scrolls to far
	currently:
	![image](https://github.com/inlang/inlang/assets/21335119/d0de8153-05a9-4a39-9c13-3399e9f342db)

	expected:
	![image](https://github.com/inlang/inlang/assets/21335119/bb66b931-1949-40f5-afb9-d048a73ee19f)

3. update wording of copy messsage
	"Copy to clipboard" would be the label for the tooltip when hovering over the `#` and not the information on **what happened**. This should probably be "Copied to clipboard" or even better "Copied link to clipboard".
	![image](https://github.com/inlang/inlang/assets/21335119/e66e503e-6ecc-4f39-93cc-11ffc281276a)

**Comment by NilsJacobsen** [comment]
Thanks @ivanhofer. I would say it has not the highest prior, but we could do that in a few minutes. So it's on the list 👍

**Comment by ivanhofer** [comment]
Another issue I just saw:

Copying the hash link also includes a newline at the end
```bash
https://inlang.com/documentation/sdk/sveltekit/advanced#hooks.server.js/n
```
but is should be:
```bash
https://inlang.com/documentation/sdk/sveltekit/advanced#hooks.server.js
```

**Comment by ivanhofer** [comment]
And when running on `localhost` the `https` needs to be replaced with `http`. You should get the information from `location.protocol`.

**Comment by NilsJacobsen** [comment]
Added anchor to url after clicking on headline. https://github.com/inlang/inlang/commit/4e870163df6f70ba129083c9735a38ed938efcbf

Issue should be done.
