### ISSUE TITLE
Crash: The reference language "en" must be included in the list of languages

### ISSUE THREAD

**Issue by dewil-official** [inlang/inlang#1089]
### Expected behavior

Should not crash.

## Steps to reproduce

- See [our editor](https://inlang.com/editor/github.com/remnoteio/translation) and [our config](https://github.com/remnoteio/translation).

### Additional information

- I tried removing the `standardLintRules` plugin, didn't change anything
- I tried using the `json` plugin instead, that also crashed but with a different error (some permission error that supposedly it failed to access `.git/hooks`, which doesn't exist in the repo)
- I recently merged @NiklasBuchfink 's [PR](https://github.com/remnoteio/translation/pull/1) which upgraded the versions of these plugins and added the standardLintRules plugin. Maybe it's a bug in the latest versions?
- I found [this similar issue](https://github.com/inlang/inlang/issues/749) which seems to have been a bug in the JSON plugin?

- `inlang.config.js` file:

```js
export async function defineConfig(env) {
  const { default: i18nextPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next/dist/index.js",
  );

  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules/dist/index.js",
  );

  return {
    referenceLanguage: "en",
    
    plugins: [
      i18nextPlugin({
        pathPattern: "./{language}/*.json",
      }),
      standardLintRules()
    ]
  };
}
```

- `npx @inlang/cli config validate` output:

```sh
error: unknown command validate
```

(Sorry looked at your docs but couldn't find a replacement command)

- Browser: Brave / Chrome (but happens everywhere)
- Operating system: Windows
- Screenshots:
  - ![image](https://github.com/inlang/inlang/assets/7500200/0f16608c-1bc3-470e-a8e3-0019cb32ab55)
  - ![image](https://github.com/inlang/inlang/assets/7500200/966e58f2-374f-4f9a-bf98-38196304019f)

**Comment by dewil-official** [comment]
@NiklasBuchfink fixed this - the issue was that `*` wasn't supported anymore in v3 of the plugin.
https://github.com/remnoteio/translation/pull/6

**Comment by samuelstroschein** [comment]
@dewil-official use major version pinning to not auto update the plugin with breaking changes. 

```
export async function defineConfig(env) {
  const { default: i18nextPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@3/dist/index.js",
  );

  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js",
  );

  return {
    referenceLanguage: "en",
    
    plugins: [
      i18nextPlugin({
        pathPattern: "./{language}/*.json",
      }),
      standardLintRules()
    ]
  };
}
```
