### ISSUE TITLE
[bug] `switchLanguage` redirects incorrectly when `localStorage` strategy is chosen

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1091]
### Problem

Calling `switchLanguage` changes the URL, which should not be the case when `localStorage` strategy is chosen.

### Expected behavior

Switching language should not change the URL

### Reproduction

1. Call `switchLanguage` function
2. you get redirected to e.g.`/de`

### `inlang.config.js` file

```JavaScript
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2.2.0/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.8.0/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
		],
	}
}
```

**Comment by ivanhofer** [comment]
The issue was introduced by #797 because it currently treats the `reactive` and `not-reactive` implementation the same (`not-reactive`). Becasue `switchLanguage` is baked into the variant, in both cases a redirect to `/de` gets made.
Until we re-add (optimized) reactivity into the SDK, let's just apply a quick fix for now.

**Comment by ivanhofer** [comment]
a quickfix was introduced in `0.8.1`

**Comment by jannesblobel** [comment]
Unfortunately, Ivan has passed away, and we are trying to find a solution.
I will close this issue as not planned for now when we have a solution.
