### ISSUE TITLE
[bug] variableReferencePattern are not correctly displayed in inline annotation

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1092]
### Problem

The problem origined in this PR: https://github.com/mifi/lossless-cut/pull/1653#issuecomment-1632065778

`Keep all {{type}} tracks` annotates as `Keep all`

### Expected behavior

Should just show the translation.

### Reproduction

Fork https://github.com/mifi/lossless-cut
Add config
Use ide-extension

### `inlang.config.js` file

```JavaScript
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: i18nextPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@3/dist/index.js",
	)

	const { default: standardLintRules } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js",
	)

	return {
		referenceLanguage: "en",
		plugins: [
			i18nextPlugin({
				pathPattern: "public/locales/{language}/translation.json",
			}),
			standardLintRules(),
		],
	}
}
```

### `npx @inlang/cli config validate` file

```sh
valid
```

**Comment by felixhaeberle** [comment]
@openscript I analyzed this bug already, we currently do not handle placeholders in the rendering of the message preview decoration.

<img width="369" alt="Bildschirmfoto 2023-07-14 um 10 20 39" src="https://github.com/inlang/inlang/assets/34959078/1ce8913b-970e-49a6-8265-a17bfb4b21c2">
<img width="469" alt="Bildschirmfoto 2023-07-14 um 10 20 26" src="https://github.com/inlang/inlang/assets/34959078/722ccb9f-1d1e-49d2-b063-ec5269edbd6d">
<img width="575" alt="Bildschirmfoto 2023-07-14 um 10 20 32" src="https://github.com/inlang/inlang/assets/34959078/0138c365-4505-42cb-b6cf-baf7ef343316">

**Comment by openscript** [comment]
I think it's not hard to fix to show the whole message with the placeholder. 1h should be sufficient.

**Comment by openscript** [comment]
@felixhaeberle: I think it is a quick win. Should I do it today?
