### ISSUE TITLE
Throw error for wildcards in `inlang.config.js`

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#1094]
### Context

Since the wildcard is not supported with version 3 of the `plugin-i18next` and users have invalid configs without getting a good error message. (https://github.com/inlang/inlang/issues/1089)

### Proposal

1. Improve the error message and point out what is wrong
2. Version 2 should still work
3. Link to the readme if possible

**Comment by NilsJacobsen** [comment]
https://github.com/inlang/inlang/pull/1095

Done ✅
