### ISSUE TITLE
enforce correct LanguageTag

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1105]
## Problem 

We need strict(er) enforcement of language tags to avoid chaos in the ecosystem because different "language code" standards are mixed. 

## Proposal 

Bake [BCP-47 language tag](https://datatracker.ietf.org/doc/html/rfc5646) linting into core with a hardcoded lint rule for messages. 

- bcp-47 is the current best practice 
- used by HTML, HTTP.

**Comment by ivanhofer** [comment]
This would block existing apps with a different language code system to adopt inlang.
I would vote for a type like this:
```ts
type LanguageTag = {
   language: string
   country?: string
   // other props that might come in the future like `dialect`?
}
```

**Comment by samuelstroschein** [comment]
> This would block existing apps with a different language code system to adopt inlang.
I would vote for a type like this:

I vote against it because the web works with string identifiers. Have a utility function that gives you language, country, and region. 

```ts
const tag = parseLanguageTag("de-DE-23s")
tag.language
tag.country
tag.region
```
> We can educate people from using the standard and create a lint rule, but I would not enforce it.

We have to enforce it because interop breaks otherwise. Concrete example: machine translate doesn't work with false language tags.

**Comment by ivanhofer** [comment]
If we enforce a common patter, than a `string` will work.
Do we also want to support language only like "de" and "en"? This would be non ISO standard, right?
Most smaller apps won't specify a locale.

**Comment by samuelstroschein** [comment]
> Do we also want to support language only like "de" and "en"? This would be non ISO standard, right?
Most smaller apps won't specify a locale. 

Is supported by BCP-47! :)
