### ISSUE TITLE
setupConfig return a result?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1108]
## Problem

Errors in setting up the config should be handable by apps. 

- the current console logging is "hidden"  

https://github.com/inlang/inlang/blob/7b8a620c4a16a39a1386cd36cad8b65ed0b6e2b8/source-code/core/src/config/setupConfig.ts#L52-L57

## Proposal 

Return a Result with exceptions that apps can display. 

Vote with 👍 or 👎

**Comment by NilsJacobsen** [comment]
It will feel a lot better to show the errors in proper ways in the frontend or handle them individually if needed.

**Comment by samuelstroschein** [comment]
Likely becomes redundant with #1140. 

An app instance could have 

```
const inlang = createApp({ config, env })
inlang.exceptions() // <-- returns exceptions
```

**Comment by samuelstroschein** [comment]
succeeded by #1149
