### ISSUE TITLE
`messages` (query) API

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1112]
## Context

Please propose APIs for messages.

**Comment by ivanhofer** [comment]
How do we know that `get` will return a `Message` or a `Message[]`? This is probably also a bit intransarent for users. I would create two distinct functions.

**Comment by samuelstroschein** [comment]
> How do we know that get will return a Message or a Message[]? This is probably also a bit intransarent for users. I would create two distinct functions. 

We don't know that. We would need a query builder then. Or `getSingle()` function

**Comment by NilsJacobsen** [comment]
From a dev point of view. `getUnique()`,`getFirst()` or `getMany()` kind of functions feel complex. I just want to get the thing, is there not a common typesafe way of doing it?

**Comment by ivanhofer** [comment]
> is there not a common typesafe way of doing it?

There is, but it adds complexity and non-typescript users won't know when `get` returns a single entry and when it returns an array

**Comment by samuelstroschein** [comment]
Succeeded by #1149
