### ISSUE TITLE
config schema update `loadMessages()`, `saveMessages()`

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1116]
Blocked by #1111

**Comment by samuelstroschein** [comment]
Changing `getMessages` to `loadMessages` to avoid confusion like https://github.com/inlang/inlang/issues/1122#issuecomment-1641973079

**Comment by felixhaeberle** [comment]
inspired by https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration — I think there are useful scenarios where utility functions (get, inspect?, update) for the config would come in handy.

**Comment by felixhaeberle** [comment]
Already cleared that misunderstanding 👍

**Comment by samuelstroschein** [comment]
addressed in #1149
