### ISSUE TITLE
discussion about reactivity architecture 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1122]
## Problem

1. how to do caching? 
2. reactivity? messages change, how to propagate to linting, updating the UI, etc. 
3. where to "solve the complexity": plugins, apps, or core? 

## Additional information 

- app state problem driven by persistent layer (repository), and app state
- maybe something like https://tinybase.org/ can help the app state layer but is likely not interop between different apps

**Comment by NilsJacobsen** [comment]
Take that as a thought experiment. It's not about api definitions, it's about functional responsibilities of the ecosystem.
Watch the -> [Loom](https://www.loom.com/share/0cafc240f89241c4bc04aef8914a1ada?sid=ab9d2942-7e38-41d9-a4d3-bdc28520d67e)

<img width="689" alt="image" src="https://github.com/inlang/inlang/assets/58360188/08b0d603-1e93-427c-9ef8-46e00d2905aa">

[Figjam](https://www.figma.com/file/mv2W6vqffN22BARI3hRy2o/organization-structure?type=whiteboard&node-id=0%3A1&t=trnby3GzFDXtHH69-1)

**Comment by NilsJacobsen** [comment]
I always love to hear that the plugins do not get more complexity :D 

If the watcher is in core, do we want that core handles file changes. I thought we made a clear cut from files to only messages in core and app? Or only for apps?

Otherwise I really like the watching being part of core. And query being the central interface for apps. Must admit, that I do not know in detail how to establish reactivity for query without using framework specific technology. 

Only using reactive CRUD would be absolute best case 👍

**Comment by felixhaeberle** [comment]
@NilsJacobsen Thank you for your Loom and what you are thinking of the architectural approaches.

I will conclude based on our discussion:
- reactivity is likely needed for apps (or some kind of)
- query should likely have caching built-in
- there need to be some setter/getter functions
- there is a need to define an updating process that is easy

## Proposal WIP do not comment on it 😂

```ts
// Message Type
type Message = {
  id: string;
  // Define your message properties here
};

// Plugin Type
type Plugin = {
  getMessages: ({ filter }: { filter: Message["id"][] }) => Message[];
  saveMessages: (messages: Message[]) => void;
};

// Messages Type
type Messages = {
  set: (messages: Message[]) => void;
  exec: () => void;
  get: () => Message[];
};

// Core Implementation
const createCore = (plugins: Plugin[], _messages: Messages) => {
  const buildQueryFromPlugins = (): void => {
    const messages: Message[] = plugins.flatMap((plugin) => plugin.getMessages({ filter: crud.get().map((message) => message.id) }));
    _messages.set(messages);
  };

  const setupWatcher = (): void => {
    // Implementation for setting up a file watcher or any other reactive mechanism
    // Whenever a change occurs, trigger rebuild of the query and persist messages
    // You can use fs.watch or implement your own watcher
    fs.watch('path/to/watched/file', (eventType, filename) => {
      if (eventType === 'change') {
        buildQueryFromPlugins();
        _messages.exec();
        const changedMessages = crud.get();
        persistMessages(changedMessages);
      }
    });
  };

  const persistMessages = (messages: Message[]): void => {
    // Implementation for persisting messages
    // You can use a database, file storage, or any other storage mechanism
    // For example, using SQLite:
    const db = new SQLite('path/to/db');
    db.saveMessages(messages);
  };

  return { buildQueryFromPlugins, setupWatcher };
};

// Plugin Implementation
const createPlugin = (): Plugin => {
  let messages: Message[] = [];

  const getMessages = ({ filter }: { filter: Message["id"][] }): Message[] => {
    // Implementation for retrieving messages
    // Apply any necessary filters based on the provided filter
    return messages.filter((message) => filter.includes(message.id));
  };

  const saveMessages = (newMessages: Message[]): void => {
    // Implementation for saving messages
    messages = newMessages;
  };

  return { getMessages, saveMessages };
};

// App Implementation
const createApp = (messages: Messages) => {
  // access messages
  const messages = messages.get()
};
```

**Comment by samuelstroschein** [comment]
@felixhaeberle and @ivanhofer, you are thinking too wide IMO. 

- The question is only about query (reactivity), I would refrain from changing plugin APIs, etc. at the risk of breaking endless things
- Maybe the system is even okay as is with a separate query function. The mental model of "passing an array of messages" around is unbeatable simple. 



> @ivanhofer // no need to specify "languages" because we can derive it from the messages

That's already a mistake. Don't derive, don't assume. Let users or plugins explicitly define what languages a project has.

**Comment by felixhaeberle** [comment]
@samuelstroschein Alright. That's why it matters to talk about implementation.
Can you outline what you would suggest as a way to go forward?

**Comment by samuelstroschein** [comment]
> @felixhaeberle Can you outline what you would suggest as a way to go forward?

Yes.
 
1. I'll go through batch 1 and batch 2 issues in https://github.com/orgs/inlang/projects/35, excluding the query issue. 
2. Afterwards, we should have a clearer overview of what we need from query/how we should implement the API.

**Comment by samuelstroschein** [comment]
Another idea to streamline future adjustments: 

```ts
const inlang = setupInlang({ config, env })

inlang.config // <- the resolved config
inlang.config.getMessages() // <- manual access to config props if needed
inlang.config.languageTags 

// in the future, we can extend the inlang object as required
inlang.messages.query
inlang.lint.reports
inlang.lint.exceptions 
```

Similar to what @felixhaeberle mentioned, have an inlang object/instance that is returned by `setupInlang`. Big time question though: How to do reactivity?

**Comment by samuelstroschein** [comment]
New proposal https://www.loom.com/share/13d70a3063ea4959b058fb19c5953556

- `setupConfig` should return an "inlang instance", not a config -> `setupInlang`
- the inlang instance has getters that can be subscribed to (solving the reactive problem)
- inlang instance deals with caching, `config.getMessages()` and `saveMessages() internally. 

I also asked on Solid's Discord what they think about it https://discord.com/channels/722131463138705510/751355413701591120/1131182363200725012

**Comment by felixhaeberle** [comment]
Note on the wording: I do not understand why I should access messages through a `config`. 
`inlang` make much more sense here.

**Comment by samuelstroschein** [comment]
@ivanhofer @felixhaeberle 

> I would do config.messages.get() instead of config.getMessages(). In the future we will probably also have config.videos etc.

The inlang instance would be created based on the config. 

`inlang.config` is the "raw" config object. 
`inlang.x` is the inlang instance

**Comment by samuelstroschein** [comment]
Very in-depth reply from Ryan Carniato (SolidJS maintainer) https://discord.com/channels/722131463138705510/1131182363200725012/1131266100647174284 on how to tackle reactivity.

**Comment by felixhaeberle** [comment]
> Bringing the discussion points from Discord to github to give a better context.

Talking to Ryan and other members of the solidjs core team, they didn't sell solidjs for our use case that hard. There were a few points to be considered which I listen beneath

---

## Question: Should/can we use SolidJS for reactivity?
### Answer
- rxjs/observables is lower level
- solidjs/signals could be used and would be higher level
- dependent on the needs of the various applications, going lower level might make sense
- using two different version of solidjs in conjunction will likely lead to problems (imagine core using v1 and app uses v2)

---

## Should we go with a subscribe pattern. If so, what library could you recommend?
### Answer
- if you don't have much control over the consumer then subscribe is good because it is just a handoff
- the consumer doesn't need to have a specific system in place -> it could even be Signals, React State, ...
- that seems to be key -> we don't have much control over consumers

```ts
inlang.messages.query.get({ where: { id: "example-id" }}).subscribe((data) => {
 /* here goes the consumer state logic */
})

---

## Libraries that could help introduce the reactive patterns?
### Answer
There are a lot of libraries.
- RxJS
- S.js
- Quarx
- Hyperactiv
- Nanostores
- ofc also Solidjs

**Comment by samuelstroschein** [comment]
@felixhaeberle yeah let's go with subscribe pattern but don't expose it to plugins. 

- we can iterate if the pattern doesn't work because used internally in core and only exposed to apps which we control (no exposure to ecosystem via plugins). 

### Which library 

- prob signal based because observables/RxJS is heavyweight 
- should have long-term maintenance investment. 1 single OSS maintainer is likely bad. 

We could go with SolidJS and see if it works given that they plan to provide a dedicated reactive library this year and are the reactivity experts with company backing (Netlify + Google). 

Go with SolidJS internally and expose manual `.subscribe`?

**Comment by ivanhofer** [comment]
Should we do a little prototype how the implementation would look like using SolidJs?

**Comment by felixhaeberle** [comment]
@ivanhofer Do you feel confident on providing a first prototype PR ? I already spoke with @NilsJacobsen about it and we should probably do a starting point (like with the `query` discussion) and then iterate.

**Comment by NilsJacobsen** [comment]
I'm also trying to build a prototype.👍 Let's try to finish this topic today.

**Comment by ivanhofer** [comment]
@samuelstroschein do you have a clue how to make `createEffect` work outside of the render context?
This code will log nothing:
```ts
const [value, setValue] = createSignal(1)

createEffect(() => {
	console.log(value());
})
setValue(2)
```
If we go to the implementation of `createEffect`, we see that it is empty
![image](https://github.com/inlang/inlang/assets/21335119/8f6a439a-3886-4795-8f59-a682ab2015af)

Before we ask stupid questions in the solidjs discord, we would ask if someone knows how to make it work.

**Comment by ivanhofer** [comment]
If `createEffect` would work, the API should look somthing like this

**Comment by ivanhofer** [comment]
@samuelstroschein
```ts
import { createSignal, createEffect, createRoot } from "solid-js";

const start = async () => {
	const [value, setValue] = createSignal(1);
	console.log(1, value());

	createEffect(() => {
		console.log(5, value());
	});

	setValue(2)
	console.log(2, value());

	await new Promise(resolve => setTimeout(resolve, 100));
}

createRoot(start)
```
will output

![image](https://github.com/inlang/inlang/assets/21335119/e78be5bd-e436-4a61-bf99-975cb98f80c4)

**Comment by samuelstroschein** [comment]
@ivanhofer Seems like we need to wrap the `createInlang` code in `createRoot`. Seems like we are good to go then.

**Comment by ivanhofer** [comment]
@samuelstroschein no, `createRoot` has no effect in the example

**Comment by samuelstroschein** [comment]
@ivanhofer i was about to edit by comment :D indeed odd. works on the solid playground. I'll invest 10 mins to see if i get it to run

**Comment by samuelstroschein** [comment]
@ivanhofer can't get it runing. can you use this stackblitz https://stackblitz.com/edit/stackblitz-starters-gxm7op?file=index.js and ask on the solid discord?

**Comment by ivanhofer** [comment]
Ok, I will do that.

Meanwhile I did some experiments with [`S.js`](https://github.com/adamhaile/S) and it looks promising.

**Comment by samuelstroschein** [comment]
@ivanhofer why `S.js` and not something (more) maintained like Nanostores?

**Comment by ivanhofer** [comment]
Becasue of the auto-tracking of dependencies. No need to define a dependency array. This is also one of the main benefits why solidjs would be appealing.

**Comment by ivanhofer** [comment]
While we are waiting for an answer from solid, I want to share some thoughts:

The auto-tracking would be great, but if we choose to provide a `.subscribe` function, we should probably go with a solution that supports it natively. Comparing [`solid.js`](https://github.com/inlang/inlang/blob/4e935872b3d68eb271d706354866d4d85f63c122/source-code/core2/src/messages/query.ts) and [`Svelte`](https://github.com/inlang/inlang/blob/52db1b9a2c8b54847bb5b132505f12db8740fbbf/source-code/core2/src/messages/query.ts), having a library with native `.subscribe` requires less manual code.
The only question is how do we handle unsubscibes, to not introduce memory leaks?

**Comment by felixhaeberle** [comment]
Interesting question. Because we do not have a component context here, we can't make use of effect callback on dismount. 

We could either:
- **1** expose `unsubscribe() / cancel() / dispose()` (arguably not so nice API) and call it a day or 
- **2** introduce a built-in unsubscribe, with a "more magic" approach. 

I'm more on the side of **1**

Talking about memory leaks: I would simply ignore this topic for now and assume that people know how to write their apps properly. If we find out they can't, I would care about it in a later stage. If we introduce the unsubscribe pattern and advise apps to do it, memory leaks also become less likely.

**Comment by NilsJacobsen** [comment]
Did discuss that with @ivanhofer.

> Could we define the API at this point so that other components of the core, apps, and plugins can begin working with it?

Example:
```ts
export type MessageQueryApi = {
    create: (args: { data: Message }) => void
    get: (args: { where: { id: Message["id"] } }) => { 
        message: Message | undefined, 
        subscribe: (callback: (message: Message | undefined) => void) => void 
    }
    update: (args: { where: { id: Message["id"] }; data: Partial<Message> }) => void
    upsert: (args: { where: { id: Message["id"] }; data: Message }) => void
    delete: (args: { where: { id: Message["id"] } }) => void
}
```

We could agree on the subscription approach, maybe also think about unsubscribe, but then merge it and let one person work on reactivity while the rest is finishing core/ apps/ plugins. 

That way we do not have to wait for answers in discord ...

**Comment by samuelstroschein** [comment]
Steve (Wozniak) comes to the rescue. 

Here is working reactivity in 20 lines of code with `subsribe` auto disposal etc. :) https://stackblitz.com/edit/stackblitz-starters-okatwd?file=index.js

@ivanhofer a signal with a subscription is 7 lines of code. 

@inlang/editor the `get()` should automatically be reactive without `subscribe` 😎 . 

Leeeeeet's go. Please vote on SolidJS with the subscribe wrapped signal. 

> @felixhaeberle 
> Talking about memory leaks: I would simply ignore this topic for now and assume that people know how to write their apps properly.

Nope. Choose a reactive library that eliminates the potential for memory leaks. 

> @NilsJacobsen 

Your proposes API is weird. 

```ts
export type MessageQueryApi = {
    get: (args: { where: { id: Message["id"] } }) => { 
        message: Message | undefined, 
        subscribe: (callback: (message: Message | undefined) => void) => void 
    }
}

```

```ts
const result = query.get({})
result.message
result.subscribe()
```

I propose a very simple

```
const message = query.get()
// or 
query.get().subscribe()

**Comment by felixhaeberle** [comment]
@samuelstroschein Steve is on fire – nice API!! 🔥 
> offtopic: why import from `dist` 🧐 do they not have proper exports?

**Comment by samuelstroschein** [comment]
> @felixhaeberle 

> The solid js package.json imports `dist/server.js` by default which is overwritten to `dist/solid.js` in the browser. Since we are running the code above in a server context, the code the server code was imported.

https://discord.com/channels/722131463138705510/1131182363200725012/1133666569558425700

**Comment by ivanhofer** [comment]
> ```ts
> const message = query.get()
> // or 
> query.get().subscribe()
> ```

I don't think this is possible..
the `Message` and `.subscribe` can't axist on the same object, or else it would break serialization, which we probably need?

This would be the solid syntax:
```ts
query.get({ })() // get value
query.get({ }).subscribe()
```

**Comment by samuelstroschein** [comment]
@ivanhofer yep already removed!

Maybe we should just export `createEffect` for apps. We want reactivity not only for messages but also config props for example. 

```ts

createEffect(() => {
  const config = inlang.config.get()
})
```

Or getters take a `on` prop (because only applies to getters)

```ts
const config = inlang.config.get()

let config = inlang.config.get({  onChange: (_config) => {config = _config} })
```

**Comment by felixhaeberle** [comment]
@samuelstroschein Do you speak about https://www.solidjs.com/tutorial/reactivity_on ?

**Comment by ivanhofer** [comment]
Should we just go without `.subscribe` and see if we run into problems?
We could provide a helper function to convert a signal to a subscription, if someone really needs it. If we have problems, we can always add a `subscribe` function.
Having effects and subscriptions at the same time will probably cause some issues

**Comment by ivanhofer** [comment]
I think this is the API we should go for: https://github.com/inlang/inlang/blob/reactivity-solid/source-code/core2/src/test.ts

It uses `Signals`, `Memos` and `Effects`, is performant and easy to read.
Create root can be called when initializing an application.

I tried it also with stores, but the store API is weird and I also could not make it work ^^.
I find the signals api way easier to reason about.
We can meet in around to discuss my findings if you want. Just ping me on discord.

**Comment by ivanhofer** [comment]
Did some testing and it has absolutely no effect whether `createMemo` get's called multiple times within an `createEffect`. So it looks like we can safely hide the accessor of signals and return the raw value and stil lbe able to offer reactivity on top 🤯:
I'm impressed by solids implementation 👏

**Comment by samuelstroschein** [comment]
Closing as "we are going to use SolidJS".
