### ISSUE TITLE
[bug] error when accessing Editor in "isolated view" mode

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1126]
### Problem

When accessing https://inlang.com/editor/github.com/inlang/example?id=title&lang=en&lang=de
I see the following error:

![image](https://github.com/inlang/inlang/assets/21335119/3062ce3c-c87e-451c-b3e3-a031d3a4d102)

### Reproduction

Open link: https://inlang.com/editor/github.com/inlang/example?id=title&lang=en&lang=de

### `inlang.config.js` file

```JavaScript
not relevant
```

### Other information

Console output

![image](https://github.com/inlang/inlang/assets/21335119/4fc9e481-19d7-44eb-ae4f-c698b006bcf6)

**Comment by NilsJacobsen** [comment]
Thanks for handing in. I saw that this error also appears when not having iso mode on. But you need to be on the editor on the first load. 

https://inlang.com/editor/github.com/inlang/example

Gonna work on a fix tomorrow.

**Comment by NilsJacobsen** [comment]
Can you verify that it is resolved and close?

**Comment by ivanhofer** [comment]
Works now 🎉
