### ISSUE TITLE
BCP47LanguageTag or LanguageTag?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1131]
## Context 

I refactored [#130](https://github.com/inlang/internal/issues/130) to use `BCP47LanguageTag`. 

## Question 

Stick with `BCP47LanguageTag` or rename to `LanguageTag`? 

**Why BCP47LanguageTag**

- more explicit
- opens door for future different language tag e.g. BCP51LanguageTag (but hey, how likely is that)

**Why LanguageTag**

- looks better (haha)

**Comment by samuelstroschein** [comment]
@inlang/team

**Comment by samuelstroschein** [comment]
Vote for `BCP47LanguageTag`

**Comment by samuelstroschein** [comment]
Vote for `LanguageTag`

**Comment by ivanhofer** [comment]
`LanguageTag` because it looks nicer and is easier to type 👍

**Comment by samuelstroschein** [comment]
will be fixed if #1142 is merged
