### ISSUE TITLE
[bug?] TypeError: Cannot read properties of undefined (reading 'component')

### ISSUE THREAD

**Issue by dewil-official** [inlang/inlang#1132]
### Problem

In the Inlang Web-Editor, I get the following error: `TypeError: Cannot read properties of undefined (reading 'component')`. It seems to work regardless but this is not something that users should have to see.

### Expected behavior

Error should not happen 🤷🏻 

### Reproduction

Visit our editor page:
[https://inlang.com/editor/github.com/remnoteio/translation](https://inlang.com/editor/github.com/remnoteio/translation)

And here's our config:
[https://github.com/remnoteio/translation/blob/main/inlang.config.js](https://github.com/remnoteio/translation/blob/main/inlang.config.js)

### `inlang.config.js` file

```JavaScript
export async function defineConfig(env) {
  const { default: i18nextPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@3/dist/index.js"
  );

  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js"
  );

  return {
    referenceLanguage: "en",

    plugins: [
      i18nextPlugin({
        pathPattern: "./{language}/all.json",
      }),
      standardLintRules(),
    ],
  };
}
```

### `npx @inlang/cli config validate` file

```sh
❯ npx @inlang/cli config validate
error: unknown command 'validate'
```

### Other information

Console output:

![image](https://github.com/inlang/inlang/assets/7500200/ea538735-161a-4517-9816-86cbbd4b75c9)

(no visible errors)

Note I also had [this issue](https://github.com/inlang/inlang/issues/1134), I'd assume it's unrelated but just FYI.

**Comment by NilsJacobsen** [comment]
Hi @dewil-official, thanks for handing in. Can you verify that it is resolved?

**Comment by dewil-official** [comment]
Yeah, the error is gone now. Thank you!
