### ISSUE TITLE
Remove console.log in `plugin-json`

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1135]
https://github.com/inlang/inlang/blame/14bcebc7e201a4db86efc85853fded24aa4b8997/source-code/plugins/json/src/plugin.ts#L124

**Comment by samuelstroschein** [comment]
I WAS WONDERING WHERE THAT CAME FROM FOR A WEEK

**Comment by NilsJacobsen** [comment]
✅ https://github.com/inlang/inlang/commit/de0fe4e39df8e7b64d8b29d34ad19b7533df9823
