### ISSUE TITLE
[bug] `lang` attribute does not get updated when switching locales

### ISSUE THREAD

**Issue by buhodev** [inlang/inlang#1145]
### Problem

https://github.com/inlang/inlang/assets/105121122/4d99d6da-2a51-4a2b-8c9f-6af9b9a018fd

### Expected behavior

`lang` attribute should change when switching languages

### Reproduction

1. Clone https://github.com/buhodev/melt-ui-starter/
2. Install dependencies
3. Start dev server & open localhost
4. Open devtools
5. Switch language
6. See that the html lang attribute doesn't change

### `inlang.config.js` file

```JavaScript
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		'https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js'
	);

	const { default: sdkPlugin } = await env.$import(
		'https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.9.1/dist/index.js'
	);

	const { default: standardLintRules } = await env.$import(
		'https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@latest/dist/index.js'
	);

	return {
		referenceLanguage: 'en',
		plugins: [
			jsonPlugin({ pathPattern: './languages/{language}.json' }),
			standardLintRules(),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: 'url' }]
				}
			})
		]
	};
}
```

### `npx @inlang/cli@latest config validate` file

```sh
i 🔎 Validating the config file...
√ 🎉 Inlang config is valid!
```

### Other information

- Browser: Chrome
- OS: Windows 11

**Comment by NilsJacobsen** [comment]
@inlang/sdk-js

**Comment by ivanhofer** [comment]
Thanks for reporting the issue. We accidentiall have removed this feature in a recent refactoring.
It should work again in version `0.9.2`

**Comment by buhodev** [comment]
Thanks for fixing it so quickly!
