### ISSUE TITLE
[bug docs] anchor in link is not working anymore

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1147]
### Problem

After I copy an anchor in the docs and paste it into a new tab, it only opens a page without scrolling to the anchor.

@inlang/docs 

@floriandwt can u explore?:)

### Expected behavior

It should scroll to the anchor.

### Reproduction

click on https://inlang.com/documentation/sdk/configuration#routing

### `inlang.config.js` file

```JavaScript
-
```

### `npx @inlang/cli@latest config validate` file

```sh
-
```

### Other information

- Chrome

![image](https://github.com/inlang/inlang/assets/58360188/27a18b74-6fa6-4061-8d1e-d2395cb7e54c)

**Comment by floriandwt** [comment]
Closing because of #1177
