### ISSUE TITLE
[bug] Editors "Return to app" button doesn't work

### ISSUE THREAD

**Issue by yixuanwu4** [inlang/inlang#1148]
### Problem

I found that the "Return to app" button doesn't work: 
![image](https://github.com/inlang/inlang/assets/56627720/bd670f6c-7041-43d9-adbc-b79213c19a2b)

### Expected behavior

After the "Return to app" button is clicked, my browser should navigate back to the repository I have opened in inlangs editor before I signed in.

### Reproduction

1. Go in inlang.com
2. Click "Open Editor" button
3. Paste my repository link into the input field 
4. Wait for the repository to be cloned
5. Click on the github sign in button
6. Grant permission on github to inlang
7. Cannot use "Return to app" button

### `inlang.config.js` file

```JavaScript
it's a fork of inlang repository
```

### Other information

Browser: Firefox 115.0.2 (64-bit)
Operating System: Linux hostname 6.4.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 11 Jul 2023 05:13:39 +0000 x86_64 GNU/Linux

**Comment by samuelstroschein** [comment]
@inlang/editor can someone take over?

**Comment by NiklasBuchfink** [comment]
@yixuanwu4 I worked on it again today within https://github.com/inlang/inlang/issues/1170

The redirect after login should work on Firefox as well. Sometimes a reload was required after the redirect; this should also be fixed now.
