### ISSUE TITLE
[api spec] uniqueness problem in query. aka massive ecosystem breaking change in the future

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1159]
## Problem

The combination of `id - languageTag` does not entail uniquely identifying a message if `variant` (or other additions) are introduced, breaking query operations. 

https://github.com/inlang/inlang/assets/35429197/697757b1-4b58-4010-85e2-2b875b4ee6c2

### Proposal 1 - add variant

Introduce a `variant: "default"` property on `Message` without introducing the feature yet. 

- we must be certain that "variants" will highly likely come 
- we must be certain that variants will be the only addition for uniqueness 

### Proposal 2 - do nothing

We could ignore the problem at the risk of a massive ecosystem-breaking change. 

- query is passed to plugins, every plugin needs to be updated to include new query API
- every app needs to be updated

---

### off topic 

This is why we should use `messages.query*` that can be succeeded by `messages.query2` in the worst case, see https://github.com/inlang/inlang/pull/1157#discussion_r1270761121 

**Pro**

- not a breaking change (compared to proposal 2)

**Con**

- it will take time until variant is supported (variants could stay unlinted for in the meantime/ignored by plugins). Hence not as "good" as proposal 1.

**Comment by samuelstroschein** [comment]
@inlang/team vote with 👍 👎

**Comment by samuelstroschein** [comment]
proposal 1

**Comment by samuelstroschein** [comment]
proposal 2

**Comment by samuelstroschein** [comment]
proposal 3

**Comment by NilsJacobsen** [comment]
I'm pretty sure AB test will come this way

**Comment by felixhaeberle** [comment]
### Counter Proposal 3

Have multiple bodies because it's still the same `Message`, but with different content. Therefore, uniqueness preserved although breaking change with multiple bodies (I'm almost 100% sure going with multiple bodies is the right thing to do at some point, also speaking about pluralization for example)

**Comment by NiklasBuchfink** [comment]
In general we see now that more flexibility is needed for mentioned use cases. Therefore there is no reason not to implement this at least in the core.

**Comment by NilsJacobsen** [comment]
> Have multiple bodies because it's still the same `Message`, but with different content. Therefore, uniqueness preserved although breaking change with multiple bodies (I'm almost 100% sure going with multiple bodies is the right thing to do at some point, also speaking about pluralization for example)

Can you make an example? @felixhaeberle

**Comment by felixhaeberle** [comment]
PR will follow on Monday is this gets considered. 

@NilsJacobsen Atm, we only have one body/pattern to a message where we nest Text / Placeholder. 

I could image that we do not directly nest `message.pattern.text`, but `message.body["variant"].text` - body is here interchanged with `pattern` because it probably makes sense to have `pattern` in `variant` again so it's then `message.body["variant].pattern.text`

please don't nail me on the api if we should go with array or object for `body` - I'm not sure.

**Comment by ivanhofer** [comment]
I think @felixhaeberle has a good point here. Variants could live inside the `Message` object.

**Comment by samuelstroschein** [comment]
@felixhaeberle point about variants being in a message, not a different message, seems correctish. 

**Example type**

```ts
type Message = {
  id: string
  languageTag: LanguageTag
  pattern: Record<Variant, Pattern> 
}
```

**Problem**

- messages become nested now, making query and working with messages more difficult

```
const message = inlang.messages.query.get({ where: { id: "some.message", languageTag: "de", pattern: { variant: "default" } } )

const defaultMessage = message.pattern['default']

// doesn't work
console.log(message.variant)

```

flat messages is definitely simpler mental model (also for writing plugins)

```ts
const message = inlang.messages.query.get({ where: { id: "some.message", languageTag: "de", variant: "default" } )

// works
console.log(message.variant)
```

---

Off topic notes for @felixhaeberle 

> message.body["variant].pattern.text

No idea where `pattern.text` is coming from. A pattern is an array of pattern elements (Text | Placeholder). 

> I'm almost 100% sure going with multiple bodies is the right thing to do at some point, also speaking about pluralization for example

Pluralization is handled within a pattern. Separate "bodies"/patterns for pluralization are not going to happen because wrong. A pattern defines how a "text" is rendered to the user, including pluralization, gender, variables, functions, etc.

**Comment by samuelstroschein** [comment]
Taking the thought of a message has multiple patterns/shouldn't be split into multiple messages further buy thinking about future props: 

```ts
type Message = {
  id: string
  // description: string
  // referencesInCode: Array<CodeLocation>
  // ...
  pattern: Record<LanguageTag, Record<Variant, Array<Text | Placeholder>>
}

const pattern = message.pattern["en"]["default"]

// might miss variant in another language
const availableVariantsInSource = Object.keys(message.pattern["en"])

// omg horrible API 
const allVariants = new Set(Object.keys(inlang.config.languageTags.map((tag) => Object.keys(message.pattern[tag]).flat())

// should be 
const allVariants = message.variants
```

Looking at that type, description is likely shared across every Message regardless of languageTag or variant. However, a `comments` field would be related to a languageTag again (?).

**Comment by felixhaeberle** [comment]
> No idea where pattern.text is coming from. 

😂 I just wanted to give an easy example typing on my phone while cooking with saucy hands and not make my comment example type-safe, I know the real structure of pattern but simplified it for "a quick comment". 

> Separate "bodies"/patterns for pluralization are not going to happen because wrong.

I don't think this is ultimately wrong, it's just how you define/think about a variant. 💆‍♂️

i18n for example even creates new messages for pluralization. As far as I follow the discussion we do not even consider that an want to nest them not only in the first object hierarchy (with variants) "most deep down" (inside pattern). TLDR: Wild spectrum of **where** to put pluralization & other data (comments, source tags). 

offtopic

> A pattern defines how a "text" is rendered to the user

*Do you mean "rendered" in terms of UI? We should not structure our data in a way it's nice for the UI, but rather how it makes sense from a data perspective.*

**Comment by samuelstroschein** [comment]
> offtopic

> A pattern defines how a "text" is rendered to the user

> Do you mean "rendered" in terms of UI? We should not structure our data in a way it's nice for the UI, but rather how it makes sense from a data perspective.

Yes, rendered to the UI. Yes, that's the way to store text. We basically have text nodes that need to be serialized. Store them as nodes [in a pattern]. That's how text formatting works :)

**Comment by felixhaeberle** [comment]
My proposal is to have a `body` with `variant` items (you have to specify a default) for now and inside the `body` the `pattern`. It then simply "duplicates" what we have already in place with `Resource` and `Message`, but with `Message` and `Variant`.

https://github.com/inlang/inlang/blob/9f5ca75b1f07cd615d48f424844bd4bfeac854af/source-code/core/src/ast/schema.ts#L62-L83

**Comment by samuelstroschein** [comment]
@felixhaeberle your code example is outdated. pease reference the api-spec branch.

**Comment by felixhaeberle** [comment]
For my argument, I wanted to showcase the core implementation like it is rn, not the one we are currently discussing.

**Comment by NilsJacobsen** [comment]
But we need to merge this one :D

**Comment by felixhaeberle** [comment]
Therefore, I explained my changes. I can do a PR if things are not clear yet.

**Comment by NilsJacobsen** [comment]
Proposal 1:
type Message = {
  id: string
  languageTag: LanguageTag
  variant: Variant
  pattern: Array<Text | Placeholder>
}

Proposal 2:
type Message = {
  id: string
  languageTag: LanguageTag
  pattern: Record<Variant, Pattern> 
}

Is that right, folks?

**Comment by felixhaeberle** [comment]
no, it's https://github.com/inlang/inlang/pull/1166

**Comment by NilsJacobsen** [comment]
**Proposal 1:**
```ts
type Message = {
  id: string
  languageTag: LanguageTag
  variant: Variant
  pattern: Array<Text | Placeholder>
}
```

**Proposal 2:**
```ts
type Message = {
  id: string
  languageTag: LanguageTag
  pattern: Record<Variant, Pattern> 
}
```

**Proposal 3:**
```ts
type Message = {
  id: string
  languageTag: LanguageTag
  pattern: Array<MessageVariant>
}

type MessageVariant = {
  id: string
  pattern: Array<Text | Placeholder>
}
```

@felixhaeberle, that should be proposal 3, then?

**Comment by NilsJacobsen** [comment]
On the one side, I like that the messages that belong to each other (id/languageTag wise) are grouped.

But I feel like that will produce more complexity in the plugins. Because one single entity was always a message, now we want to merge multiple messages, which leads to negative effects on the ecosystem. At the same time, the query function gets also more complicated because with proposal 1 it's just a simple filter function.

@felixhaeberle what is the benefit of proposal 3?

**Comment by felixhaeberle** [comment]
> which leads to negative effects on the ecosystem

can you elaborate?

**Comment by NilsJacobsen** [comment]
When it is more complex to build plugins, the ecosystem will grow slower.

Why is 3 more consequently?

**Comment by felixhaeberle** [comment]
### Why is 3 more consequently?

- P1: having **multiple messages** with same `id` + `languageTag` because of different `variant`
- P1: we must be certain that variants will be the only addition for uniqueness –> we are probably not certain
- P3: a query with `id` + `languageTag` only returns **single message** (unique)
- P3: easy to extend `MessageVariant` type in future, no uniqueness problems

**Comment by samuelstroschein** [comment]
Following proposal 3 by @felixhaeberle, the logical follow-up is to make language tags belong to a message too. 

```ts
type Message = {
  id: string
  languageTags: LanguageTag[]
  variants: string[]
  patterns: Record<LanguageTag, Record<Variant, Pattern>>
```

A query has no uniqueness problem anymore because a message is always uniquely identified by an id. But, the API becomes a bit more cumbersome. 

```ts
const message = query.get({ where: { id: "first-message" }})
for (const tag of message.languageTags){
  for (const variant of message.variants) {
    const pattern = message.patterns[tag][variant]
    if (pattern === undefined){
      // do something
    }
    console.log(pattern)
  }
  console.log(message.pattern[tag]["default"))
}
```

On the flip side, adding additional properties to a Message makes sense then. 

```diff
type Message = {
  id: string
+  description: string
  languageTags: LanguageTag[]
  variants: string[]
  patterns: Record<LanguageTag, Record<Variant, Pattern>>
```

Dear Ladies and Gentlemen, we are starting to model relations in JS objects :D 

**Pros**

- close to modeling a relational schema (pretty future-proof)

**Cons**

- complexer query 
- complexer writing plugins

**Comment by felixhaeberle** [comment]
> complexer query

why? I would argue more powerful query. 

> complexer writing plugins

no just other architectural approach needed (based around one message object)

**Comment by samuelstroschein** [comment]
Or, we put the `LanguageTag` into the variant. 

```ts
type Message = {
  id: string
  body: Array<MessageVariant>
}

type MessageVariant = {
  id: string | "default"
  languageTag: LanguageTag
  pattern: Array<Text | Placeholder>
}
```

```ts
const message = query.get({ where: { id: "first-message" }})

const germanVariants = message.body.filter((variant) => variant.languageTag === "de")

const germanDefault = germanVariants.filter((variant) => id === "default")
```

**Pros**

- we can use plain JS for filtering

**Cons**

- plain JS for filtering can become a performance bottleneck. BUT, then we can slowly extend query over time

**Comment by NilsJacobsen** [comment]
I personally think that get's almost more complex than before the refactoring. 

We removed two lines of code by removing the addLanguage functionality with languageTags in the config and now we add a lot to handle all of that complex merging. 😅

**Comment by NilsJacobsen** [comment]
> Or, we put the LanguageTag into the variant.

Looks a bit like Resources again :D

**Comment by felixhaeberle** [comment]
> Looks a bit like Resources again :D

Perfect! You got it! 😍 haha
No seriously, @samuelstroschein is now grouping by `Message` and not by language / `Resource` anymore – this is the proposed simplicity.

**Comment by NilsJacobsen** [comment]
To get that right. It is not getting simpler. Not for plugins or apps. But we can get the advantage of extendability/flexibility. @felixhaeberle

**Comment by felixhaeberle** [comment]
> To get that right. It is not getting simpler. Not for plugins or apps. But we can get the advantage of extendability/flexibility.

one could argue simpler because:
- mental model around one message makes more sense
- message architecture in plugins is easier than around a resource

> offtopic @samuelstroschein: ("complexer" -> do you have your Grammarly on? its "more complex to") :D

**Comment by NilsJacobsen** [comment]
I agree, comparing to resources yes, but comparing to a message array no.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink what's your opinion?

**Comment by samuelstroschein** [comment]
Guys, hop on a call? 

We gotta make a decision. Too much back and forth.

**Comment by samuelstroschein** [comment]
Closing as "one message, one id, multiple patterns". 

A message is always uniquely identified as a single message. Note: this must be linted.
