### ISSUE TITLE
Document existing converters

### ISSUE THREAD

**Issue by Marr11317** [inlang/inlang#116]
[This page](https://inlang.dev/docs/glossary/converter) says translations can be converted with converters when downloading formats other than fluent.

Is there any existing converter?  I couldn't find info regarding existing options.

Or is that wip?

**Comment by Marr11317** [comment]
Actually, just found [this](https://github.com/inlang/inlang/tree/main/packages/fluent-syntax-converters/src/converters). I guess this means there are existing converters. 

Should they be documented?

**Comment by samuelstroschein** [comment]
Hi @Marr11317, 

I opened a pull request #117. Can you review it?

**Comment by samuelstroschein** [comment]
> Or is that wip?

It's also wip btw. What syntax/format are you using?

**Comment by Marr11317** [comment]
Looks good. That's all the info I needed when reading the docs.

I am looking for a fluent->message-format compiler.

Actually, I am just trying to get javascript messages, but I use message-format to transpile to js.

**Comment by samuelstroschein** [comment]
> fluent->message-format compiler 

I assume as JSON file correct? Added to https://github.com/inlang/inlang/discussions/104
