### ISSUE TITLE
Show a big banner that node >= 18 is required for inlang to work

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1181]
We often get bug reports where the root cause is that a node version smaller than 18 is getting used.

We should create a helper function that checks the node version and outputs a very prominent banner, that shows that Node 18 should be installed.
The function then should throw an error and stop the execution.

This function should be called when starting the CLI. It also makes sense for the SDK.

@inlang/team what do you think?

**Comment by felixhaeberle** [comment]
This is already in place using node / npm build-in `engine` spec & `engine-strict=true`. The main reason it's not working is that people have outdated CLI's — although we could advise them to update.

This is a task which is on my list and I'll create an issue for it. Closing this for now.

**Comment by ivanhofer** [comment]
I can't see this in the code. Where is it?

**Comment by ivanhofer** [comment]
![image](https://github.com/inlang/inlang/assets/21335119/e33013cd-5d2c-49c3-849a-16944df1729f)
It is just a warning. Shouln't it throw?

**Comment by ivanhofer** [comment]
Maybe we should just wait to see if we still get a lot of issues with the current approach. If yes, I would throw an error.

**Comment by ivanhofer** [comment]
The current warning message is not so obvious.. I think most people ignore it like they do on every `npm i` ^^
