### ISSUE TITLE
re-export core modules in `@inlang/instance`

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1184]
## Problem 

1. Apps must import all core modules separately. 
2. The manually imported core modules must be compatible to the instance dependencies. 

## Proposal 

Re-export core modules in @inlang/instance to provide apps with only one dependency they need to add and avoid the versioning problem.

- it is reasonable to expect apps to import many core modules
- the used core modules should be compatible which each other which is ensured by only adding a single `@inlang/instance` dependency. 

```diff
"dependencies": {
	"@inlang/instance": "3.8.0",
-	"@inlang/environment": "1.0.0",
-	"@inlang/config": "2.3.2",
-	"@inlang/messages": "1.4.2",
-	"@inlang/plugin-api": "2.1.0",
-	"@inlang/lint-api": "1.9.0",
-	"@inlang/language-tag": "1.0.1",
-	"@inlang/result": "1.2.0",
	"deepmerge-ts": "^5.1.0",
	"ts-dedent": "^2.2.0",
	"zod": "^3.21.4"
}
```

### Proposal 1 Re-export via paths  

```ts
import { createInlang } from "@inlang/instance"
import { InlangConfig } from "@inlang/instance/config"
import { InlangEnvironment } from "@inlang/instance/environment"
import { PluginApi } from "@inlang/instance/plugin-api"
...
```

### Proposal 2 Re-export all in one (ESM has tree-shaking)

```ts
import { createInlang, InlangConfig, InlangEnvironment, PluginApi } from "@inlang/instance"
```

**Comment by samuelstroschein** [comment]
@inlang/team

**Comment by samuelstroschein** [comment]
Off topic: i find `@inlang/app` better than `@inlang/instance` 

> "if you want to build an inlang app, use @inlang/app".

**Comment by samuelstroschein** [comment]
Vote: Proposal 1

**Comment by samuelstroschein** [comment]
Vote: Proposal 2

**Comment by samuelstroschein** [comment]
Off topic: i find @inlang/app better than @inlang/instance

"if you want to build an inlang app, use @inlang/app".

**Comment by ivanhofer** [comment]
Do we actually need to publish `@inlang/plugin-api` as a separate package?
We don't have the `@inlang/core` namespace anymore, so we could use that.
Also related: https://github.com/orgs/inlang/projects/35/views/1?pane=issue&itemId=34367601

**Comment by samuelstroschein** [comment]
> Do we actually need to publish @inlang/plugin-api as a separate package? 

Yeah. Plugin authors need it to write plugins :)

> Also related: https://github.com/orgs/inlang/projects/35/views/1?pane=issue&itemId=34367601 

Ah, I don't know. "core" is more a thing for us than external devs. If a dev wants to use "result", go import @inlang/result. Use messages? Go import @inlang/messages. 

Besides, a new namespace complicates deployment, key handling etc.

**Comment by ivanhofer** [comment]
Why not import `Result` from `@inlang/core/result`?
This issue is about that developers don't want to install X different packages, so why don't we just bundle them into `@inlang/core`? I don't see the benefit of publishing X different modules.

**Comment by samuelstroschein** [comment]
Aha, you want to use `@inlang/core` to export all core modules? 

So proposal 2, but instead of re-export via `instance/app`, have `core` as a dedicated package that re-exports everything? 

```ts
import { createInlang } from "@inlang/core/instance"
import { InlangConfig } from "@inlang/core/config"
import { InlangEnvironment } from "@inlang/core/environment"
import { PluginApi } from "@inlang/core/plugin-api"
```

vs

```ts
import { createInlang } from "@inlang/app"
import { InlangConfig } from "@inlang/app/config"
import { InlangEnvironment } from "@inlang/app/environment"
import { PluginApi } from "@inlang/app/plugin-api"
```

Seems reasonable. Observation: `@inlang/instance` imports every other core module. Thus, `@inlang/core` would depend on `@inlang/instance`. Hence, we would have two different packages with the same dependencies.

**Comment by samuelstroschein** [comment]
### Proposal 

Re-export dependencies of `@inlang/app` and `@inlang/plugin` to satisfy the different use-cases: 

1. Build an app? Add `@inlang/app` as a dependency
2. Build a plugin? Add `@inlang/plugin` as a dependency
3. Want to codeshare? Add whatever `@inlang/*` dependency you need 

**Pros**

- Easy communication. Build a plugin? Build an app? 
- Strict semver for the different APIs. 
- Only one dependency required for apps and plugins. 
- No potential "Why does @inlang/core exists?"

**Cons**

- No one import to rule them (but that causes semver problems) 

Vote with 👍 👎 pls

### Elobatoration

> This issue is about that developers don't want to install X different packages, so why don't we just bundle them into @inlang/core?  

Plugin APIs, config, and instance APIs change irrespective of each other. 

- Bundling three different APIs in one module entails one version for 3 different APIs. 
- A breaking change in `instance` might not be a breaking change in `config` or `plugin-api`. 
- A breaking change in `config` does not lead to a new plugin API v2. 

### Scenarios

#### Scenario - Inlang Plugin Developer 

```ts
import { } from "@inlang/plugin-api"
```

- I want to use the plugin API and only deal with the plugin API. 
- A breaking change in `config` is not my concern and neither do I want `@inlang/config` as a dependency. 
- Ideally, I only need `@inlang/plugin-api` as a dependency. 

#### Scenario - Inlang App Developer 

```ts
import { } from "@inlang/app"
```

- I only want to add `@inlang/app` as a dependency. 
- Any breaking change in a dependency of `@inlang/app` is (likely/automatically) a breaking change in `@inlang/app`. 

#### Scenario - Inlang User 

```ts
{
  sourceLanguageTag: ["de"],
  languageTags: ["de", "en"],
  plugins: [
    ...
  ]
}
```

- I only care about the config schema from inlang core. 
- Hence, breaking changes in inlang core that don't affect the config are irrelevant. 
- Plugin changes are outside the scope of core. But, I can only set plugin options anyways. 

#### Scenario - Developer that wants to use inlang modules for their own benefit

```ts
import { } from "@inlang/messages"
import { } from "@inlang/language-tag"
```

Think about @amannn that builds https://github.com/amannn and maybe wants to use `@inlang/messages` and `@inlang/language-tag` independently.

- every module should be its own published module  

### Conclusions

1. A separation makes sense. 
2. But, we want to consolidate around the use cases. 
3. A generic `@inlang/core` would lead to "What is the breaking change for my plugin again?" Even though no breaking change was conducted.

**Comment by NiklasBuchfink** [comment]
Had exactly the same in mind.
I'm building an app: `import * from @inlang/app`
I'm building a plugin: `import * from @inlang/plugin`

**Comment by samuelstroschein** [comment]
Completed in https://github.com/inlang/inlang/commit/d250261453ca6e87de645826fabb4ab57a920c15. 

- exports without subpath because a) subpaths need to be explained and b) lead to N import statement instead of 1.
