### ISSUE TITLE
Less Permissive GitHub Authentication

### ISSUE THREAD

**Issue by mfranzs** [inlang/inlang#1188]
Hey;

Signing into Inlang requires giving a lot of permissions. Many of these don't seem necessary. Is there some way that I can log in without giving so many permissions? Thanks!

<img width="458" alt="CleanShot 2023-07-29 at 09 59 28@2x" src="https://github.com/inlang/inlang/assets/953103/1f00a9c3-1408-4df6-bbe7-c84b7569d10c">

Suggestions:
1. Option to only provide access to public repos.
2. Option to only provide access to specific repos (most preferred). 

Thanks for Inlang!

**Comment by samuelstroschein** [comment]
Hi @mfranzs!

Not at the moment. The auth system naively requests all permissions to enable the cloning of private repositories. Feel free to upvote https://github.com/inlang/inlang/discussions/1120. 

PS I am closing this issue in favor of the feature request. Feel free to comment on the feature request
