### ISSUE TITLE
Package `@inlang/cli` not found in the registry

### ISSUE THREAD

**Issue by b3ngg** [inlang/inlang#119]
**Describe the bug**
When trying to install the CLI via NPM, I get an error message that the package is not found.

**To Reproduce**
1. Create a new folder
2. Run `npm init -y`
3. Run `npm i @inlang/cli -D`
4. See error: 

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@inlang%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@inlang/cli@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2022-03-25T08_22_13_677Z-debug-0.log
```

**Expected behavior**
The package should be in the registry and install. 

**Desktop:**
 - OS: MacOS
- Node Version: v17.4.0

**Comment by samuelstroschein** [comment]
Indeed. I am refactoring inlang to work on top of git, see https://github.com/inlang/inlang/discussions/115. 

I expect the work to be complete within the next 4 weeks. In the meantime, you can use the VSCode extension and dashboard nevertheless. Just the CLI is not available for now.

**Comment by b3ngg** [comment]
Alright, thank you. 
Maybe add a notice in the README and in the docs? Could be confusing for people like me. 

Looking forward for the finished refactor. Looks like a really cool project!

**Comment by samuelstroschein** [comment]
As part of https://github.com/inlang/inlang/pull/127, the architecture is rebuilt and this issue becomes obsolete.

**Comment by samuelstroschein** [comment]
@b3ngg you could take a look at inlang again. 

The CLI is not out yet. The VSCode extension will be re-released within the next 7 days.
