### ISSUE TITLE
vscode extension bug

### ISSUE THREAD

**Issue by GetCurious** [inlang/inlang#120]
`/c:/Users/Nate/Desktop/my-app/inlang.config.json` is a UNIX path.
![image](https://user-images.githubusercontent.com/8876854/161433757-64c54c11-d36e-4ba0-9715-896b03a98eac.png)

**Comment by samuelstroschein** [comment]
Indeed. Likely not a valid path on Windows machines which might lead to that issue. I am refactoring inlang, see #115. Afterwards, I will look into this issue.

**Comment by samuelstroschein** [comment]
Closing as the vs code extension will be re-written. Will take some time.
