### ISSUE TITLE
setup must return an object with the properties a plugin/lintRule defines

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1206]
@ivanhofer is author of this issue

We face several issues with the current approach:
- we have shared state between invocations
  This is probably not a problem for plugins, but it is for lint rules. Lint rules will run X times and can also run in parallel.
  If `setup` initializes some state, it will probably override it for another lint process that is currently running
- we need to call `setup` multiple times
  It is almost impossible to test, because I can't run `setup` multiple times to see how it behaves with different params
- we have to write code to make sure setup was called
  > I found this code, but I guess we should assume that setup was always called

  ![Image](https://user-images.githubusercontent.com/21335119/258033463-fabb6c85-1ad0-4ce7-9569-43c91bcf43b5.png)
  ![Image](https://user-images.githubusercontent.com/21335119/258033533-61e26848-605a-4e27-b4aa-d782ef85255f.png)

Solution:
- `setup` should only be called once
- `setup` returns an object with the properties it wants to define
- `setup` makes it possible to scope variables to an instance
- `setup` should only be called once during "resolving"
- we don't need to pass `settings` around as they were already resolved

Downsides:
- We don't know what a plugins defines before calling `setup`, but is this really so bad??
- Resolution algorithm becomes slightly more complicated
- some may think: differentiation between `LintRule` and `InitializedLintRule` but I see this as an advantage as we can add new properties and remove some others we only need for `setup`

**Comment by samuelstroschein** [comment]
I am not the author, @ivanhofer is. I pressed "create an issue" to be able to comment. 

@ivanhofer, it seems like the problem you are facing stem from the assumption that `setup` is (needs?) to be called multiple times. Why does setup need to be called multiple times?

**Comment by ivanhofer** [comment]
Because the `lint` function receives all uninitialized things and each time the function get's called, it needs to call setup because it does not know if setup was already called.
Storing setup calls in memory makes it hard to test the `lint` functionality.

**Comment by ivanhofer** [comment]
decision was made to get rid of `setup`
