### ISSUE TITLE
[bug] TypeScript type error

### ISSUE THREAD

**Issue by anhtuank7c** [inlang/inlang#1212]
### Did you check if the config file includes errors?

- [X] Yes, I have validated the config file

### Problem

I've used inlang for SvelteKit project which use TypeScript format.
I got a problem with implement types for `+layout.server.ts`.
```
import type { LayoutServerLoad } from "./$types";  <= this 'cause the error, work normally if just simple remove this one

export const load = async ({ locals }) => {
	return { user: locals.user };
};

```
If I import a types into this file, the inlang will 'cause an error like this:
![image](https://github.com/inlang/inlang/assets/3163410/cb8f50fd-bffa-4abd-8485-3697f810ef53)

### Expected behavior

Work normally with TypeScript types

### Reproduction

Just simple import a types to `+layout.server.ts`, it will crash on the next time you do `pnpm run dev`

```typescript
// routes/+layout.server.ts
import type { LayoutServerLoad } from "./$types";

export const load = async () => {
	return { foo: 'bar' };
};

```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 1.24 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/Library/pnpm/npm
    pnpm: 7.22.0 - ~/Library/pnpm/pnpm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
  npmPackages:
    @inlang/sdk-js: ^0.11.3 => 0.11.3 
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1 
    @sveltejs/kit: ^1.20.4 => 1.22.4 
    svelte: ^4.0.5 => 4.1.2 
```
```


### Other information

_No response_

**Comment by ivanhofer** [comment]
Thank you for opening the issue! It was fixed in version `0.11.4`.
