### ISSUE TITLE
update plugin registry/create marketplace

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1224]
## Context

The plugin registry is now turning into a marketplace that consists of app, plugins, and lint rules. 

```
marketplace
- apps
- plugins
- lint rules
- ... (more soon?)
```

## Scope

1. Have a JSON with a list of modules.
2. Fetch the modules during the build step, gather the metadata, and create a new JSON file that contains all modules with metadata that can be statically imported.  

### Essential

- [x] implement build step logic
- [x] `getLatestVersion(module)` function    

## Additional information 

- https://github.com/inlang/inlang/pull/1163#issuecomment-1646879127

**Comment by samuelstroschein** [comment]
@floriandwt I assigned you the task as part of #1242. 

The idea is to have a script `buildRegistry.js` that fetches all modules defined in let's say `registry.json` to generate `src/registry.js` that contains all available apps, plugins and lint rules with metadata. Similar to https://github.com/inlang/inlang/blob/aa01d5501cb8e1c31dbc35c99e142d866b9605a8/source-code/core/language-tag/buildTagRegistry.js

**Comment by floriandwt** [comment]
@samuelstroschein Okay 👍
The goal is to have the registry files in inlang/marketplace so we can get rid of the plugin-registry which is currently providing the hard-coded info for the docs?

**Comment by samuelstroschein** [comment]
@floriandwt Yes. 

1. introduce a new library called `@inlang/marketplace` (you can copy and paste `plugin-registry` for that)
2. have a `registry.json` file that external developers can add their plugins and lint rules to (just an array of modules: [ ]), apps need to have a separate key

```json
{
  apps: [
    {
       displayName: {
         en: "hey"
       } 
       // ...
  ],
  modules: [
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js".
    // ...
  ]
}

3. Use `registry.json` to fetch the metadata for the modules and create a `src/registry.js` file that helps you build the marketplace

**Comment by floriandwt** [comment]
Closing as of https://github.com/inlang/inlang/pull/1263
