### ISSUE TITLE
App is redirecting to http instead of https with URL strategy

### ISSUE THREAD

**Issue by babakar7** [inlang/inlang#1226]
### Did you check if the config file includes errors?

- [X] Yes, I have validated the config file

### Problem

App is redirecting to http instead of https

### Expected behavior

App should redirect to https 

### Reproduction

Enter URL using URL strategy

### System Info

```Shell
n/a
```

**Comment by ivanhofer** [comment]
We can't investigate issues without a reproduction. Feel free to open the issue again if you provide a link to a repo where we can reproduce the issue.
