### ISSUE TITLE
how should users interact with the badge generator as an app when it's no longer in the docs (subpage, popup …?)

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1244]

**Comment by floriandwt** [comment]
@jannesblobel do we have any numbers on how many badges have been created in the last 3 months? Posthog always shows me a 1. I'm agreeing to remove it if the numbers are low anyway.

**Comment by samuelstroschein** [comment]
@floriandwt seems neglactable


<img width="968" alt="CleanShot 2023-08-14 at 16 28 06@2x" src="https://github.com/inlang/inlang/assets/35429197/689cb7b1-3c01-40bd-be76-cb9355606a7a">
