### ISSUE TITLE
is rendering markdown READMEs essential for this initiative?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1246]
## Context

(Some) marketplace items need a longer README. 

## Proposal 1 - Link to Github (and deprecate in the future) 

```ts
meta: {
  // ...
  linkToReadme: {
    en: "github.com/x/x/en.md"
  }
}

```

**Pros**

- Simple link to GitHub

**Cons**

- links to external site (reduces UX and SEO)  

## Proposal 2 - Fetch readme and render like we render our docs

1. Fetch the markdown file
2. Render it within the marketplace

```ts
meta: {
  // ...
  readme: {
    en: "github.com/x/x/en.md"
  }
}

```

**Pros**

- increased UX 
- SEO 

**Cons**

- markdown renderer needs to be externalized (not difficult)
- markdown tags/syntax need to be explained

**Comment by samuelstroschein** [comment]
Given that #1242 is about a quick win, going with proposal 1 seems better. proposal 2 can be implemented in the future.

**Comment by floriandwt** [comment]
I agree too. SEO in this case is nice to have anyway, so not a big point for the first implementation.

**Comment by floriandwt** [comment]
Closing as agreed on proposal 1 (link to GitHub)
