### ISSUE TITLE
update ide extension

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1247]
- [ ] use new inlang api
- [ ] replace hardcoded missing message logic by linting system

**Comment by samuelstroschein** [comment]
@NiklasBuchfink are you working on this? Otherwise, (as I understand) @openscript can take over

**Comment by NiklasBuchfink** [comment]
@openscript can take over 👍

**Comment by felixhaeberle** [comment]
@NiklasBuchfink what's the progress here? :)

**Comment by samuelstroschein** [comment]
@felixhaeberle no progress. @openscript hasn't started I believe

**Comment by openscript** [comment]
> @felixhaeberle no progress. @openscript hasn't started I believe

Just looked into it, but barely wrote code.

**Comment by felixhaeberle** [comment]
@openscript Then I'll continue 👍

**Comment by felixhaeberle** [comment]
ide extension is not fully updated to the new inlang app SDK. see #1142 ✨

TODO: testing.

**Comment by samuelstroschein** [comment]
Is this complete?
