### ISSUE TITLE
update cli to use new inlang api

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1248]
### Must have

- [x] inlang config validate
- [x] inlang lint command
- [x] inlang machine translate command
- [x] inlang open editor command 

### Should have 

- [x] linting based on lint system; not hardcoded stuff

### Out of scope

- [ ]  inlang config update / updating logic of plugins
- [ ] inlang config init
- [ ] auto config migrate [will be handled in @inlang/app]

**Comment by samuelstroschein** [comment]
I am removing the `--config` flag because nobody is using it, to simplify application logic, and increase consistency with other apps that do not support a custom config path.

**Comment by ivanhofer** [comment]
I probably need to pass the exact config path to `createInlang`. I'm currently refactoring the SDK and I need to test a few things first..

**Comment by samuelstroschein** [comment]
@ivanhofer okay, lmk if you need the pass the config path down to `createInlang`. Naively, I would assume that you can use `repositoryPath` too and let `createInlang` resolve the config.

**Comment by ivanhofer** [comment]
> Naively, I would assume that you can use `repositoryPath` too and let `createInlang` resolve the config.

Once vite bundles the application, some files receive a hash and will be moved to another folder. I assume this happens to the `inlang.config.json` too. For now we probably don't need it but once the server should read messages from e.g. a database, we certainly need to be able to run `createInlang` after build.

**Comment by ivanhofer** [comment]
I have added the functionality to import the config file via a data uri: [`abf405b` (#1142)](https://github.com/inlang/inlang/pull/1142/commits/abf405baed048d813d5e26f3ebbb0ec8b1afd8cb)
I will need this soon. This means we can't get rid of `repositoryPath` in `createInlang`, but we should certainly make it optional as soon as we have a good path resolve logic.

**Comment by samuelstroschein** [comment]
@ivanhofer you mean can't get rid of `configPath`? We need `repositoryPath` in any case. 

(The proposal is to replace `configPath` with `repositoryPath` and let createInlang resolve the config. A better name might be `repositoryRootPath`)

**Comment by ivanhofer** [comment]
Yes, I meant `configPath` 👍.
`repositoryRootPath` is certainly the better approach if we plan to have a config file resolve logic.
But then I need another property for the SDK to be able to pass the config as URI, as JSON string or as JSON object

**Comment by felixhaeberle** [comment]
@samuelstroschein Was the decision made to remove `--config`? This would be a breaking change for a few existing repos for which we built it for.

@janfjohannes are you now responsible for pushing this further or should I take over?

**Comment by samuelstroschein** [comment]
> @felixhaeberle Was the decision made to remove --config?

Yes.  

> This would be a breaking change for a few existing repos for which we built it for.

Not a single repo uses this flag according to posthog.

**Comment by ivanhofer** [comment]
> Not a single repo uses this flag according to telemet

We added it because users have asked for it.

**Comment by samuelstroschein** [comment]
> We added it because users have asked for it. 

I know, but we shouldn't have. Nobody uses the flag.

**Comment by samuelstroschein** [comment]
@felixhaeberle check for yourself. other commands seem to be captured correctly

**Comment by felixhaeberle** [comment]
@samuelstroschein At least Open Assistant is using it https://github.com/LAION-AI/Open-Assistant/blob/main/website/package.json

We have telemetry for that in place, at least you can set up a filter for `args` field of the `CLI command executed` event which `contains` `--config`, and there, we don't have any events. 

Good thing tho: Flags are getting recognized, for example `--force` of `machine translate` is getting used heavily.

If we want to deprecate `--config` for another solution / no solution, now is the time.

**Comment by samuelstroschein** [comment]
@felixhaeberle i stringly vote to remove `--config` for now. 

- nobody uses the flag
- open assistant doesn't use the cli (learning here: don't create extra commands. linting must bein the main lint command)

**Comment by samuelstroschein** [comment]
@janfjohannes what's the status?

**Comment by janfjohannes** [comment]
@samuelstroschein  lint, translate and open, config validate work im doing continuing on testing today but i dont think it should interfere much with a new command

**Comment by samuelstroschein** [comment]
What is the status?

**Comment by janfjohannes** [comment]
@samuelstroschein  finally finished with something i think is a good mix of not testing internals but also not being an integration test (which also could make sense at some time)    the "inlang module build command" i decided to not test in the end (let me know if you agree)  as it will be used anyways to build our plugins and in the end to test it i would copy over the same build commands but as they run in the build pipeline breaking this would be catched in our current ci.

**Comment by samuelstroschein** [comment]
@janfjohannes not testing module build seems OK indeed. If the command is broken, we will be the first ones to notice
