### ISSUE TITLE
are we sure that the `Message` structure is the right one to settle on?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1251]
From @ivanhofer:

I was not part of the discussion, so I don't really know why we settled on this specific body structure. For me it feels weird and I'm unsure if it should look like this.

**Comment by samuelstroschein** [comment]
Also ran into a "huh, that's weird" moment with this code: 

```ts
for (const variant of message.body[sourceLanguageTag]) {
}
``

I would have expected: 

```
for (const variant of message.body[sourceLanguageTag].variants){
}

**Comment by samuelstroschein** [comment]
@ivanhofer, what weirdness did you run into?

**Comment by samuelstroschein** [comment]
Another one https://github.com/inlang/inlang/pull/1142#discussion_r1294459049

<img width="802" alt="CleanShot 2023-08-15 at 13 09 07@2x" src="https://github.com/inlang/inlang/assets/35429197/9104bc50-1f7e-4fe0-881c-dabb0f1a3933">

**Comment by samuelstroschein** [comment]
1. Because defining an empty array is simple. 
2. Because we would need conditional logic everywhere to distinguish between a message with a single pattern and a message with multiple patterns. 

The major shift roots from treating messages partially like relational data/what apps need. A message can have selectors and multiple variants. From an app standpoint, much better because the data structure reflects how users think about messages and subsequently the UI. No mental concept and application logic that distinguishes between types of Messages is required.  

What MessageFormat or other syntax schemas defines as entry points is likely irrelevant for inlang as long as all message "types" (single pattern, multi-variant) are supported. Optimizing the data structure for support of all types of messages is assumed to lead to less complexity in the system than conditional logic at runtime.        

Regardless, we need to wait with this discussion until @NilsJacobsen is back from OOO next Monday.

**Comment by samuelstroschein** [comment]
Further observations: 

- the main weirdness seems to stem from `message.body[languageTag]` 
- while simple "quick access" for a given language tag, everything else feels off. 
- we need to use `getVariant` anyways to retrieve the pattern of a message. in that case, we can get rid of the "quick access " altogether (which would solve my "huh moment" https://github.com/inlang/inlang/issues/1251#issuecomment-1678755796) 
- we can lint a lot of issues like "hey this message contains multiple patterns for the same language tag"  

A better data structure and mental concept could be "a message has variants. a variant can exist for different language tags and selectors" aka the translation of a message is itself a variant of a message: 

```ts
type Message = {
  id: string
  selectors: []
  variants: [
    languageTag: LanguageTag
    // optional match if only one variant
    match?: {}
    pattern: Pattern
  ]
}

// example code
for (const variant of message.variants) {
  if (variant.languageTag === "en"{}
}

// getting a variant
const variant = getVariant(message, { where: { languageTag: "en", selectors: { gender: "male" } })
console.log(variant.pattern)
```

**Comment by felixhaeberle** [comment]
@samuelstroschein @NilsJacobsen can this be closed after https://discord.com/channels/897438559458430986/1134098644694470666/1143141203525767290 ?
