### ISSUE TITLE
[bug] console.log() outputting "files" multiple times

### ISSUE THREAD

**Issue by retr0cube** [inlang/inlang#1252]
### Did you check if the config file includes errors?

- [X] Yes, I have validated the config file

### Problem

Getting "files" repeatedly in the terminal (example when validating config):
```
files                                                                                                                           20:49:05
files                                                                                                                           20:49:05
files                                                                                                                           20:49:05
i 🔎 Validating the config file...                                                                                              20:49:05
√ 🎉 Inlang config is valid!                                                                                                    20:49:05

```

### Reproduction

- `npm run dev` or
- ` npx @inlang/cli config validate`

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz
    Memory: 494.87 MB / 3.90 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @inlang/sdk-js: ^0.11.8 => 0.11.8
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.4
    svelte: ^4.0.5 => 4.1.2
```

**Comment by ivanhofer** [comment]
@inlang/plugins can you please release a new version of the json plugin? I'm waiting since weeks for this

**Comment by retr0cube** [comment]
> A new version has been released ✅
> 
> Works within the inlang repo: <img alt="Bildschirm­foto 2023-08-16 um 10 48 30" width="561" src="https://user-images.githubusercontent.com/59048346/260954819-7523ae21-fa7e-4123-951e-60f3796c8094.png">
> 
> Tested with the `@inlang/plugin-json@3` and `npx @inlang/cli@latest config validate`

Does this fix the issue?

**Comment by NiklasBuchfink** [comment]
@retr0cube Yes, we fixed the issue and just forgot to properly release and purge the plugin version.
