### ISSUE TITLE
is defaultLevel in lint rules required/good UX?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1254]
## Context

For https://github.com/inlang/inlang/issues/1253, I thought it would be best to include the lint rules but set them to `warning`. The UX seems considerably better:

- `warning` doesn't "overload" a fresh project with N errors (where the reality is that most ppl will turn them off entirely or set them to warning manually).
- users can opt-in to making lint rules errors progressively as they require. 

## Proposal 

Remove `defaultLevel` from `LintRule`; always fallback wo `warning` if users did not provide a level in the linting process. 

In light of the observation that introducing new rules to a project as a warning leads to better UX, it seems to make sense to remove the possibility to set the default level and instead fallback to `warning` all the time the user has not defined a custom lint level. 

**Pros**

- anticipated better UX because projects can opt-in to errors (instead of ignoring/deactivating them)
- enables #1253 without bloating the system settings and potentially confuse users
- lint rule authors do not need to decide "hmm is this an error or a warning?". 

**Neutral**

- we can introduce a `defaultLevel` in the future if the anticipated UX increase is not achieved. 

**Cons**

- Manual opt-in to errors

**Comment by samuelstroschein** [comment]
@inlang/team please vote with 👍 or 👎

**Comment by felixhaeberle** [comment]
Not polluting projects with errors makes sense. Although there are clear errors like missing messages etc. where it would be okayish to classify them as error by us. 

---

Meta:

For me, level was always just one information of many which could potentially be populated with a lint rule. This means, I can think of lint rules being categorized or have multiple variants of lint rules. 

In such a scenario, level would only be one information, among other "data points" which make more clear how urge it is to take action.

**Comment by samuelstroschein** [comment]
@felixhaeberle I suppose that we will introduce further distinguishment between warnings and errors. For example, the CLI command inlang lint might abort on errors while warnings are mentioned but not aborted. We shall see.

**Comment by samuelstroschein** [comment]
Closed in [17304ab](https://github.com/inlang/inlang/commit/17304ababa342c4d71015ba3453295d17ffb5531)
