### ISSUE TITLE
scope system settings to `@inlang/app` only

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1260]
## Problem 

We are leaking system settings to core/multiple libraries: 

- the libraries become less useful on their own because they depend on global system settings
- following app logic with spread out global settings will become hard

## Proposal 

Scope system settings to `@inlang/app` and make sub-libraries useful on their own. 

## Additional information 

_Discussion emerged on Discord https://discord.com/channels/897438559458430986/1134098644694470666/1141740213396307992_

<img width="833" alt="CleanShot 2023-08-17 at 16 55 46@2x" src="https://github.com/inlang/inlang/assets/35429197/fbcba5cd-f048-4421-b15a-cbacbc524631">

**Comment by ivanhofer** [comment]
I think we should scope all settings so apps/plugins/lintRules just can read their own settings and not others.

**Comment by samuelstroschein** [comment]
We are already scoping the settings. This issue is about scoping system settings to app only instead of spreading system settings throughout multiple libraries

**Comment by ivanhofer** [comment]
I don't get it, but I will see what you mean after the implementation :)
