### ISSUE TITLE
use `git clean -xdf` instead of manually defining each folder in the "clean" script

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1262]
Running `npm run clean` currently does not remove all files. I constantly end up with empty directories and non-tracked files. Especially during refactoring when we rename and move around packages. In rare cases even builds failed because of that.

Using `git clean -xdf` will delete everything that is not tracked by git and clean the repository way better than the current approach.

@inlang/team should we update all "clean" scripts?

**Comment by lucidNTR** [comment]
@ivanhofer  if they are broken why not fix them? i still dont understand why fixing them is not good? 

if we replace x with X would that not still delete igonred secrets and doppler files and  also things like globally ignored todo.md i keep in the same repo?

**Comment by ivanhofer** [comment]
> @ivanhofer if they are broken why not fix them? i still dont understand why fixing them is not good?

We can fix them but they will get out of sync again. And we will still have the saem issues if we rename modules in the future.

> if we replace x with X would that not still delete igonred secrets and doppler files and also things like globally ignored todo.md i keep in the same repo?

We can also ignore `.env` and other files: https://git-scm.com/docs/git-clean#Documentation/git-clean.txt--eltpatterngt

**Comment by lucidNTR** [comment]
but what is worse to occasionally update the clean commands or that potentially unexpected files get deleted?
