### ISSUE TITLE
implement new app inlang.com/install

### ISSUE THREAD

**Issue by floriandwt** [inlang/inlang#1266]
## Goal

- Independent app making it possible to install modules from anywhere in the inlang ecosystem  

## Open questions

- [x] #1280

### Must have

- [x] Read URL query to find repo
- [x] Read localStorage.user
- [x] `login/repo selection` in case the repo couldn't be found or the user isn't logged in
- [x] Write the selected module into the new config format

### Should have

- [x] Clone and write is functioning in the background (because it could take a while)
- [x] Install multiple modules at once
- [x] Opt-in button to install in selected repo

### Nice to have

- [x] Show the current state of the install process inside of the <Title> element to be visible in the tabbar

### Out of scope
- Send a success msg to the app that was installed from when done (it's not a REST API atm, so out of scope) + everyone knows how to switch windows so not a big benefit for the users

## Further context
The need for such an app came upon introducing the marketplace installation logic #1242

**Comment by floriandwt** [comment]
Here's a detailed explanation (the audio quality is not good, sorry D:)
https://www.loom.com/share/505e9855a3b6433f9b768c60eb56cac6

<img width="806" alt="Screenshot 2023-08-21 at 8 51 39 AM" src="https://github.com/inlang/inlang/assets/92092993/0fd3e7be-1b82-4179-9f43-6b3883b3452c">

**Comment by floriandwt** [comment]
@inlang/editor happy to get some feedback from you based on the logic I proposed.

**Comment by NiklasBuchfink** [comment]
@floriandwt The flow LGTM 👍 During the repo selection, the user appropriately wants to add something to a repo in the local storage marked as a recent project. You can then show the selection of a recent project as an alternative to pasting links, as we already do for the editor 😉

**Comment by floriandwt** [comment]
Here is a small update on the current state of the inlang/install app: https://www.loom.com/share/a3392b11683c4b61a7cb508cd1c4eb42 

@NiklasBuchfink @NilsJacobsen as soon as the logic is fully implemented and other important tasks like the refactoring are done, we can discuss some UI things as you are responsible for the website and made the design before I joined :)

**Comment by NilsJacobsen** [comment]
Would love to have a little co-review session at some point 👍

**Comment by NiklasBuchfink** [comment]
I agree; let's open up the inlang design studio. We can review it together and also discuss our plan for handling new UI components in the future. :)

**Comment by floriandwt** [comment]
Closing as the install app is implemented (https://github.com/inlang/inlang/pull/1286)
Note from Samuel: _We should extract install in the future to a separate package to avoid building an gigantic monolith._
