### ISSUE TITLE
build step for `@inlang/app`

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1275]
We will probably need a build step fro `@inlang/app` to bundle all files instead of just transpiling them.
Reason: we patch `solid-js` imports and everything that gets bundled outside of our repository will not have those patches and therefore will not be able to use the reactivity.

We currently use `patch-package` to fix the import statements, but we could also switch to an `alias` approach: https://github.com/thetarnav/solid-server-reactivity
 - we probably need to define the aliases in the esbuild config if possible?

We probably also need to mention somewhere in the docs that when using `solid-js`'s reactivity, someone must patch it also in their repo.

From the example repo linked above we can assume that we have to manually call `dispose` at the end.

**Comment by ivanhofer** [comment]
Should we also expose common solid functionality under `@inlang/app/solid` so apps dont have to do this:

```ts
import {
	createEffect as _createEffect,
	// @ts-ignore
} from "solid-js/dist/solid.js"

const createEffect = _createEffect as typeof import("solid-js")["createEffect"]
```

**Comment by samuelstroschein** [comment]
Not required anymore as we got rid of patching solid js.
