### ISSUE TITLE
auto update of config for existing users

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1276]
This tasks aims to bring up a migration strategy to automatically/manually migrate the `inlang.config.js` to the new config format of `inlang.config.json`.

**Comment by samuelstroschein** [comment]
@felixhaeberle master of auto generation do you want to take this one over?

**Comment by felixhaeberle** [comment]
@samuelstroschein will come up with a plan.

**Comment by felixhaeberle** [comment]
@janfjohannes As you are also working on the config creation atm, we can discuss tomorrow based on 
https://discord.com/channels/897438559458430986/1143603643988324434/1143604085724024944

**Comment by felixhaeberle** [comment]
@janfjohannes can this be closed?
