### ISSUE TITLE
How important is implementing telemetry for the install app?

### ISSUE THREAD

**Issue by floriandwt** [inlang/inlang#1280]
We have implemented telemetry in our other apps, the question is how important is it and what is to consider?

**Comment by samuelstroschein** [comment]
Not important. 

The only interesting insight would be number of installs but we can derive that from `@inlang/app`

**Comment by samuelstroschein** [comment]
PS @floriandwt i assigned you to handle this issue since you opened it. assigning issues ensures that issues will be resolved

**Comment by floriandwt** [comment]
Closing as we can derive the only interesting insight from `@inlang/app`
