### ISSUE TITLE
improve `setConfig`

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1283]
## problem

An app currently does not know how long it takes to actually write the config to disk. 
For tests we currently have a lot of `await new Promise((resolve) => setTimeout(resolve, 0))` to wait for the config to be written on disk. But it would be nice to be able to just `await setConfig()`.

An app currently also does not know whether `setConfig` was successful or not. An invalid config might be passed and the app would not know that it was not written to disk.

## solution

Make `setConfig` async and return a `Result`.

**Comment by samuelstroschein** [comment]
Added the issue to https://github.com/inlang/inlang/issues/1290. 

We should implement async reactivity. The workarounds are buggy, we will introduce a breaking change in next 4 weeks if we don't do it now.

**Comment by felixhaeberle** [comment]
@samuelstroschein can this be closed?

**Comment by felixhaeberle** [comment]
@samuelstroschein can this be closed?

**Comment by samuelstroschein** [comment]
not really. we need an async reactive primitive. but that's another issue. so yeah lets close this one
