### ISSUE TITLE
how to define ide extension settings for sdk-js?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1288]
## Problem 

If #1287 is adopted, the question arises as to how appSpecificApi's are injected from one app (sdk-js) to another (ide-extension).

**Comment by samuelstroschein** [comment]
## Proposal - Hardcode sdk-js ide extension settings

We avoid/delay the problem by hardcoding sdk-js settings for the ide-extension in the ide-extension itself. 

**Pros**

- fast solution 
- not so dirty (we can remove the hardcoded stuff once we come up with something better)

**Cons**

- hardcoded

**Comment by samuelstroschein** [comment]
## Proposal - ide-extension offers base functionality via settings

The ide-extension logic is extracted from plugin-json, plugin-i18next, plugin-sdk-js into a generic solution within the ide-extension that is configured via settings. 

```diff 
{
  sourceLanguageTag: "en",
  languageTags: ["en"],
  modules: [],
  settings: {
+    "inlang.app.ideExtension": {
+      "messageReferencePattern": true,
+       // ...
+    }
  }
}
```

**Pros**

- other apps/plugins can set the matching settings
- plugins can still provide more sophisticated matchers

**Cons**

- we have two ways to configure the ide extension matching then a) plugins b) config
- a config will not be able to express messagerefeence matches
- lock-in to whatever parser we use for the config

**Comment by samuelstroschein** [comment]
## Proposal - the inlang-sdk-js app injects a "inlang-sdk-js-ide-extension-plugin" 

The inlang SDK js app injects a dedicated plugin for the ide extension into the modules. 

```diff
{
  sourceLanguageTag: "en",
  languageTags: ["en"],
  modules: [
+  "https://jsdelivr.com/inlang-sdk-js-ide-extension-plugin@version/index.js"
  ],
  settings: {}
}
```

**Pros**

- no need to communicate "you also need to install and configure the sdk-js-plugin" and thereby fulfill #1287 
- no version mismatching anymore because the sdk-js can bundle the ide extension plugin and automatically adjust the imported module
- no hardcoded stuff

**Cons**

- a plugin is still needed but scoped to ide-extension.

**Comment by samuelstroschein** [comment]
I favor proposal 3 (injecting an ide-extension-plugin).

**Comment by ivanhofer** [comment]
Proposal 2 is the best option. The functionality you describe above is already implemented. In the end we just rename the old plugin ^^.

**Comment by samuelstroschein** [comment]
@ivanhofer yep. rename + no config + user doesn't see the plugin

**Comment by ivanhofer** [comment]
The user will still see the plugin in his config file

**Comment by samuelstroschein** [comment]
> The user will still see the plugin in his config file

Yep, I meant that no custom settings are required for the ide-extension plugin. The plugin is just a module contained in the config.modules array :)

**Comment by samuelstroschein** [comment]
We are going to use approach 3. A dedicated ide-extension plugin for the paraglide js.
