### ISSUE TITLE
replace `inlang.config.json` files with `project.inlang.json` 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1298]
### EDIT: We should remove the concept of config files, but stick with plain .json for now, see https://github.com/inlang/inlang/issues/1298#issuecomment-1696008680

---
 
## Problems 

- Communicating both inlang config files and inlang projects [which are config files] is confusing. 
- Automatically resolving config (project) files is close to impossible
- Repositories can have multiple inlang projects (config files), yet inlang is mostly designed one repo = one inlang project. 
See flo's marketplace install proposal for example "select your repository" instead of "select your repo, select your project" or directly "select your project".

## Proposal 

Remove the concept of config files for inlang project files `android.inlang`, `first-project.inlang`. 

### 📺 [LOOM](https://www.loom.com/share/d0f332becacf4e6e9f9cfc25a4df7136?sid=51b50d9c-87b9-41c2-a278-9563cfd0fd48)

**Pros**

- no need to explain config files to end users. instead "open the inlang project" 
- no need for auto resolving, prompt the user "which project (file) do you want to open?"
- we design inlang for one repo = can have multiple projects
- overall better UX (for non devs) because of familiarity with good old "open your FinalCut/Sketch/Photoshop project" workflow

**Neutral**

- manually editing a project file (`*.inlang`) via developers is discouraged -> the better apps become, the more irrelevant this downside becomes

**Cons**

- JSON syntax highlighting for developers that open a project file (`*.inlang`) needs to come from inlang ide extension

**Comment by samuelstroschein** [comment]
@inlang/team

**Comment by Suyashtnt** [comment]
I feel like having a custom inlang file will push users away as it seems like they would have to learn a whole new language to use it. I feel like you can keep the terminology of "open your inlang repo." but the inlang repo is rather defined as `project.inlang.json`.

**Comment by samuelstroschein** [comment]
> @Suyashtnt  but the inlang repo/project is rather defined as project.inlang.json where project can be the project name.

This is a great proposal! We can force `project.inlang.json`, and (if required) loosen the strictness on "project" e.g. allow `*.inlang.json`

**Comment by samuelstroschein** [comment]
Settling on: 

`project.inlang.json` which can IF REQUIRED be loosened to `*.inlang.json` in the future and opens the possibility to introduce IF REQUIRED `*.inlang`.

**Comment by floriandwt** [comment]
Instead of throwing an error if the project.inlang.json file wasn't found, should #1266 give the opportunity to create a new project.inlang.json (to the root of the repo atm)?
We could take the function to make the implementation of different projects inside of a repo more complex in the future if needed.

**Comment by samuelstroschein** [comment]
@floriandwt I was about to say, #1299 would be the possbility to create a new project :D

**Comment by felixhaeberle** [comment]
@samuelstroschein should I push those changes?

**Comment by samuelstroschein** [comment]
@felixhaeberle what changes?

**Comment by NiklasBuchfink** [comment]
Updated the file names in our test projects

**Comment by felixhaeberle** [comment]
for anyone who wants to update their files recursively:

```sh
find /path/to/dir -type f -name 'inlang.config.json' -execdir mv {} project.inlang.json \;
```

can also be executed on a global level, to update all local project on your device.

**Comment by samuelstroschein** [comment]
@felixhaeberle is this complete?
