### ISSUE TITLE
update starter templates

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1300]
update starter templates for different metaframeworks 

- [ ] update nextjs starter
- [ ] update nuxt starter
- [ ] update svelte starter

@samuelstroschein we might not even need starter anymore because of inlang.com/new & marketplace but it's still low effort to maintain and also gives a good internal testing base (ide extension, cli, editor,...)

**Comment by samuelstroschein** [comment]
@felixhaeberle disagree. The starters are high effort as seen in this issue. Nobody uses them. Remove them.

**Comment by felixhaeberle** [comment]
@samuelstroschein the task in this issue is only to change 3 config files, this is no major time effort & we did not touch the starters in months.

**Comment by samuelstroschein** [comment]
> the task in this issue is only to change 3 config files 

No you need to update and keep the starters updated. Nobody will use a starter template that hasn't been updated in months. Just remove them. Again, nobody uses them. I haven't heard a single user talk about starter templates.

**Comment by felixhaeberle** [comment]
@samuelstroschein what is with testing the different use cases? 
at least the nextjs starter was a perfect place to test the ide extension.

**Comment by samuelstroschein** [comment]
@felixhaeberle use inlang's example repo to test the ide-extension

**Comment by felixhaeberle** [comment]
we agreed on a monorepo whic has a lot of benefits for test automation which we should also introduce (& already introduced) in the ide extension.

**Comment by felixhaeberle** [comment]
the fact that they serve us well and we didn't touch them in months are a clear sign of no maintenance burden.

**Comment by samuelstroschein** [comment]
Decided on: move starters to `source-code/end-to-end-tests` and don't market them as "started" anymore

**Comment by felixhaeberle** [comment]
closed by 3514a089518404c7cf047990c9307030a2d19f1c
