### ISSUE TITLE
add `license` to marketplace

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1305]
## Problem 

Organizations don't know which license an item on the marketplace is licensed after. 

## Proposal 

Introduce `license` field, which can only be `Apache-2.0` for now. 

- we can add more licenses upon user requests

```ts
marketplace.license: "Apache-2.0"

```

**Comment by samuelstroschein** [comment]
Like NPM

<img width="462" alt="CleanShot 2023-08-30 at 13 04 15@2x" src="https://github.com/inlang/inlang/assets/35429197/36b7f3cb-810c-44f6-b971-506b373fbc47">

**Comment by floriandwt** [comment]
https://github.com/inlang/inlang/pull/1142/commits/f964917e058e1a206eba1a1e4cf93e05a6a48f11
