### ISSUE TITLE
change packages to module and introduce marketplace-manifest.json

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1310]
- [x] have a marketplace-manifest interface (create it in `source-code/interfaces/marketplace-manifest`
- [x] the manifest can work for apps, plugins, libraries, etc. (use a union and use typebox for it!) 
- [x] change marketplace to load those manifest files (we only need a `manifests: []` in the registry.json`
- [x] remove meta.marketplace from plugins and lint rules

**Comment by floriandwt** [comment]
manifests are now implemented
