### ISSUE TITLE
[bug] Missing error message if pasted URL is incorrect

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#1314]
### On what page did you encounter the bug?

https://inlang.com/editor

### Problem

It is not clear to the user why specific URLs don't work. 
This frustrates and leads to a negative experience. 

### Expected behavior

Error message why the user can't open this Repo 
OR 
Open this URL 

### Reproduction

 1. Go to `https://inlang.com/editor`
 2.  copy and paste this URL into the input field `github.com/NiklasBuchfink/Open-Assistant`
3. Try to open this one 

### Browser Info

Chrome 

### Other information
<img width="1145" alt="CleanShot 2023-09-06 at 14 42 02@2x" src="https://github.com/inlang/inlang/assets/72493222/f7101934-84d5-471c-a0a9-de44adc2107c">

https://www.loom.com/share/87ae864ae83440ff89a8181f740cdd38

**Comment by floriandwt** [comment]
@NiklasBuchfink yes I will do that.

**Comment by floriandwt** [comment]
Changes will be applied when armageddon gets merged, see https://github.com/inlang/inlang/pull/1142/commits/3255f77c11efac93cd5f8dab53f912f2641997fc

**Comment by jannesblobel** [comment]
Thanks flo 🚀 

@NiklasBuchfink Should I fix something like this myself in the future instead of opening an issue? What do you prefer?

**Comment by NiklasBuchfink** [comment]
@jannesblobel I think if it's a minor issue/bug fix and you can do it yourself in a reasonable amount of time, you can do it and send me a quick note that you fixed something.

@floriandwt asked me a few minutes before you opened this issue if he could help me with something, and that seemed like a fitting task for the time left today.
