### ISSUE TITLE
fix node:fs/promises type for $fs

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#154]
**Describe **

The defined subset of the node fs in the config is incompatible with node:fs/promises.

**Expected behavior**
Node's promise-based fs type should be compatible with the defined fs type in the config.

**Screenshots**
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/35429197/195980666-18167238-d11c-4005-aef8-83657b35f216.png">

**Additional context**

**Comment by samuelstroschein** [comment]
simple workaround, for now, is to use `@ts-ignore` above the type error line

**Comment by openscript** [comment]
This is related to https://github.com/inlang/inlang/discussions/373
