### ISSUE TITLE
nav bar end editor needs better contrast between each other 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#175]
### Problem

The nav bar and editor seem visually too close. Both make use of a horizontal divider and no color difference between them. 

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/35429197/206422053-20b7a305-4920-490e-bb6b-17874d3bd10c.png">
 
### Proposal 

Increase visual difference by either changing the nav bar or the "editor nav bar". GitHub only uses color.

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/35429197/206422462-e1b51675-2620-495f-8c59-642bd6437e96.png">

We could use surface-100 for the nav bar. I played around with surface-100, a bit too light. The hue likely needs to increase in the color system to make a meaningful difference.

**Comment by jannesblobel** [comment]
@jannesblobel change the colour from surfaces 100-500 
https://m3.material.io/styles/color/the-color-system/color-roles
