### ISSUE TITLE
mobile nav bar color mismatch

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#181]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/35429197/207018917-c6587ddb-d219-413e-bf3b-3de97216bb8f.png">

related to #175

**Comment by jannesblobel** [comment]
Commit id: a7d628c512c05839b8c50366dbb06bab34b50fcf
I fixed the background colour. How can I Link to a commit?

**Comment by jannesblobel** [comment]
Ah, nice, Github is smart and did it on its own
