### ISSUE TITLE
nav bar tree view for documentation behaves differently dependent on the location of the click 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#189]
**Describe the bug**

**To Reproduce**
1. open the hamburger menu on mobile
2. click on "docs" (-> doesn't open the tree view)

**Expected behavior**
Open the tree view.

**Screenshots**

https://user-images.githubusercontent.com/35429197/207915755-146c2a72-c8ad-47e4-820d-05ed92e1600c.mov

**Comment by samuelstroschein** [comment]
https://user-images.githubusercontent.com/35429197/207916573-361f87fb-d16c-4885-995e-00d7d017637d.mov

The links in general behave incorrectly. Clicking on "editor" has no effect if the text is not pressed. 

Simple fix: wrap the links that are not a tree like "editor" in a link. Elements with a tree, like docs, have no link. 
Implication: Questionable UX. A user needs to click twice to get to docs, probably before even knowing what section in the docs they want to read.

**Comment by jannesblobel** [comment]
closed by #187

**Comment by jannesblobel** [comment]
closed by https://github.com/inlang/inlang/pull/187
