### ISSUE TITLE
auto-rebase when changes from main to inlang branch

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#220]
## Problem 

#219 introduced an automatic switch to a branch called "inlang". Changes from other branches are not auto-merged into this branch. This is fine as long as a user is aware of that fact. The current flow does not make the user aware of the fact that an inlang branch is created that could be outdated.  

## Proposal 

Signal to the user that a dedicated "inlang" branch has been created (if not exists) that could be outdated. 

### Ideas: 

- create a toast notification when the inlang branch has been created. 
- auto-merge changes from main into inlang on clone if possible?

**Comment by samuelstroschein** [comment]
I don't know whether the auto-merge, or rather [rabasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing), is a good UX flow because it is implicit. A solution could be a second toast that asks the user when the inlang branch is outdated if a rebase should be conducted. 

Flow if no inlang branch exists: 
- notify the user that inlang branch has been created. Explain why (refer to #186).

Flow if inlang branch exists but is outdated: 
- prompt the user (toast can be used as well) whether a rebase should be conducted.

**Comment by samuelstroschein** [comment]
The flow is unbearable. Auto rebase must happen if this flow stays in place. Changes to the inlang config are not reflected otherwise which makes testing extremely painful.

**Comment by jannesblobel** [comment]
Rebasing is not supported with isomorphic-git. 
We have to switch to libgit2 or another git tool.
