### ISSUE TITLE
mobile nav alignment to Header/inlang 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#232]
## Problem 
<img width="373" alt="Screenshot 2022-12-30 at 09 30 19" src="https://user-images.githubusercontent.com/72493222/210050348-7eb47ddd-51b1-4709-8350-dc87f4c1377b.png">
The navigation is not aligned to "inlang"

## use columns and <a/ > instead of  <sl-tree/ >
first col = logo
sec col= inlang and Nav
third col = Hamburger menu

**Comment by samuelstroschein** [comment]
needs complete overhaul in the future. let's not bother with small mistakes now
