### ISSUE TITLE
#docs rename "Design principles"

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#233]
## Problem 
What do you expect if you hear design principles?  
for My understanding, it is something like 
brand colour, 
rules for Designer... 
design guidelines

## Proposal 
renaming this title to get a better understanding of what it means: 
architecture, 
based on git, 
infrastructure

**Comment by samuelstroschein** [comment]
I see where you are coming from. The English language does not differentiate between "Konstruktionplan" (construction plan) and "Gestaltung" (design). Taken from Google: 

> design
> Design, Entwurf, Konstruktion, Ausführung, Muster, Zeichnung 

Design principles roughly translates to "Aufbauweise". Design refers to "the blueprint" of inlang, not "gestalterisches" design. I hope this explanation makes sense. I do see potential confusion. Renaming "design principles" to "infrastructure" as in #236 is wrong though. I can't come up with a better word. 

1. Better word? 
2. Is the issue so large that another word must be found? If not close this issue.

**Comment by samuelstroschein** [comment]
Architecture is also not a suited word. Developer-first is not an architecture, it is a principle :D

**Comment by jannesblobel** [comment]
Last idea:  
Principle
or 
Principle of inlang? 
if these words are not suitable close it.

**Comment by samuelstroschein** [comment]
Hmmm. I think that design principles is straight forward. Principles of inlang reads odd. Lets close this for now.
