### ISSUE TITLE
UX/UI on docs page 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#235]
## Problem 
There needs to be better UX in the docs. 
To get a better DX, the following UX problems should be fixed. 
 ## Proposal 

- [ ] Copy-Paste Button for code snippets
- [ ] Next and previous page buttons at the bottom of each document page 
- [ ] Docs page navigation must be `sticky` on the top-left side 
- [ ] change Bold Font, it looks gruesome <img width="833" alt="Screenshot 2022-12-30 at 12 22 23" src="https://user-images.githubusercontent.com/72493222/210065052-728f0e4c-f311-418b-95f8-346d3bf4a963.png">
- [ ] add/highlight code boxes for  text related to code instead of font-weight   <img width="919" alt="Screenshot 2022-12-30 at 12 26 08" src="https://user-images.githubusercontent.com/72493222/210065392-155613f9-45f8-45a8-8969-42946c5803cc.png"> 
- [ ] In general too much text on the docs page ( missing focus )
<img width="440" alt="Screenshot 2022-12-30 at 13 09 21" src="https://user-images.githubusercontent.com/72493222/210068836-57cff823-009a-495e-ad35-34a1239f12f8.png"><img width="440" alt="Screenshot 2022-12-30 at 13 20 20" src="https://user-images.githubusercontent.com/72493222/210069635-05b32c96-b3d3-4d33-9a37-9bfcb4cc6c72.png">

## Additional information 
Add new `short` tasks to improve the DX with a short description.

**Comment by samuelstroschein** [comment]
> change Bold Font, it looks gruesome 

The first sentence in a callout is bold on purpose to increase the UX. Reading the first sentence, visually elevated form the rest, is enough to decide whether the rest is of interest or not. While it might not look good, it seems to serve its purpose.

![image](https://user-images.githubusercontent.com/35429197/210082645-5f07d702-c5a4-432f-87ce-c360bd9bfbb9.png)


For the rest of the list, seems like a nice-to-have but not important. The biggest priority right now is to get people to use inlang (again).

**Comment by samuelstroschein** [comment]
Not prioritized
