### ISSUE TITLE
401 error during rendering

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#264]
## Problem

I tried to open a private repository I just published a few minutes ago in the `inlang` editor.
https://inlang.com/editor/github.com/ivanhofer/inlang-test-repo
Another private repository seems to work fine, but because I don't have an `inlang.config.js` file, I got an information message instead of the editor.

### Additional information (screenshots?)

![image](https://user-images.githubusercontent.com/21335119/211261140-12945f27-c298-4b13-a211-db07c39c5418.png)

![image](https://user-images.githubusercontent.com/21335119/211261232-69b01459-f571-427d-b322-4022f95161d6.png)

**Comment by ivanhofer** [comment]
A few minutes later it seemed to work, but now I get the same error again.

**Comment by ivanhofer** [comment]
It only seems to work if I enter the link to the repo [here](https://inlang.com/editor). Once I hit "reload", I get the error

**Comment by samuelstroschein** [comment]
I am working on the issue and will update this comment as I progress.

## 10:34 GMT

- [ ] catch 401 errors and display an "unauthorized" card. 
 
Assumption: Loading the link directly SSRs the site with a 401 (makes sense, the server has no access). The question is why the client does not take over after rendering. MIght be related to not catching the 401 error.
