### ISSUE TITLE
misleading message in UI when the `inlang` config could not be loaded

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#266]
## Problem

If I open the `editor` with an invalid `inlang.config.js` file I see the following error message:

![image](https://user-images.githubusercontent.com/21335119/211281629-ec2247bc-24c3-45e2-8c7e-6126dcb92d95.png)

The config file is present. The `editor` just can't load it (syntax-error, error while initializing the config, etc.). 

I don't get any information what caused the error, making it hard to debug.

## Steps to reproduce

1. write invalid JavaScript code inside the `inlang.config.js` file
2. open the repo in the `inlang` editor

### Expected behavior

Forwarding the error message to the UI would be great

**Comment by samuelstroschein** [comment]
@ivanhofer does the config file exist at the root of the repository or nested in a folder like `example/inlang.config.js`?

**Comment by ivanhofer** [comment]
the file is at the root

**Comment by samuelstroschein** [comment]
The problem seems to be related to https://github.com/inlang/inlang/issues/264#issuecomment-1375799486
