### ISSUE TITLE
catch and show error from plugins

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#267]
## Problem

Each crash in a plugin leads to a crash in inlang itself. 

### Expected behavior

Show that an error occurred in a plugin and do not crash the editor.

**Comment by jannesblobel** [comment]
I tried to improve the inlang.config, and my code crashed. No problem, but I wondered why the editor showed this message.
I wasted 10 min to understand the problem. 

<img width="635" alt="CleanShot 2023-01-30 at 13 21 17@2x" src="https://user-images.githubusercontent.com/72493222/215475467-db5a52e2-8e38-4b8f-845b-0303616d0604.png">

**Comment by NiklasBuchfink** [comment]
@samuelstroschein can this be closed with the current error handling?
