### ISSUE TITLE
$import does not work with base64 strings

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#268]
## Problem

(From @ivanhofer) The env function `$import` does not work with base64 encoding. 

## Steps to reproduce

```js
const content = `const en = {
  HI: 'Hi {name:string}!',
}

export default en
`

  const moduleWithMimeType = "data:application/javascript;base64," + Buffer.from(content).toString('base64');
  return (await $import(moduleWithMimeType)).default;

```

### Expected behavior

Work.

**Comment by samuelstroschein** [comment]
tom my awareness, has been fixed by ivan.

**Comment by ivanhofer** [comment]
Yes, this was fixed with https://github.com/inlang/inlang/commit/4a0ff110cd00674006c9a2b15ff928e2616c0652
