### ISSUE TITLE
"Push changes" badge shows incorrect amount of changes

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#270]
## Problem

When I edit a message inside the editor, the UI shows **2** changes instead of **1**

## Steps to reproduce

1. Open a repo in the editor
2. edit a single string
3. take a look at the "Push changes" button

### Expected behavior

I would expect that `1` gets shown instead of `2`

### Additional information (screenshots?)

![image](https://user-images.githubusercontent.com/21335119/211343526-652d98e2-24ee-41ae-892b-8a6367be7999.png)

**Comment by ivanhofer** [comment]
It seems the badge is correct.
The issue is related to #269. The text inside the editor does not match the text on disk.

So the actual issue is:
Hitting "commit" on "en", will also save the contents of "de"
![image](https://user-images.githubusercontent.com/21335119/211344883-016a8532-c06a-4eb9-9020-aecaef257678.png)
 
 Not sure if this is intended

**Comment by samuelstroschein** [comment]
The current implementation naively serializes the entire AST (all resources) upon changing something. Thus, the first commit might trigger a "round-trip" of parsing and serializing all resources. Not ideal indeed but seems to work regardless. I committed a change that commits only one commit on a round trip https://github.com/inlang/inlang/commit/cbac68b62a291eef85198b31a66326ed2c23bc37
