### ISSUE TITLE
editor makes empty commits

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#277]
## Problem

The editor currently produces empty commits.
https://github.com/ivanhofer/inlang-test-repo/commit/d85703668d641163cd9c0616d92293bc2f079088

## Steps to reproduce

1.change something in the editor
2. commit and push changes

### Expected behavior

Changes should be applied correctly
If no changes are detected (empty commit), don't push at all.

**Comment by samuelstroschein** [comment]
Added to #271 which  I will hopefully be able to complete this week
