### ISSUE TITLE
show a loading spinner or similar to display activity

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#283]
## Problem

Cloning repositories can take a minute. There is no indicator to the user during that minute that the app did not crash because "loading ..." is static. 

## Proposal

Show a loading spinner or similar. Maybe with a text that "cloning repositories can take a a few minutes".

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/c48dc9d5-25bd-4c76-b09e-40d1fc55ff05.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/51c7f8b6-65c9-4fbe-bbcb-0f37e967264f.png)

**Website URL:**
[https://inlang.com/editor/github.com/osmosis-labs/osmosis-frontend](https://inlang.com/editor/github.com/osmosis-labs/osmosis-frontend)

**Device and browser info:**
Chrome 108.0.0.0 (1440x796) | Mac OS 10.15.7

**Date and time:**
January 17th 2023 | 1:09pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/de34cf7e-4a5a-4d44-ab97-795e176c0536](https://jam.dev/c/de34cf7e-4a5a-4d44-ab97-795e176c0536)

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by jannesblobel** [comment]
![CleanShot 2023-01-20 at 15 06 51](https://user-images.githubusercontent.com/72493222/213716654-53d8cdf0-1325-443d-a78a-3e8ed574857d.gif)
