### ISSUE TITLE
languages are unaligned when the button bar is opened

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#284]
## Proposal 

Center align the language on the left based on the input field on the right. 

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/98102026-80ba-4f53-ad4a-e10b1e6863ec.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/8917959d-a975-4eae-b9be-e0eed5c03cea.png)

**Website URL:**
[https://inlang.com/editor/github.com/inlang/example](https://inlang.com/editor/github.com/inlang/example)

**Device and browser info:**
Chrome 108.0.0.0 (1440x796) | Mac OS 10.15.7

**Date and time:**
January 17th 2023 | 7:32pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/df898d42-9b57-4bea-b2fc-1d86c2da05ac](https://jam.dev/c/df898d42-9b57-4bea-b2fc-1d86c2da05ac)

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by jannesblobel** [comment]
closed with PR
