### ISSUE TITLE
SSR missing owner and the name of the repo 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#295]
At localhost i missed the owner and the repository name. 

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/e5145650-a4d4-4279-9b99-caf3989bcedc.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/2a09f229-7f6c-4b29-bc1e-c12abc3fab98.png)

**Website URL:**
[http://localhost:3000/editor/github.com/inlang/example](http://localhost:3000/editor/github.com/inlang/example)

**Device and browser info:**
Chrome 109.0.0.0 (1816x1192) | Mac OS 10.15.7

**Date and time:**
January 20th 2023 | 6:57pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/9adacae0-4201-4049-b1e4-e94763ea5989](https://jam.dev/c/9adacae0-4201-4049-b1e4-e94763ea5989)

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by samuelstroschein** [comment]
I ran into that bug too, can't reproduce. Seems to be a hydration issue from SSR to client-side given the logs.
