### ISSUE TITLE
mention somewhere that `moduleResolution="node16"` is required to get type-checks for `defineConfig`

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#298]
## Problem
![image](https://user-images.githubusercontent.com/21335119/213906680-18c701f2-63be-4edd-89cb-606136b9f0a3.png)

with this `tsconfig.json`

![image](https://user-images.githubusercontent.com/21335119/213906688-8b4d74ef-6d0a-4c5f-b2ac-8d45b7c4512b.png)

Once I add `"moduleResolution": "node16"` to my `tsconfig.json`, the errors are gone and I get proper type checks.

![image](https://user-images.githubusercontent.com/21335119/213906711-cf555684-4445-4232-90d2-d1f24fc58b68.png)

## Proposal

Mention this somewhere in the docs.

## Additional information

Could be a problem for older projects because they probably can't update the whole codebase to that option.

Maybe the approach that `vite` uses is the better option
```ts
import { defineConfig } from 'vite'

export default defineConfig({
  // ...
})
```

**Comment by samuelstroschein** [comment]
Decided with @jannesblobel to switch back to the single-column view to avoid issues like this. A fix will come soon.

**Comment by samuelstroschein** [comment]
> Could be a problem for older projects because they probably can't update the whole codebase to that option.

I'll see if I can setup the core package to export types with `node16` module resolution. 

> Maybe the approach that vite uses is the better option

Static imports and dynamic imports without the `env.$import` function are not supported, making vites approach unfeasible :( If #129 is implemented, the DX of importing packages should be vastly improved.

**Comment by samuelstroschein** [comment]
I couldn't find a solution. I mention in the docs that `moduleResolution` must be set to `node16`. 

> Could be a problem for older projects because they probably can't update the whole codebase to that option.

Indeed. I don't see a solution. Inlang's running a JS config in the browser is enabled by ES Modules. Loosening the moduleResolution of inlang's code base and thereby the inlang ecosystem could lead to unforeseen, and potentially much larger issues.
