### ISSUE TITLE
improve(editor): make nav bar sticky

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#308]
How many unpushed changes are in the queue? 
Problem: 
The user can see the unpushed changes only at the top of the page. It could be possible that the user closed the page without pushing
Proposal: 
Display the unpushed changes every time/ on the whole website.

Watch the screen recording here: https://jam.dev/c/4aca0579-55f4-4b6d-a7f1-73f996e30133

\-------------------------------------

**Website URL:**
[https://inlang.com/editor/github.com/jannesblobel/Prusa-Firmware](https://inlang.com/editor/github.com/jannesblobel/Prusa-Firmware)

**Device and browser info:**
Chrome 109.0.0.0 (1440x764) | Mac OS 10.15.7

**Date and time:**
January 24th 2023 | 3:23pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/4aca0579-55f4-4b6d-a7f1-73f996e30133](https://jam.dev/c/4aca0579-55f4-4b6d-a7f1-73f996e30133)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by samuelstroschein** [comment]
> Display the unpushed changes every time/ on the whole website.

Making the "navbar" sticky would be a fix right?

**Comment by NiklasBuchfink** [comment]
This should be solved already with the new sticky listheader https://github.com/inlang/inlang/pull/499
