### ISSUE TITLE
validate config 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#309]
## Problem

1. Programatically testing the config is not possible e.g. "Does the `readResources` function work?", "Are my lints correct?". 
2. Plugin authors are starting to "hack" the inlang config. That's great. But will lead to unintended consequences and breaking changes in the future.

## Proposal

Provide a module (`inlang/core/test` ?) that can validate the config schema and functionality.  That module can be used by, for example, the CLI that provides an `inlang config validate` command and the editor that checks the config on the fly. 

- [ ] Validate the config schema with something like `zod`.
- [ ] "Test run" functions that are defined in the config
- [ ] Provide a CLI command like `inlang config validate` to test the config file programmatically
- [ ] Use regex to ban code in the config file that won't run in the browser like `import`, node globals, etc.

## Additional information

Using zod for the validation seems to make sense.

**Comment by leolurch** [comment]
Would it make sense, to only allow importing plugins from one central authority like a inlang repo? This way you could make sure that plugin authors don't (intentionally or unintentionally) abuse their ability to run code on inlang editor clients.

**Comment by samuelstroschein** [comment]
@leolurch

> Would it make sense, to only allow importing plugins from one central authority like a inlang repo?  

Would add too much overhead for us + the community. What we should do is to provide `@inlang/core/test` that plugin authors can use to test their plugins. 

> This way you could make sure that plugin authors don't (intentionally or unintentionally) abuse their ability to run code on inlang editor clients. 

Seems unlikely. We can't validate code for malicious intent. A plugin could use a malicious npm package which would even be out of the scope of the plugin itself. The right way to deal with security is sandboxing JS.

**Comment by samuelstroschein** [comment]
@leolurch it could make sense to consolidate community plugins in a dedicated repo like solidjs does it see https://github.com/solidjs-community
