### ISSUE TITLE
Detailed dev setup guide

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#312]
- [ ]  Document all necessary env vars in Readme
- [ ]  Explanation + Link for creation of the github oauth app
- [ ]  How to create a JWE Secret Key?

**Comment by samuelstroschein** [comment]
@leolurch What is missing in the contributing section https://inlang.com/documentation/contributing? 

And did https://gitpod.io/#https://github.com/inlang/inlang.git work in/for your fork? Theoretically, gitpod sets up the entire dev setup.

**Comment by leolurch** [comment]
Didn't know that gitpod takes care of the setup that. That probably explains my poor setup experience.

**Comment by leolurch** [comment]
@samuelstroschein seems like the env variables aren't initialized correctly in gitpod. After the initialization done by gitpod I ran `npm run dev` in `/source-code`, but it failed with: `Error: Missing env variable VITE_CORS_PROXY_URL`. Seems like the env var setup done by doppler isn't working correctly. But I'm not that deep into gitpod.

My test repo url: https://github.com/leolurch/inlang-supertokens-session

**Comment by samuelstroschein** [comment]
@leolurch I see. Damn it. Need to find another solution then. The appeal of Gitpod was the elimination of a dev setup.

**Comment by samuelstroschein** [comment]
I asked doppler what they recommend https://community.doppler.com/t/public-env-files-to-streamline-open-source-contributions/949

**Comment by samuelstroschein** [comment]
the simplest solution might be to directly commit the development env file that would be exposed via service like doppler and just be done with this.

**Comment by samuelstroschein** [comment]
Closed by #363

**Comment by motdotla** [comment]
hi @samuelstroschein would the new `.env.vault` file mechanism be useful for you here?

https://www.dotenv.org/blog/2023/10/24/what-is-env-vault-file.html

It's the spiritual successor to .env files. Essentially, it encrypts a copy of your .env file into the codebase. Then you use a single `DOTENV_KEY` to decrypt those and inject them just-in-time.

Various guide examples here: https://dotenv.org/docs

**Comment by samuelstroschein** [comment]
Hi @motdotla, 

I am unsure. My goal is to have a "community" env file that is readily available without a complicated setup. 

Let's hop on a call where I explain my use case. If dotenv supports it, willingness to switch is high because we have an issue with our current Doppler setup that prevents us from using NX cloud caching. 

https://cal.com/samuelstroschein/15-min
