### ISSUE TITLE
synchronize forks

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#326]
## Problem

Forks are not synchronized.

## Steps to reproduce

1. Open a repository that has been forked some time ago with changes that break inlang.

### Expected behavior

The fork is synched.

### Additional information (screenshots?)

An easy implementation could be to ask the user to manually sync the repo via GitHub's UI.

**Comment by samuelstroschein** [comment]
https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#sync-a-fork-branch-with-the-upstream-repository

**Comment by leolurch** [comment]
(How) should we deal with potential merge conflicts?

**Comment by samuelstroschein** [comment]
We can't :( If there are merge conflicts, we likely have to point the user to "please go on github to re-sync your fork". I assume that the minority will run into merge conflicts

**Comment by samuelstroschein** [comment]
The next git should probably have a strong design focus on minimizing the possibility of merge conflicts

**Comment by leolurch** [comment]
Guess that's true ✓

**Comment by leolurch** [comment]
Found that there is already a telefunc function for syncing a fork, which calls the REST API endpoint you referenced, in this file: https://github.com/inlang/inlang/blob/main/source-code/website/src/services/github/fork.telefunc.ts

Didn't look any deeper into the topic. Would calling that function, before a PR in the original repo is created, resolve the issue?

**Comment by samuelstroschein** [comment]
> Didn't look any deeper into the topic. Would calling that function, before a PR in the original repo is created, resolve the issue? 

The repo has to be merged/synced with upstream on cloning the repo. Otherwise, the user would edit outdated messages. There is no periodic pull implemented yet, see https://github.com/inlang/inlang/issues/252

**Comment by leolurch** [comment]
I get it. Should solving this issue include implementing periodic pulling?

**Comment by samuelstroschein** [comment]
Probably not. #252 pollutes the git commit history. anyhow, swing by my place. the first people arrived. see you in a bit

**Comment by leolurch** [comment]
Was my first party with an open github repo on a screen and it was lit ^^

**Comment by samuelstroschein** [comment]
That was by coincidence. But I'll keep my PC open at following parties too. Was quite cool to see people showcasing their products :D
