### ISSUE TITLE
only select reference language on startup

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#327]
## Problem

Rendering all languages upon starting the editor can be extremely slow and overwhelming. 

<img width="1288" alt="CleanShot 2023-01-29 at 20 13 49@2x" src="https://user-images.githubusercontent.com/35429197/215350316-303ed949-1953-4ce7-a967-e17a4d4b0c65.png">

## Proposal

1. Only render the reference language on startup. 
2. Show a language selection in the first rendered message IF only the reference language is selected. 

The startup time should significantly improve and users are not overwhelmed with language that they are not interested in/going to translate.

![IMG_6427](https://user-images.githubusercontent.com/35429197/215350591-a1a24bab-b752-404e-8b1e-d5caf0ea9a04.JPG)

**Comment by jannesblobel** [comment]
A Dialog is more efficient, in my opinion. It might confuse the user to select a language in the first message. 
But I agree, On default: Inlang renders only the reference language 
![CleanShot 2023-01-29 at 20 23 30@2x](https://user-images.githubusercontent.com/72493222/215350936-f847463e-72c3-48e5-a27f-afe3bb04138e.png)

**Comment by samuelstroschein** [comment]
@jannesblobel I disagree with the dialog approach. A dialog interrupts the user to ask for an action. The user should not be interrupted by opening a site. Instead, the user should be "invited" to explore the site. 

Displaying and being able to select possible languages is inviting. Feel free to give counter arguments

**Comment by jannesblobel** [comment]
In this example, there are about 50 languages. 
You cannot display them all. 
We have to implement the function "Add language". When this is implemented, it is easy to create a new language if the language you are looking for is not in the project. 

I will do some research and keep you informed. 

<img width="549" alt="CleanShot 2023-01-29 at 20 45 04@2x" src="https://user-images.githubusercontent.com/72493222/215351896-c4cd644b-cced-4fc2-bbdd-24302f607cf0.png">

**Comment by samuelstroschein** [comment]
My take. Not all languages are shown but can be expanded if desired. 

https://shoelace.style/components/select can be used. 
https://beta.tldraw.com/r/v2_c_62KQMNutgBgQZz2r0aGv3 edit the drawing here

<img width="1076" alt="CleanShot 2023-01-29 at 21 10 03@2x" src="https://user-images.githubusercontent.com/35429197/215353166-9362c13b-8141-4aa4-9983-c5229e082b36.png">

**Comment by samuelstroschein** [comment]
the performance issues should be mitigated by #333. the UX issue remains

**Comment by samuelstroschein** [comment]
Alternative proposal of using a dedicated card at the top of the editor. 

- clear distinction between language filters and messages by separating the cards
- the https://zagjs.com/components/react/tags-input component can be used

<img width="483" alt="CleanShot 2023-01-31 at 14 55 43@2x" src="https://user-images.githubusercontent.com/35429197/215779607-8d11d478-517a-4385-9046-68e5dea293f0.png">

**Comment by samuelstroschein** [comment]
implemented by nils and niklas
