### ISSUE TITLE
changes are not detected in large repositories

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#329]
## Problem

Changes are not being detected.

## Steps to reproduce

1. Go to https://inlang.com/editor/github.com/samuelstroschein/umami
2. Create commits
3. The "push changes" button stays disabled

### Expected behavior

Pushing changes is possible

**Comment by samuelstroschein** [comment]
The bug is caused by a performance bottleneck. 

Committing a change triggers endless filesystem calls: 

1. `writeResources()` all of them ...
2. `readResources()` all of them ... (yeah haha naive implementation)
3. `hasUnpushedChanges()` 

Committing multiple changes in a fast pace -> booom 💥 

https://user-images.githubusercontent.com/35429197/215354033-a0c4d7ea-59a4-4d9d-a405-dd925c9c332f.MOV

PS enjoy the music

**Comment by samuelstroschein** [comment]
Can't even push changes. Probably needs #278

**Comment by samuelstroschein** [comment]
Changes are detected but the implementation is naive and writes and reads all resources on a single change which the git implementation must traverse to detect changes. 

Related: #345. CC @araknast another git performance issue

**Comment by jannesblobel** [comment]
@samuelstroschein  Is this Bug still existing or can we close this issue?  Last Update 1 1/2 Month ago

**Comment by samuelstroschein** [comment]
Closing for now because #1142 should improve things.
