### ISSUE TITLE
the reference language should be the first language in a message 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#330]
## Problem
The reference language is somewhere. Sometimes in the middle of a message, sometimes at the end. 

## Suggestion
 The alphabetical order of all languages in a project/repository and the ref. language at the beginning of a message/ filter option 

## Additional information

![CleanShot 2023-01-29 at 21 15 17@2x](https://user-images.githubusercontent.com/72493222/215353461-bcd7066f-6fb8-4bcc-971f-bf35ddb23852.png)

**Comment by NiklasBuchfink** [comment]
Done in https://github.com/inlang/inlang/pull/508/commits/003ac096027db0a4ff58ada6738d77c9e2396bea
