### ISSUE TITLE
Machine translation is not working on .po files 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#334]
## Problem
Machine translation does not work for .po files. 
Conjecture: 
The reference language file (pot) has no 'msgstr' messages. 
I assume that the machine translation function tried to take this as a reference message, but the string is empty/unavailable. 

## Steps to reproduce

1. Open a Project whit a pot file as a reference 
2. delete a translated message. commit this message (only for testing ) 
3. try to translate this message via machine translation 

The second video supports this thesis 
### Additional information (screenshots?)

https://user-images.githubusercontent.com/72493222/215558217-4b76331e-f8ed-4f6d-a243-2cfa08bc86a7.mp4

https://user-images.githubusercontent.com/72493222/215561582-64b2c2f7-f1fd-4958-8098-39eaecb7da98.mp4

**Comment by samuelstroschein** [comment]
I can confirm that the machine translation function takes the reference message.

**Comment by samuelstroschein** [comment]
moved the issue to https://github.com/jannesblobel/inlang-plugin-po/issues/3. 

the issue is unrelated to inlang except for #309. the bug is a bug in the po plugin
