### ISSUE TITLE
Translation boxes empty for Osmosis frontend

### ISSUE THREAD

**Issue by jonator** [inlang/inlang#339]
## Problem
No translations in the boxes for our frontend.

## Steps to reproduce

Visit: https://inlang.com/editor/github.com/osmosis-labs/osmosis-frontend

**Comment by samuelstroschein** [comment]
Hi Jon, 

The inlang config on the master branch is outdated. You merged my PR https://github.com/osmosis-labs/osmosis-frontend/pull/1243 into staging. Inlang opens the master branch by default until branches are supported https://github.com/inlang/inlang/discussions/166. 

Are you going to merge staging in master soon, or should I open a new PR?

**Comment by jonator** [comment]
Ah yes we will merge soon. Thanks.

**Comment by samuelstroschein** [comment]
We could prevent such confusion with #309
