### ISSUE TITLE
performance optimization: only parse and serialize resources that have been changed

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#345]
## Problem 

Every commit leads to the serialization and subsequent parsing of every, even unchanged resource. 

## Proposal 

1. Only serialize and parse resources that changed. 
2. Don't parse resources if the change occurred due to a serialization from the editor (careful to not disable parsing for external changes)

## Would close the following issues

- [x] #329

**Comment by jannesblobel** [comment]
@samuelstroschein Is this Bug still existing or can we close this issue? Last Update 1 1/2 Month ago

**Comment by samuelstroschein** [comment]
Closing because #1142 will improve things
