### ISSUE TITLE
enable extension on existing inlang.config.js

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#348]
## Problem
VSCode extension only works for `Javascript`, `Javascript React`, `Typescript`, `Typescript React` and `svelte` projects. This conflicts with the idea of inlang to help with i18n independently from the used technology.

## Proposal

- [x] Change the activation event to detect `inlang.config.js` instead of languages. This can be done with:
https://code.visualstudio.com/api/references/activation-events#workspaceContains
- [x] Reinitialize upon `inlang.config.js` changes with https://code.visualstudio.com/api/references/vscode-api#workspace.createFileSystemWatcher

## Additional information
![image](https://user-images.githubusercontent.com/1105080/216575592-056fb7fa-91ff-4de3-b69a-491debd1cabc.png)

https://code.visualstudio.com/api/references/activation-events

**Comment by samuelstroschein** [comment]
Agree. Inlang should function independently from the technology. 

I created a draft config schema for the extension a while back https://github.com/inlang/inlang/blob/main/source-code/core/src/config/schema.ts#L79. I used `documentSelectors`: [DocumentSelectors](https://code.visualstudio.com/api/references/document-selector) from VSCode to signal when the extension should start. 

I thought that activation events would be "overkill". Just run the extension on javascript files for example. But, plugins will mostly define the config. Sticking with VSCode's API itself seems advisable. 

VSCode would be a technology lock-in, given VSCode's adoption, that seems to be okay. Supporting other code editors via API mapping should be doable in the future. 

## Proposal 

- add activation events under `config.ideExtension.activationEvents`.
In the future, activation events could be moved out of the ide extension nesting, if the config is used elsewhere. 

- stick to VSCode's API (including return types?) 

@openscript sounds good?

**Comment by openscript** [comment]
Sounds good to me. I can tackle this after #132 and #133.

**Comment by samuelstroschein** [comment]
@openscript Great

**Comment by openscript** [comment]
This will be useful: https://code.visualstudio.com/api/references/vscode-api#workspace.createFileSystemWatcher

**Comment by openscript** [comment]
@samuelstroschein
Estimate 1h

**Comment by samuelstroschein** [comment]
Go ahead! :)

**Comment by felixhaeberle** [comment]
this is fixed by 4eaa8b59ca9c06eb5bc2087adb0dd4d3a6915fa3 🎉
