### ISSUE TITLE
invalid link 

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#352]
1. Open a new feature request issue https://github.com/inlang/inlang/issues/new?assignees=&labels=&template=feature_request.md&title=
2. Try to open the discussion link mentioned in the description: https://github.com/inlang/inlang/discussions/categories/feature-requests
3. See that "feature request" is missing as a category

**Comment by samuelstroschein** [comment]
We could embed https://github.com/lycheeverse/lychee into CI/CD to be alerted of broken links throughout the entire repo including documentation, rfcs, source code, etc
