### ISSUE TITLE
migrate extension to esm

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#368]
## Problem
Currently Rollup is used to transpile Inlang from ESM to the CommonJS format as VSCode doesn't support ESM to be used in extensions.

## Proposal
Sooner or later they will have to support ESM. When this happens, we should migrate as it causes some technical dept.

## Additional information
see https://github.com/microsoft/vscode/issues/130367

**Comment by samuelstroschein** [comment]
Future problem, doesn't need immediate action. Closing this to clean up the issues.
