### ISSUE TITLE
internationalize extension with inlang

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#371]
## Problem

The VSCode extension is not internationalized.

## Proposal

Internationalize VSCode extension with inlang.

**Comment by samuelstroschein** [comment]
Good idea. Monorepo support is likely required, see https://github.com/inlang/inlang/discussions/258. 

Generally, I'd like to localize inlang (editor && website) ASAP with inlang. The blocking factor are document/markdown and the mentioned monorepo support.

**Comment by openscript** [comment]
Is i18n for monorepos a USP?

**Comment by samuelstroschein** [comment]
Nope, no priority right now. 

The alternative is to create one inlang.config.js file that reads messages from multiple modules. In our case the ide-extension and website. Namespace support would be useful but can be "hacked" by prefixing messages with `ide-extension.message1234` and `website.message2233`.

**Comment by openscript** [comment]
Here is an example:
https://github.com/microsoft/vscode-extension-samples/tree/main/l10n-sample

**Comment by samuelstroschein** [comment]
Not so important. Closing for now to minimize open issues
