### ISSUE TITLE
exclude files from matchers

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#382]
In my opinion it should be possible to configure a list of files which are included or excluded. So in the `inlang.config.js` there is something like:

```js
{
   // ....
   ideExtension: {
     excludeFromMatchers: ['inlang.config.js', 'node_modules/**/*']
   }
   // ...
}
```

_Originally posted by @openscript in https://github.com/inlang/inlang/issues/376#issuecomment-1436869303_

**Comment by openscript** [comment]
Estimate 3h

**Comment by openscript** [comment]
@samuelstroschein 
Estimate 3h

**Comment by samuelstroschein** [comment]
@openscript I am thinking about whether we should prioritize that feature now and whether this is a "ide extension" or core feature. 

The ide extension doesn't really need exclusion matches (correct me if i am wrong). The ide extension only runs on opening a specific file. While yes, running on the `inlang.config.js` file is annoying (https://github.com/inlang/inlang/pull/376#pullrequestreview-1305627762), I don't know whether the issue exists with other files.

**Comment by openscript** [comment]
> @openscript I am thinking about whether we should prioritize that feature now and whether this is a "ide extension" or core feature.
> 
> The ide extension doesn't really need exclusion matches (correct me if i am wrong). The ide extension only runs on opening a specific file. While yes, running on the `inlang.config.js` file is annoying ([#376 (review)](https://github.com/inlang/inlang/pull/376#pullrequestreview-1305627762)), I don't know whether the issue exists with other files.

Probably the core needs a similar feature at some point. For example if you want to find references with missing translations you don't want to scan the whole `node_modules`. `inlang.config.js` can always be excluded.

Or can we ignore are files which are also ignored by `.gitignore`?

**Comment by samuelstroschein** [comment]
> Or can we ignore are files which are also ignored by .gitignore plus inlang.config.js which can always be excluded? 

Let's wait for feedback from users if file exclusion is required and how to implement file exclusion. 

For now, just ignore the inlang.config.js?
