### ISSUE TITLE
reload resources upon change and propagate

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#383]
## Problem

Currently the resources are loaded, when a new editor becomes active. If changes happen to the resources from the active editor, the inlang extension doesn't react (for example redecorate).

 - [ ] Add file path to `Resource` so we can find out which files read by `readResources`
 - [ ] Create file watches for all loaded resources https://code.visualstudio.com/api/references/vscode-api#workspace.createFileSystemWatcher
 - [ ] Propagate changes resources to decorators

**Comment by openscript** [comment]
@samuelstroschein 
Estimate 2h

**Comment by samuelstroschein** [comment]
Go ahead! :)

**Comment by felixhaeberle** [comment]
this is fixed by 7fc4f4f5ebd0baf1bb5e68b31f4b083f4d2502d1 ✨
