### ISSUE TITLE
gain in developers visibility and trust

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#385]
- [x] Verify Inlang organization https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization
- [x] Update logo, description and link of Visual Studio Code Marketplace publisher profile https://marketplace.visualstudio.com/publishers/inlang
- [x] Verify Visual Studio Code Marketplace publisher profile https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher
- [x] Register at alternative Visual Studio Code Marketplace https://open-vsx.org/

**Comment by samuelstroschein** [comment]
Claiming the namespace on open vsx is in progress https://github.com/EclipseFdn/open-vsx.org/issues/1632. The rest of the tasks are complete. Thus, I close this issue.
