### ISSUE TITLE
ide extension changes the working directory and thereby (potentially) breaks other extension

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#386]
## Problem

See https://github.com/inlang/inlang/pull/376#issuecomment-1438809792

## Proposal

Don't change node's working directory. 

## Additional information

Blocked until https://github.com/orgs/inlang/discussions/373 is implemented.

**Comment by samuelstroschein** [comment]
@openscript fixed in #392? If so, please close this issue

**Comment by openscript** [comment]
Yep, this nasty line is gone.
