### ISSUE TITLE
abstract minimal filesystem types

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#391]
_Originally posted by @openscript in https://github.com/inlang/inlang/discussions/373_

The core should describe a minimal filesystem as types, which is used through out the project. The interface should intersect with `memfs` and `node:fs`. The following **async** methods are required:
 - `readFile`
 - `writeFile`
 - `readdir`

- [x] Define types for `readFile`, `writeFile` and `readdir` inside `core/fs`.
- [x] Use fs abstraction for `environment-functions`
 - [x] Add a new documentation page `reference/fs`.
 - [ ] Fixes #154

**Comment by openscript** [comment]
Estimate 2h

**Comment by samuelstroschein** [comment]
Go ahead! :)

**Comment by openscript** [comment]
This also fixes #154
