### ISSUE TITLE
use filesystem abstraction in ide-extension

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#392]
_Originally posted by @openscript in https://github.com/inlang/inlang/discussions/373_

Use #391 inside the ide-extension.

- [x] Add a mapper between `vscode.workspace.fs` and inlang filesystem abstraction
- [x] Use `vscode.workspace.fs` and the mapper for `initialize$import`.
- [x] #386

**Comment by openscript** [comment]
@samuelstroschein:
Estimate 3h

**Comment by samuelstroschein** [comment]
Go ahead! :)

**Comment by openscript** [comment]
Only used 2h of estimated 3h
