### ISSUE TITLE
## Problem

### ISSUE THREAD

**Issue by Juaanita** [inlang/inlang#396]
## Problem

Building (sophisticated) i18n for metaframeworks is a month/year-long effort. 

For example, SvelteKit's most upvoted issues are about i18n and have been open for years https://github.com/sveltejs/kit/issues/553, https://github.com/sveltejs/kit/issues/1274. I18n in the context of metaframeworks is especially problematic because routing, SSR, SEO, "code splitting", and more needs to be considered. 

- no metaframework has a "one click/simple" i18n solution, sometimes even lacking i18n support entirely
- every metaframework builds its own solution, leading to duplicate efforts

## Proposal

Provide a framework-agnostic i18n library for metaframeworks with the possibility for deep integration via adapters. 

We have multiple components in `@inlang/core` to provide an i18n library already. We can invest resources to relieve metaframework authors from months/years of work to build i18n features for their frameworks. By providing such a library, we simultaneously come closer to our goal to make i18n easy. 

- relieving metaframework authors from months/years of work
- make every framework better regarding i18n
- the rest of inlang's dev tools like the ide extension work out of the box, leading to a DX beyond of what a i18n library could provide

_Originally posted by @samuelstroschein in https://github.com/inlang/inlang/discussions/395_

**Comment by samuelstroschein** [comment]
This issue seems to be opened by mistake. Closing it, let me know if I should re-open it.
