### ISSUE TITLE
ci/cd tests are running for over 15 min

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#401]
## Problem

https://github.com/inlang/inlang/actions/runs/4276274134/jobs/7444247148

### Expected behavior

Tests should complete in a few seconds

**Comment by samuelstroschein** [comment]
@openscript an idea what the issue is?

**Comment by openscript** [comment]
Yes, I think there is an issue with my changes with the FS.

**Comment by openscript** [comment]
Well it is somehow related to my recent changes. I'll investigate.

**Comment by openscript** [comment]
Well this tests, which time out, have external dependencies. I'm in the train right now and my internet is not so stable, the test failed and then suddenly they start to work. I reran the tests on Github and they worked well. I suspect that sometimes the external dependencies cannot be loaded before the test timing out.

**Comment by samuelstroschein** [comment]
Odd. I guess this can be closed then.
