### ISSUE TITLE
set up continuous integration and delivery for ide-extension

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#421]
Checking the `ide-extension` and releasing it should be automated.

- [x] Include `ide-extension` tests when running `npm test` on the monorepo
- [x] Publish to VSCode Marketplace
- [ ] Publish to https://open-vsx.org/ (OVSX seems to be unstable; we skip it for now)

Probably secrets for the VSCode Marketplace and https://open-vsx.org/ need to be set by @samuelstroschein.

**Comment by openscript** [comment]
@samuelstroschein 
Estimate 1h

**Comment by samuelstroschein** [comment]
@openscript Go ahead! :) Tell me where I need to set the secrets

**Comment by openscript** [comment]
@samuelstroschein We need the following secrets:

`VSCE_TOKEN`: VSCode marketplace secret
`OVSX_TOKEN`: https://open-vsx.org/ secret

**Comment by samuelstroschein** [comment]
- Created the VSCode marketplace secret. 
- Open VSX is down right now. 

<img width="1141" alt="CleanShot 2023-03-14 at 21 10 25@2x" src="https://user-images.githubusercontent.com/35429197/225124908-9fd2cb13-c20a-4b51-973f-54922eeecda5.png">

**Comment by openscript** [comment]
It's up again. I saw this: https://blogs.eclipse.org/post/john-kellerman/help-us-sustain-open-vsxorg

**Comment by samuelstroschein** [comment]
@openscript it's down (again). 502 gateway error. just set it up without open VSX

**Comment by openscript** [comment]
@samuelstroschein I've adjusted the pr accordingly: https://github.com/inlang/inlang/pull/446/commits/663d19eaa170917aa92e4fdccf4cbc364098717d
