### ISSUE TITLE
add solid devtools to website to increase debugging DX

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#428]
## Problem

Tracking the state in the editor is hard. 

## Proposal

Add https://github.com/thetarnav/solid-devtools to @inlang/website.

**Comment by samuelstroschein** [comment]
@inlang/contributor up for grab. @nikitavoloboev if you do it, please assign yourself

**Comment by boian-ivanov** [comment]
At this moment this doesn't seem possible while using `vite-plugin-ssr`, since we're getting the following, upon adding `solid-devtools/vite`
```
Error: [vite-plugin-ssr@0.4.70][Wrong Usage] You are using a Vite Plugin that transforms the HTML in a way that conflicts with vite-plugin-ssr. 
```

**Comment by samuelstroschein** [comment]
The VPS maintainer is aware https://github.com/brillout/vite-plugin-ssr/issues/607#issuecomment-1496366088

**Comment by felixhaeberle** [comment]
I commented on the relevant issue:
https://github.com/thetarnav/solid-devtools/issues/233

**Comment by felixhaeberle** [comment]
@samuelstroschein gave the author of the devtools an example he can test with. it's on his roadmap a top priority for the next release as I have seen. Maybe this will soon land 🥳

**Comment by samuelstroschein** [comment]
Closing as "no priority/stale".
