### ISSUE TITLE
create a standardized `build` utility function for plugins

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#430]
## Problem

Plugin autors should be able to just focus on the code and not on how to configure the build setup to release a bundle that is compatible with inlang.

Most things can be solved already by offering a great [`template`](https://github.com/inlang/plugin-template) repository. As time moves on, bugs or missing features may be found, leaving early adopters with an outdated build process.

Plugin autors may also accidentially remove or change settings that need to be there.

Things that should always be present:
 - `.d.ts` type definitions
 - `esm` as output format
 - ´es2020` as target
 - `'neutral'` as platform
 - the `@esbuild-plugins/node-modules-polyfill` polyfills

## Solution

Create a new `build` utility exported from `@inlang/core/utilities`.
It accepts an array of `entryPoints` and an optional array of `plugins`.
Once called it uses `tsup` to generate a production bundle with some predefined rules.

If we find a bug or want to change the way how we bundle things in the future, we can do that in a central place. Once plugin authors update the `@inlang/core` dependency, they automatically benfit from it and don't need to spend time configuring build tools.

The `build` function will be the recommended way. If some autors wish, they can always build their own build script.

**Comment by samuelstroschein** [comment]
Additional information: The output should always be one bundled JavaScript file. 

Most environments don't support import maps yet. We can implement code splitting when import maps are widely supported.  

For esbuild, the config must have only one input and bundle must be true

```ts
    entry: ["src/index.ts"],
    bundle: true 
```
