### ISSUE TITLE
Watcher for website development does not run on Windows

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#439]
## Problem
Try to develop on Windows in a Docker container, but file changes in the website development are not detected by the watcher and the website is not updated.

## Steps to reproduce
1. Open the repository in VSCode.
2. Open the repository in a dev container via CMD + Shift + P and search for Open in container. Make sure to allocate enough memory in your Docker setup (4GB).
3. `npm install` to install dependencies
4. `npm run dev` to run the development environment.
5. wait for `Server running at http://localhost:3000/`
5. Change markup in source-code/website/src/pages/index/index.page.tsx

### Expected behavior
- change is watched
- build message in terminal
- change is visible on website

### Additional information
- nothing happens after `@inlang/website:dev: Server running at http://localhost:3000/` in terminal

**Comment by samuelstroschein** [comment]
I did not manage to take a look at this issue and won't be able to take a look till 2 pm CEST tomorrow. 

I recall that I had a similar issue. The dev container seemed to slow down development tremendously, causing a slow HMR. I might be wrong, though.

**Comment by NiklasBuchfink** [comment]
### Problem
The inlang repo was not cloned/stored in WSL but the windows filesystem. File watchers from Windows don't propagate into WSL.
### Solution
1. Navigate to the Linux subsystem with `cd $HOME` & `cd /mnt`.
2. Clone the inlang repo directly into the Linux subsystem
3. Start development from there
### Note: 
Make sure that the user has the right to edit files. For Docker Desktop, this should be `node`.

Now it runs smoothly 👍
