### ISSUE TITLE
`ide-extension` fails to import dynamically

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#452]
## Problem

![image](https://user-images.githubusercontent.com/1105080/225942918-c217d055-cb9a-4467-a512-35d7154eec77.png)

```
[error] TypeError: A dynamic import callback was not specified.
	at new NodeError (node:internal/errors:371:5)
	at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
	at main (/home/user/.vscode/extensions/inlang.vs-code-extension-0.4.3/dist/main-186ff56f.cjs:7379:20)
```

## Steps to reproduce

Load production build of `ide-extension` in VSCode and start it.

## Expected behavior

Imports dynamically

## Additional information

https://stackoverflow.com/questions/75002605/vscode-extension-a-dynamic-import-callback-was-not-specified
https://github.com/microsoft/vscode/issues/152052 leads to https://github.com/microsoft/vscode/issues/130367
https://stackoverflow.com/questions/70620025/how-do-i-import-an-es6-javascript-module-in-my-vs-code-extension-written-in-type
https://gist.github.com/samthor/3ff82bd5b11314fec2e1826d4a96ce7c
https://github.com/uupaa/dynamic-import-polyfill
https://github.com/GoogleChromeLabs/dynamic-import-polyfill
https://github.com/rich-harris/shimport
https://github.com/microsoft/vscode/issues/166265

**Comment by felixhaeberle** [comment]
@openscript @samuelstroschein It works now 🎉
Now it's only about waiting for the vscode team to release the next version – they want to ship **early May** (first week).
see this: https://github.com/microsoft/vscode/issues/178951

Tested with these specs:

```
Version: 1.78.0-insider (Universal)
Commit: 208bbb0d788cce3eb80799e3565ee2204391b86d
Datum: 2023-04-20T05:22:30.460Z (Vor 5 Stunde(n))
Electron: 22.4.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Darwin arm64 22.4.0
Sandkasten: Yes
```

and this config file:

```js
// @ts-check

/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
  const plugin = await env.$import(
    "https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@1/dist/index.js"
  );

  const { standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/gh/inlang/standard-lint-rules@1/dist/index.js"
  );

  const pluginConfig = {
    pathPattern: "./resources/{language}.json",
  };

  return {
    referenceLanguage: "en",
    languages: await plugin.getLanguages({ ...env, pluginConfig }),
    readResources: (args) => plugin.readResources({ ...args, ...env, pluginConfig }),
    writeResources: (args) => plugin.writeResources({ ...args, ...env, pluginConfig }),
    lint: {
      rules: [standardLintRules()],
    },
    ideExtension: {
      messageReferenceMatchers: [
        async ( /** @type {{ "documentText": string; }} */ args) => {
          const regex = /(?<!\w){?t\(['"](?<messageId>\S+)['"]\)}?/gm;
          const str = args.documentText;
          let match;
          const result = [];

          while ((match = regex.exec(str)) !== null) {
            const startLine =
              (str.slice(0, Math.max(0, match.index)).match(/\n/g) || [])
              .length + 1;
            const startPos =
              match.index - str.lastIndexOf("\n", match.index - 1);
            const endPos =
              match.index +
              match[0].length -
              str.lastIndexOf("\n", match.index + match[0].length - 1);
            const endLine =
              (
                str
                .slice(0, Math.max(0, match.index + match[0].length))
                .match(/\n/g) || []
              ).length + 1;

            if (match.groups && "messageId" in match.groups) {
              result.push({
                messageId: match.groups["messageId"],
                position: {
                  start: {
                    line: startLine,
                    character: startPos,
                  },
                  end: {
                    line: endLine,
                    character: endPos,
                  },
                },
              });
            }
          }
          return result;
        },
      ],
      extractMessageOptions: [{
          callback: (messageId) => `{t("${messageId}")}`,
        },
        {
          callback: (messageId) => `t("${messageId}")`,
        },
      ],
    },
  };
}
```

**Comment by felixhaeberle** [comment]
this can be closed due to the latest vs code release. 🎉

<img width="340" alt="Bildschirmfoto 2023-05-08 um 07 45 36" src="https://user-images.githubusercontent.com/34959078/236743584-ea512e33-a358-4f51-96a6-2dbb0fd06b14.png">

**Comment by felixhaeberle** [comment]
Turns out this is not yet fixed as the issue is still open & not working in production.

https://github.com/microsoft/vscode/issues/130367

**Comment by samuelstroschein** [comment]
The immediate (and maybe only solution) that I can think of: 

1. Use a custom `$import` in the ide extension that: 
2. Transpiles code imported by `$import` to commonjs.
3. Uses `require(transpiledCode)` instead of `import`. 

That workaround is heavy but it might work.

**Comment by felixhaeberle** [comment]
@samuelstroschein I implemented this (https://github.com/inlang/inlang/commit/6994510f082c3fcd07a6666993cbc70f6680e291) as suggested and this surprisingly works, but now I'm getting the "Invalid host defined options" from other sources. 

<img width="783" alt="Bildschirmfoto 2023-05-15 um 16 42 41" src="https://github.com/inlang/inlang/assets/34959078/6cb8454f-2308-4589-b06e-592c10690688">

And after manually saving the main.cjs file to get a better line number for debugging, this is what causes the error:

<img width="785" alt="Bildschirmfoto 2023-05-15 um 16 47 36" src="https://github.com/inlang/inlang/assets/34959078/e378ad63-ab52-4a32-a0a2-b51f838c990c">

**Comment by samuelstroschein** [comment]
@felixhaeberle See my comment https://github.com/inlang/inlang/commit/6994510f082c3fcd07a6666993cbc70f6680e291#r113406606

**Comment by felixhaeberle** [comment]
the transpiled config output look like this, just in case this is interesting:

```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.defineConfig = void 0;
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
function defineConfig(env) {
    return __awaiter(this, void 0, void 0, function* () {
        const { default: jsonPlugin } = yield env.$import("https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js");
        const { default: sdkPlugin } = yield env.$import("https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.4.2/dist/index.js");
        const { default: ideExtensionPlugin } = yield env.$import("https://cdn.jsdelivr.net/npm/@inlang/ide-extension-plugin@latest/dist/index.js");
        return {
            referenceLanguage: "en",
            plugins: [
                jsonPlugin({
                    pathPattern: "./languages/{language}.json",
                }),
                sdkPlugin({
                    languageNegotiation: {
                        strategies: [{ type: "url" }],
                    },
                }),
                ideExtensionPlugin(),
            ],
        };
    });
}
exports.defineConfig = defineConfig;
```

**Comment by felixhaeberle** [comment]
Sadly, also after [a complete import refactor](https://github.com/inlang/inlang/commit/f0c179090c5484cee7678dd21f300c937f2d17ea), this doesn't work.

<img width="589" alt="Bildschirmfoto 2023-05-15 um 18 53 38" src="https://github.com/inlang/inlang/assets/34959078/6f6afd7c-9e14-4e5f-b772-64dfcbe0f7e4">

**Comment by samuelstroschein** [comment]
@felixhaeberle should I try to take over this issue? 

**Pros**

- I might be able to fix it faster / this week. Given that you are OOO for the rest of the week, we can push the extension out faster. 

**Neutral**

- You need to do https://github.com/inlang/inlang/issues/760 tomorrow instead of me

**Cons**

- I want you to be in charge of the IDE extension. Jumping in to solve issues seems to mix ownership. But, this issue seems deep and of high importance to finally get the ide extension running.

**Comment by samuelstroschein** [comment]
@felixhaeberle Okay, I take over this bug and assign you the CLI command.

**Comment by felixhaeberle** [comment]
@samuelstroschein thank you for fixing this 😊

**Comment by samuelstroschein** [comment]
@felixhaeberle you're welcome!
