### ISSUE TITLE
bug machine translation button is disabled

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#464]
# Problem 

The machine translation button is disabled even though a reference message exists.

Watch the screen recording here: https://jam.dev/c/a28fa158-e145-471b-afd1-c675432ad681

\-------------------------------------

**Website URL:**
[https://inlang.com/editor/github.com/inlang/example](https://inlang.com/editor/github.com/inlang/example)

**Device and browser info:**
Chrome 111.0.0.0 (1849x1120) | Mac OS 10.15.7

**Date and time:**
March 25th 2023 | 3:04pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/a28fa158-e145-471b-afd1-c675432ad681](https://jam.dev/c/a28fa158-e145-471b-afd1-c675432ad681)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by samuelstroschein** [comment]
fixed right?

**Comment by NilsJacobsen** [comment]
@felixhaeberle you found an other bug with this right?

Can you describe it?

**Comment by felixhaeberle** [comment]
It was in the @inlang/example on live when you delete a existing translation and the button appears, it failed then on "recreate" with clicking the button. It was an endless loading state of the button.

**Comment by samuelstroschein** [comment]
I might have fixed the issue with #518

**Comment by samuelstroschein** [comment]
I found the bug. Will fix it tomorrow. Has to do with env variables (again). We need to bundle them (erghhh).

**Comment by samuelstroschein** [comment]
has been fixed
