### ISSUE TITLE
Input field is broken in the Editor

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#489]
Missing Border

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/ab30374f-1290-41bb-8900-83001f9c0a33.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/b78eb12c-c1ec-442b-bac9-0feedcfa65f4.png)

\-------------------------------------

**Website URL:**
[https://inlang.com/editor](https://inlang.com/editor)

**Device and browser info:**
Chrome 111.0.0.0 (1440x764) | Mac OS 10.15.7

**Date and time:**
March 31st 2023 | 4:12pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/00fbd750-3833-4a09-80aa-bef87c2d42dc](https://jam.dev/c/00fbd750-3833-4a09-80aa-bef87c2d42dc)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by NilsJacobsen** [comment]
On it. We fix it asap

**Comment by NiklasBuchfink** [comment]
Fixed in this [commit](https://github.com/inlang/inlang/commit/222d32dd7e09ab54e429cefbaaf0f74645535d2a)

I reset the CSS class and it should be the same styling as before.
