### ISSUE TITLE
Responsive view for not logged in users has weird layout

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#491]
## Problem

Weird layout flow.

## Proposal

Hey, the layout could be better here with aligning the button underneath the text + icon. Right now, it takes a lot of space which could be better.

## Additional information

![https://user-images.githubusercontent.com/34959078/229354481-3c632b84-79cc-4b16-852e-463997d89c40.png](https://user-images.githubusercontent.com/34959078/229354481-3c632b84-79cc-4b16-852e-463997d89c40.png)

**Comment by samuelstroschein** [comment]
Since we don't care about mobile users (for now). Close this as not planned @felixhaeberle?

**Comment by felixhaeberle** [comment]
@samuelstroschein Sure!
