### ISSUE TITLE
Tooltip z-index issue

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#492]
## Problem

![image](https://user-images.githubusercontent.com/21335119/229355019-dee6d086-cd46-4125-9936-0254a0169d3f.png)

### Expected behavior

The tooltip should be displayed on top

**Comment by felixhaeberle** [comment]
At this point, I'm not sure if the tooltip should be displayed all the time, at least on mobile, it has unnecessary big importance / presence imho. I think this should be displayed on hover so the additional click to close it is also obsolete.

**Comment by NiklasBuchfink** [comment]
The stacking is now fixed for all notifications and the "Language detection" tooltip is now set to fades out after 5 seconds. Mobile is atm not a prio.

**Comment by jannesblobel** [comment]
closed 
https://github.com/inlang/inlang/commit/23ddc0139e44908bab894f5fe53ed5f1d72449b3
