### ISSUE TITLE
Add a "message/alert…" if there are no missing messages 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#501]
currently, you don't know that everything was good and there are no messages that contain errors. 

Maybe you should just add a message "no messages to translate".

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/16031ce6-78a0-4c41-aa93-5f5b2cca8a2a.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/403a1d87-399d-4f8d-a576-28734372b4b3.png)

\-------------------------------------

**Website URL:**
[https://inlang.com/editor/github.com/inlang/example](https://inlang.com/editor/github.com/inlang/example)

**Device and browser info:**
Chrome 111.0.0.0 (1440x764) | Mac OS 10.15.7

**Date and time:**
April 3rd 2023 | 10:06am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/18d952a5-5619-4198-bddb-da03eacd2e35](https://jam.dev/c/18d952a5-5619-4198-bddb-da03eacd2e35)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by NiklasBuchfink** [comment]
Empty state added in https://github.com/inlang/inlang/pull/507
