### ISSUE TITLE
Bundle shared dependencies of CLI: '@inlang/shared@*' is not in this registry.

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#509]
## Summary
When attempting to install the "@inlang/cli" package using the command "npx @inlang/cli", the installation failed due to a 404 error with the "@inlang/shared" package.

## Steps to Reproduce

Run the command "npx @inlang/cli" in the terminal.
When prompted to proceed with installation, type "y" and press Enter.
Expected Result:
The "@inlang/cli" package should be installed successfully.

## Actual Result
The installation failed with the following error message:

```sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@inlang%2fshared - Not found
npm ERR! 404 
npm ERR! 404  '@inlang/shared@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/felixhaberle/.npm/_logs/2023-04-04T10_22_43_975Z-debug-0.log
```

### Expected behavior

This should work and we should bundle the shared artifacts of the CLI into the CLI.

**Comment by samuelstroschein** [comment]
fixed
