### ISSUE TITLE
Support variables in the plugin-json

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#520]

**Comment by samuelstroschein** [comment]
blocked by https://github.com/inlang/inlang/issues/517

**Comment by samuelstroschein** [comment]
Supporting placeholders in inlang-plugin-json is not straightforward. inlang-plugin-json would require additional config for placeholder detection. 

```ts
const pluginConfig = {
    pathPattern: "./{language}.json",
    variableMatcher: ??? 
};

```

The config requires knowing how variables should be matched/parsed and serialized. While variables might be easy to match, every other placeholder is not and likely benefits from dedicated plugins.
