### ISSUE TITLE
e2e tests for adapter-sveltekit

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#523]
All use cases from #522 need to be tested in order to easily see if the automatic injection of the plugin does not break anything

**Comment by felixhaeberle** [comment]
@ivanhofer Have you had a look on this and should I do the tests for the lang-in-slug more flexible? At the moment, it does test all the functionality but it isn't that flexible like picking up the languages and translations dynamically? 

I think the current status is good enough for now, I'm curious what do you think?

**Comment by ivanhofer** [comment]
@felixhaeberle sorry, I was busy today and could not look at the tests. There are now 3 different examples in the repository. A 4th one will follow next week. I think the tests can wait until then. We can make a call next week to discuss what tests are needed.

**Comment by felixhaeberle** [comment]
@ivanhofer Great work with the additional examples!! :) For sure, just ping me again when you're ready to get the tests going 🙏

**Comment by ivanhofer** [comment]
@felixhaeberle I have added a few dummy test files in the PR. They are full of `TODO` comments. Please check them and let me know if something is unclear. We can schedule a call if you want.

**Comment by felixhaeberle** [comment]
I'm on the README project atm – but later this week we can schedule something for sure!! 
Thanks for putting the `TODO`s in there, much appreciated 🫶

**Comment by ivanhofer** [comment]
@felixhaeberle I just merged #484. So you need to create a new PR for the tests.

**Comment by felixhaeberle** [comment]
@ivanhofer alright, thanks for the heads-up 👍

**Comment by felixhaeberle** [comment]
@ivanhofer we decided to postpone this for a few days (at least for me) in favor of testing and finishing the ide extension before svelte summit.

**Comment by ivanhofer** [comment]
> Does the scope of the issue include build tests?

It is the plan. But we need to think about a testing strategy first. We will probably need hundreds of examples to cover everything.

**Comment by jannesblobel** [comment]
@ivanhofer  Can we close this issue? or is that still a todo?

**Comment by ivanhofer** [comment]
This is one of the more important tasks. But also requires some time to implement it. I can start on this after the beta release.
