### ISSUE TITLE
README project: create image with project lints (missing translations)

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#535]
## Goal

- Provide contributors with visibility in a readme whether or not translations need to be created/updated.
- Increase inlang opening rates in READMEs

We can use the readme more like a one-pager and share the information on the translation status in the [[[readme.md](http://readme.md/)](http://readme.md//)] ([http://readme.md](http://readme.md/)). The community gets a better overview of the translations and is more encouraged to contribute the missing translations.

## Approach
Generate a image based on a url which is in the format of:

```html
<img src="https://inlang.com/badge?url=github.com/inlang/example">
```

### General

The inlang service then returns a image based on this url where you can see the translation progress in general and for each language as bar charts with a progress indicator. The bar charts could be green. 

### Width

The width of the image could differ for example we could provide sizes like sm, md, lg and with these sizes the width of the image could be controlled. I would go for a small version as default (375px-400px width) because then it's also easy to read on smartphones and in GitHub Mobile. Technically, we could specify a `&size` argument with parameter of `sm`, `md` and `lg`.

### Link with editor for conversion

The image should be linked with the Inlang editor in the Readme of a project, so the final output in a markdown file would look like this:

```html
<a href="https://inlang.com/editor/github.com/inlang/example">
<img src="https://inlang.com/badge?url=github.com/inlang/example" alt="translation progress as bar charts">
</a>
```

This is an example:

<img width="670" alt="CleanShot 2023-02-18 at 22 35 29@2x" src="https://user-images.githubusercontent.com/34959078/231105952-332b15f5-2321-4e1e-a885-851b5e40fad9.png">

## Technology
[https://og-playground.vercel.app/](https://og-playground.vercel.app/)

[https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation)

**Comment by samuelstroschein** [comment]
Exactly what I had in mind. LGTM!

Regarding UI questions like colors, height, width etc. I wouldn't worry too much. We can iteratively improve the design and introduce different variants like `https://inlang.com/badge?url=github.com/inlang/example&variant=large`

**Comment by jannesblobel** [comment]
I disagree on one point. 
The height is essential. If a Repo has 50+ Languages and 43 missings/lint errors, we can only show some of it with a chart. Maybe show only the top 3 and the others as chips/tags.

**Comment by felixhaeberle** [comment]
@jannesblobel I would consider this a a scaling issue. 
We can improve this over time if we see a repository with 50+ languages. 😄 
Or do we have one already?

**Comment by jannesblobel** [comment]
> @jannesblobel I would consider this a a scaling issue. We can improve this over time if we see a repository with 50+ languages. 😄 Or do we have one already?


Yep 
<img width="365" alt="CleanShot 2023-04-11 at 17 48 34@2x" src="https://user-images.githubusercontent.com/72493222/231217979-a369685d-7081-4bc6-aecd-9f29f6f0ba90.png">

**Comment by samuelstroschein** [comment]
From a call with @NilsJacobsen: 

- we can A/B test badges 
- and lol we can even show different badges based on the users browser -> "5 missing Italian translations" instead of a generic "70% complete" badge etc.

**Comment by felixhaeberle** [comment]
@jannesblobel @samuelstroschein As we are generating charts in the server context and most libraries require canvas rendering, we need to use something that supports server-side rendering (SSR). For example, we could use a library like chart.js-node-ssr-example. 
https://github.com/shellyln/chart.js-node-ssr-example

However, for simplicity's sake, I would prefer something like the solution described in this StackOverflow answer: https://stackoverflow.com/a/7191071.

**Comment by NilsJacobsen** [comment]
If we adjust the content per user (per browser languages) we probably get some similar outputs on the image as in the editor. Maybe we should discuss some kind of alignment at some point.

**Comment by samuelstroschein** [comment]
> Maybe we should discuss some kind of alignment at some point. 

You are having different goals with each visualization. Alignment might not be worth it. 

Badges -> get users on the editor
Editor -> get users to contribute 

I assume that both goals lead to different, even if only slightly, visualizations.

**Comment by felixhaeberle** [comment]
@samuelstroschein You are totally right, we will for sure not duplicate visualization and everybody has its getting own goal as you described. 

@NilsJacobsen Just follow this issue where I keep everyone updated and maybe have a look at the readme-project branch for details. 

If the Satori bug (which prevents using fonts/text in general) is fixed, I want to get this out asap.

**Comment by felixhaeberle** [comment]
Just to keep you updated here:

This morning I spend 2h debugging why satori-html isnt working with variables and dynamic array maps and found out that this library doesn't escape the JS used in the template literals correctly so I have to parse it myself and remove trailing commas & more. 

Unfortunately, the satori package is compiled so I can't patch the bug in there which is preventing us from using text in the image. I'm on it and will write shuding from Vercel again if there is no action in the next days.

**But** 🎉🎉🎉

We now have a first working solution! It's not that special and nice and gets a visual facelift (maybe today) – but I'm proud 😊

<img width="965" alt="Bildschirm­foto 2023-04-13 um 11 55 28" src="https://user-images.githubusercontent.com/34959078/231725263-f30a587f-4b43-475d-afd8-036ca8fb319f.png">

**Comment by felixhaeberle** [comment]
Thanks! But will be even better with a nice design. ✨
Oh you're right!! Let me try this with a fork and see how this goes.

**Comment by felixhaeberle** [comment]
get preferred language from accept language header concept

```ts
interface LanguagePriority {
  language: string;
  priority: number;
}

const parseAcceptLanguageHeader = (acceptLanguageHeader: string): LanguagePriority[] => {
  const languagePriorities: LanguagePriority[] = [];

  if (!acceptLanguageHeader) {
    return languagePriorities;
  }

  const languagePriorityStrings = acceptLanguageHeader.split(",");
  for (const languagePriorityString of languagePriorityStrings) {
    const [language, priorityString] = languagePriorityString.trim().split(";q=");
    const priority = priorityString ? parseFloat(priorityString) : 1;
    languagePriorities.push({ language, priority });
  }

  return languagePriorities;
};

const getPreferredLanguage = (languagePriorities: LanguagePriority[]): string | undefined => {
  let preferredLanguage: string | undefined;
  let highestPriority = 0;

  for (const languagePriority of languagePriorities) {
    if (languagePriority.priority > highestPriority) {
      highestPriority = languagePriority.priority;
      preferredLanguage = languagePriority.language;
    }
  }

  return preferredLanguage;
};

// Example usage
const acceptLanguageHeader = "en-US,en;q=0.8,fr;q=0.6";
const languagePriorities = parseAcceptLanguageHeader(acceptLanguageHeader);
const preferredLanguage = getPreferredLanguage(languagePriorities);
console.log(preferredLanguage);

```

**Comment by felixhaeberle** [comment]
hey people ✨
nice progress here ☀️

I had to tweak the logic behind it a lot to fix all edge cases but now we have something really stable:

1. Checks if the preferred language is set. If not, it sets it to English.
2. Removes the region code from the preferred language (e.g. "en-US" becomes "en"). This is only for language name in the stringe.g. en -> english
3. Checks if the preferred language is in the project. If not, it falls back to English. If English is not in the project either, it sets the preferred language to the first language in the project.
4. Sorts the percentages by preferred language. If a percentage has the preferred language, it is placed at the beginning of the array. If it does not have the preferred language, it is placed after the percentages that do.

🎉 This is the **updated** design:

![badge (2)](https://user-images.githubusercontent.com/34959078/232455436-3f9bd628-b3d2-4006-8dd4-d2b53cecbde2.png)

![badge (3)](https://user-images.githubusercontent.com/34959078/232455571-6330c538-c959-4136-a549-3a9d6f52b394.png)

![badge (4)](https://user-images.githubusercontent.com/34959078/232455749-cb5312a6-ee43-4c74-bd6d-dc3bb9fa40f6.png)

**Comment by samuelstroschein** [comment]
I find the mock on Discord more actionable.

- Only one sentence, the CTA.
- Contribute button, nudging the user to click on the button

Regarding one sentence: "92% translated" is not a CTA. "support {repository} [...]" seems redundant if "214 German translations are missing" and a large "contribute" button is below. 

Besides, the badge should probably have a fixed height. Otherwise, markdown layouting will be hard. 

![image](https://user-images.githubusercontent.com/35429197/232465215-3a70f0af-4961-4c6f-9397-67568b5012e5.png)

**Comment by felixhaeberle** [comment]
I think this are different scenarios:

first: displaying the translation status at top priority because of the maintainer it's nice to see this status

second: having the missing messages a top priority, but then: what's with other lint rules? for example the easiest "no reference"? 

___

Fixed height: then the question arises: which are the ones I want to display? random? languages with most misses (think lint rules triggered)? I think the current implementation gives a good overview.

What do you mean with markdown layout? images are rendered block style so they render in the size provided by the image itself on github.

**Comment by samuelstroschein** [comment]
> first: displaying the translation status at top priority because of the maintainer it's nice to see this status

This will become part of CI/CD. 

I see a README for external members to get an overview of a project. Keep in mind: The funnel you are optimizing is to get contributors on the editor. Not to give an overview for maintainers. This goal in maintainers' interest: They get contributions. 

> second: having the missing messages a top priority, but then: what's with other lint rules? for example the easiest "no reference"? also, it's a common scenario to have 0 missing messages. it makes no sense to display that. it then makes sense to say: you're doing good: 100% is translated. and we then are back to the first scenario.

Great. I suggest to fallback to "fully translated" but don't display both "93% complete" and "14 german translations are missing". I _assume_ that displaying both will lead to a weaker CTA. 

----

> What do you mean with markdown layout? 

Images (usually) don't have varied heights/widths. Using the badge in the README requires a fixed format. Imagine the badges on our README to suddenly become 5x as large as they are now -> takes too much space, fucks up the layout -> will be removed.

<img width="893" alt="CleanShot 2023-04-17 at 13 52 27@2x" src="https://user-images.githubusercontent.com/35429197/232476411-63b09383-6d17-4d53-8542-7bb8d0afa494.png">


> Fixed height: then the question arises: which are the ones I want to display?

Honestly. Screw the bar charts then. Just show "12 German translations are missing" or fallback to "100% translated". 



----

Whatever you decide. Try to push something out today, make PRs to repos and will take it from there.

**Comment by felixhaeberle** [comment]
Ah, now I know what you mean!!
So the answer is: We're not going for the small inline badges for now. 

If you want to display it, this is probably how it should work:

<img width="893" alt="232476411-63b09383-6d17-4d53-8542-7bb8d0afa494" src="https://user-images.githubusercontent.com/34959078/232478494-face54e3-f53c-40bb-bde5-ec088fbc1414.png">

## Translation

<a href="https://inlang.com/editor/github.com/inlang/example">
<img src="https://i.ibb.co/s1JNrnP/badge-8.png" alt="translation status on inlang" />
</a>

**Comment by samuelstroschein** [comment]
@felixhaeberle yeah make sense. But imagine the badge becoming ultra long. What would be the result? Every maintainer places the badge at the very bottom of README -> low visibility. 

Regardless, push something out today 🚀

**Comment by ivanhofer** [comment]
> get preferred language from accept language header concept

You can use the functionality from `@inlang/sdk-js`: https://github.com/inlang/inlang/blob/main/source-code/sdk-js/src/detectors/detectors/server/acceptLanguageHeaderDetector.ts

**Comment by felixhaeberle** [comment]
@samuelstroschein & me revisited the design and came up with a radical easier approach because of multiple reasons.

![badge (10)](https://user-images.githubusercontent.com/34959078/232711995-be67792f-0fe9-46d7-9ca6-af8fafbbac68.png)

What do you all think? 
We wanted to have something smaller and the bar charts where not optimal, so got rid of them – bringing the number of the overall translation status and especially the number of errors and warning in the spotlight. 

Furthermore, we switched the button design from link to real black button to give it more affordance. I'm prety happy with it now!! ✨

**Comment by samuelstroschein** [comment]
Yeah, honestly great. Do messages like "3 German translations are missing" still exist?

**Comment by felixhaeberle** [comment]
Missing messages: I left them out for now but we can add them back if you want. I think the current state is really clean and I like it this way. 

Additionally, the visual approach scales very well with lints in general because we're not focusing so much on the missing message lint in a bit of an singular way e.g. giving one lint more importance (in form of text) than others. 

Furthermore, the badge is really small now and we could convince maintainers more add this to their README's at an reasonable place (further to the top of the README).

Percentages: We also have to think about fixing the percentage as you said they are not correctly calculated but I think so, overall there are 3 lint errors in all languages. 

Therefore the overall percentage seems right because its not language specific here?

**Comment by felixhaeberle** [comment]
@samuelstroschein Now we're good to go I think 😄 – everybody is happy now 😂

![badge (11)](https://user-images.githubusercontent.com/34959078/233061184-714e2646-5d79-415b-8b16-bfa7af912b1a.png)

**Comment by samuelstroschein** [comment]
> @samuelstroschein Now we're good to go I think 😄 – everybody is happy now 😂
> 
> 
> 
> ![badge (11)](https://user-images.githubusercontent.com/34959078/233061184-714e2646-5d79-415b-8b16-bfa7af912b1a.png)
> 
> 

Yes leeeets go 😂

**Comment by felixhaeberle** [comment]
@samuelstroschein and added tests (partially) 😇

**Comment by felixhaeberle** [comment]
@samuelstroschein Closing this for now as fixed! We'll improve it further based on feedback. 👍

**Comment by felixhaeberle** [comment]
Changes above are introduced in 3b2429d
