### ISSUE TITLE
editor crashes when user opens a private repository and is not signed in

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#543]
## Problem

A 401 error or complete crash is shown when a private repository is cloned AND the user is not logged in.

### Expected behavior

Show information that the user must log in to view their private repositories.

## Steps to reproduce

1. Ensure you are signed out. 
2. Try to open a private repository. 

### Additional information (screenshots?)

<img width="877" alt="CleanShot 2023-04-13 at 09 49 02@2x" src="https://user-images.githubusercontent.com/35429197/231691751-3472550c-2146-4971-9a57-883051c79036.png">

https://user-images.githubusercontent.com/35429197/231691768-773a964e-2f03-4792-ae24-034d0dfb1fea.mp4

**Comment by felixhaeberle** [comment]
@samuelstroschein If the user is authenticated, does the editor work then? Can private repositories in general be fetched by the editor? If yes the issue is only detecting a private repo and redirect the user to sign-in.

**Comment by samuelstroschein** [comment]
@felixhaeberle yes editor works on private repos.

**Comment by felixhaeberle** [comment]
@samuelstroschein So as I understand correctly this only happens because of a *missing redirect to login* when we aren't able to fetch the repo when the editor is initialized?

**Comment by samuelstroschein** [comment]
fixed by @NiklasBuchfink and @felixhaeberle

**Comment by felixhaeberle** [comment]
fixed in d1e242b083cf218f2ebc4e83b060704ebc8f725d

**Comment by samuelstroschein** [comment]
Hasn't been fixed. Follow up in #774
