### ISSUE TITLE
SDK-JS unit tests need to be fixed

### ISSUE THREAD

**Issue by benjaminpreiss** [inlang/inlang#546]
## Problem

The unit tests of the JS SDK are not working currently. 

<img width="1141" alt="Screenshot 2023-04-13 at 16 56 11" src="https://user-images.githubusercontent.com/28349122/231709260-aaf7c3f3-4723-4315-af7a-66f4ece37d3c.png">

## Proposal

Let's fix the unit tests 🚀

**Comment by ivanhofer** [comment]
Ah, now I see the issue. I'll make a PR
