### ISSUE TITLE
Sometimes a commit is not processed correctly. 

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#553]
## Problem
I expereinced it in a test repo. I entered some translations. Then I pressed `commit`. The button disappeared but I didn't get a number next to the `push` button. But sometimes it works. After pushing the changes I saw that some commits has not been processed correctly.

Example Commit:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/58360188/232012542-115c7853-5a0c-4db6-8d65-4b9b60a2d807.png">

Other Commit:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/58360188/232012706-f25beff9-d39a-4c1e-adcc-05a6e9427cd8.png">

### Expected behavior
It should consistently do the same thing every time.

### You can try it here
https://inlang.com/editor/github.com/NilsJacobsen/AppFlowy

### Additional Information
It works perfectly fine in the example project

**Comment by felixhaeberle** [comment]
@NilsJacobsen Where do you think is the reason for this? As you know the editor better than me, where could this issue potential result from?

Is it the speed so things are async and doesn't update in the correct order or has it to do with updating the state?

**Comment by NilsJacobsen** [comment]
Can you reproduce it? I'm not sure if @samuelstroschein and Shannon fixed that.

**Comment by samuelstroschein** [comment]
Don't know the root cause. Someone needs to start a debugging session. I would help https://github.com/thetarnav/solid-devtools/issues/233 to get better debugging capabilities before tackling this issue

**Comment by NilsJacobsen** [comment]
Actually i couldn't reproduce it anymore. We have still super long loading times with for commits in big repos but hopefully that gets better in the future.
