### ISSUE TITLE
Editor dropdown

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#571]
From a conversation with @NiklasBuchfink #562 

> Do you have any suggestions on how to improve this issue without completely rewriting the filter selections?

I think there is a lot to improve!
Vgl. those: Multiple icon sizes, multiple font colors, multiple font spacings, multiple font weight. 
I think the current state is very noisy right now. I tried some corrections.

Previous
<img width="444" alt="Bildschirmfoto 2023-04-20 um 10 33 44" src="https://user-images.githubusercontent.com/34959078/233309057-371c5203-2eb2-41f1-9e26-797267506b25.png">

After
<img width="465" alt="Bildschirmfoto 2023-04-20 um 10 33 17" src="https://user-images.githubusercontent.com/34959078/233309271-4b7f1f41-8d5b-4bf2-92fa-12b33e5f12bd.png">

**Comment by NiklasBuchfink** [comment]
As already mentioned in https://github.com/inlang/inlang/pull/562#issuecomment-1516039073
> @felixhaeberle Making the filter dropdown exactly like the summary would not work if the language filter is removed and needs to be added. Also, as a user, I would suggest that the lints then act as AND and not OR.

So this proposal is not possible because it would not be consistent with the hierarchy of languages or the perceived filtering logic:
> I would expect the same options as I have in the "summary" now. Because thats what I want to achieve with the filter? Instead, I get a "lint" option which I don't understand.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink I updated the issue description accordingly.

**Comment by samuelstroschein** [comment]
Closing as stale.

**Comment by NilsJacobsen** [comment]
@felixhaeberle can you report what you think that need to be done here?

**Comment by felixhaeberle** [comment]
An explanation will be provided when the task is reopened & the editor dropdown is being reworked 😄

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Since the opening of this issue, some things have been improved, but only some things. And the main reason is that it is quite time-consuming to design the web components. That's why it has yet to be easily fixed in the meantime on the side.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Indeed, thanks for fixing some things 🤗 But there are still a few things missing.

Still bugs on:
- font sizing
- coloring (accessibility + consistency)
- background-coloring (accessibility)
- icon sizing
- spacing
