### ISSUE TITLE
Overlapping text with longer file names

### ISSUE THREAD

**Issue by adil192** [inlang/inlang#573]
## Problem

Text is cut off with longer file names. It seems like you should be using a `<table>` element for this layout rather than flexbox.

### Expected behavior

Text should be visible and non-overlapping

## Steps to reproduce

1. Go to https://inlang.com/editor/github.com/NilsJacobsen/saber/ (from https://github.com/adil192/saber/pull/598)
2. See overlapping text like the screenshots

### Additional information (screenshots?)
![image](https://user-images.githubusercontent.com/21128619/233977025-6924c1d3-75b9-4c1f-8d7e-ded50572c10c.png)
![image](https://user-images.githubusercontent.com/21128619/233977358-0c4134eb-c889-4788-a879-72c3aaac1bf9.png)

**Comment by NilsJacobsen** [comment]
We decided to close this issue for now, cause the approach should be to build a slang specific plugin, to get only the language ids in the editor. This is also helpful when it comes to machine translate tasks. If you want to support us build the plugin we would really appreciate that.

Thanks:)
