### ISSUE TITLE
Replace loading spinner with onProgress event output in editor

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#575]
The current implementation of the loading spinner in our editor is not very informative and does not provide users with any indication of the progress of the operation. This can lead to frustration and confusion, which may increase the bounce rate of the editor.

<img width="794" alt="Bildschirmfoto 2023-04-24 um 14 57 37" src="https://user-images.githubusercontent.com/34959078/234003101-6044001c-d742-44c3-a435-4a5fbfb7ac55.png">

As a potential solution, we can replace the loading spinner with the onProgress event and a loading bar. This would provide users with a better understanding of the progress of the operation and help them to remain engaged with our application.

### Proposed Solution
We can update our editor to use the onProgress event provided by the `isomorphic-git` library. This event provides us with a phase property that describes the current phase of the operation, along with a loaded property that describes the progress of the current phase.

We can utilize this information to create a loading bar that provides users with an indication of the progress of the operation. We can also display the phase property to provide users with a better understanding of what is happening in the background.

By updating our editor in this way, we can improve the user experience of our application and decrease the bounce rate by providing users with more information about the progress of the operation.

### Technical implementation

https://isomorphic-git.org/docs/en/onProgress

*from isomorphic-git doc*
Progress events are not guaranteed to be in order or always incrementing. Many git commands (like clone) actually consist of multiple sub-commands (fetch + indexPack + checkout) which makes computing a single progress percentage tricky. Instead, progress events are marked with a phase that provides a description of what step of the process it is in. You could choose to show the phase as a label next to the progress bar, or show one progress bar per phase.

#### Usage Example:

```js
import { clone } from 'isomorphic-git'
clone({
  ...,
  onProgress: event => {
    updateLabel(event.phase)
    if (event.total) {
      updateProgressBar(event.loaded / event.total)
    } else {
      updateIndeterminateProgressBar(event.loaded)
    }
  }
})
```

**Comment by felixhaeberle** [comment]
On a 🎨 design note, this could potentially developed in a direction GitHub is going with its Codespaces

- communicating to the user which process is currently underway
- and how long does it take
- the Aha moment: This is Git-in-browser and I can directly commit and pull / push without any hassle ✨

<img width="757" alt="Bildschirmfoto 2023-04-25 um 10 43 27" src="https://user-images.githubusercontent.com/34959078/234224016-74acf0b3-753e-4ae6-b840-f4e86bc6e86c.png">

**Comment by jannesblobel** [comment]
I  suggest a loading skeleton like on the big social media platforms 
we can see some users left the editor in the loading progress. 

The user gets the feeling something happened, and we use this time to display a short text like in the screenshot 

![Loading skeleton](https://user-images.githubusercontent.com/72493222/234369331-db836be8-a4fc-436c-91d5-4034744c1336.png)

**Comment by felixhaeberle** [comment]
@jannesblobel Thank you for the design!! I think it's a bit noisy with the text over the gray shapes. Can this be further improved? Also, isomorphic git supports various phases: checkout, index, fetch (or something) and therefore it's not one loading event but multiple. How can we reflect this in the design?

**Comment by jannesblobel** [comment]
I have found some interesting articles. 

But I agree the skeleton with spinner and text is too noisy.
But We shouldn't change the loading interphase in the different phases. 
With every change to a new phase/UI, the user thinks it is finished and sees the interface.  

@NilsJacobsen Maybe you have some thoughts about this topic 

https://www.linkedin.com/pulse/moving-away-from-loading-icon-start-using-skeleton-screen-prasad#:~:text=Skeleton%20Screen%3A%20The%20skeleton%20screen,of%20the%20page%20is%20loading.

https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a

**Comment by felixhaeberle** [comment]
@jannesblobel You mean the YT loading animation right? With the spinner for the video and the skeleton for the video list?

**Comment by felixhaeberle** [comment]
Oh I tought this loading experience?


https://user-images.githubusercontent.com/34959078/234623033-2904be71-253c-43c8-8939-8fd8b5a5e7af.mov

**Comment by samuelstroschein** [comment]
> But We shouldn't change the loading interphase in the different phases.
> With every change to a new phase/UI, the user thinks it is finished and sees the interface.  

@jannesblobel I understand @felixhaeberle [idea](https://github.com/inlang/inlang/issues/575#issuecomment-1521413108) is to show the individual steps in a more "devy" way to illustrate that git is ran in the browser. 

Regarding your placeholder idea: Going for placeholders with a skeleton is a massive undertaking because every component that will be rendered must be mocked to avoid layout shifts. Given the fast iteration process, this is a massive undertaking that will break constantly because the editor layout is not fixed yet.

**Comment by samuelstroschein** [comment]
Closing as "no priority".
