### ISSUE TITLE
Lint numbers arent calculated "correctly"

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#576]
## Problem

Hey there, as it can be seen on the image, the numbers aren't matching. Maybe this is a false positive but it is really confusing, and clicking on the [25] missing messages don't show them, but only show 3 because as I found out after clicking around wildly that this is contextual with the languages. 

### Expected behavior

I don't know, at the moment this is confusing. Maybe the language filter should be reset to all when clicking on the summarized lints. (25) to display them all. 

## Steps to reproduce

I corrected all of the missing translations in this example so I don't have a example anymore but I think the problem is clear showing the picture.

### Additional information (screenshots?)

<img width="1298" alt="Bildschirmfoto 2023-04-24 um 16 08 58" src="https://user-images.githubusercontent.com/34959078/234220453-cb1538b4-2789-428f-84bc-ae0b956a8935.png">

**Comment by NilsJacobsen** [comment]
Already in discussion #574
