### ISSUE TITLE
Editor: Parsing all language files fails if a single json file is invalid.

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#591]
## Problem
If any of the language files breaks, all working ones (in the same directory) are also not displayed in the inlang editor.

### Expected behavior
Parsing the language files one-by-one and only showing the working ones.

## Steps to reproduce
1. Go to a translation file
2. Insert an array or similar to get an invalid json
3. open the inlang editor to see the current behavior

**Comment by samuelstroschein** [comment]
this is a plugin issue. closing in favor of https://github.com/samuelstroschein/inlang-plugin-json/issues/6
