### ISSUE TITLE
use private rely email of users to not expose real email in commits

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#634]
## Problem

<img width="822" alt="CleanShot 2023-05-04 at 07 23 36@2x" src="https://user-images.githubusercontent.com/35429197/236236872-a1b40e7d-2252-4fc9-9d6a-3d49dde47f8f.png">

## Proposal

Use private rely emails for commits.

**Comment by felixhaeberle** [comment]
@samuelstroschein I take that one and work on it on Monday. If somebody can have a look earlier, then go for it!

**Comment by felixhaeberle** [comment]
This could potentially be fixed with the noreply mail provided by github.

```js
const authToken = "your_auth_token_here";
const apiUrl = "https://api.github.com/user/emails";

fetch(apiUrl, {
  headers: {
    Authorization: `Bearer ${authToken}`,
    Accept: "application/vnd.github.v3+json"
  }
})
  .then(response => response.json())
  .then(data => {
    const noreplyEmail = data.find(email => email.email.endsWith("@users.noreply.github.com"));

    if (!noreplyEmail) {
      throw new Error("Unable to find a noreply email address for this GitHub account.");
    }

    console.log(noreplyEmail.email);
  })
  .catch(error => console.error(error));

```

**Comment by felixhaeberle** [comment]
@samuelstroschein This is fixed! We switched to the non private noreply mail for the commits.
