### ISSUE TITLE
Linkability of filters for editor messages (id, missing messages ...)

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#637]
### Description
The web editor currently allows users to apply multiple filters to translate messages. However, when the page is reloaded or the URL is shared, the filter settings are lost and the user has to reapply them. This is not a great user experience and can be frustrating. We need to implement a solution that allows the filter settings to persist in the URL so that they are always in sync and can be shared with others. This will massively increase the user experience.

The corresponding code can be found in the `source-code/website` folder of this repository, there is a structure which handles the editor rendering and the components for it. those components should be modified to read and write to and from the URL. 

### Requirements
- [ ] When a filter is applied, the filter settings should be added to the URL as query parameters.
- [ ] When the page is reloaded or the URL is shared, the filter settings should be read from the URL and applied to the editor.
- [ ] If no filters are applied, the URL should not have any query parameters related to filters.
- [ ] If a user removes a filter, the corresponding query parameter should be removed from the URL.
- [ ] If a user changes a filter setting, the corresponding query parameter should be updated in the URL.
- [ ] If multiple filters are applied, the URL should contain multiple query parameters.
- [ ] The filter settings should be stored in the browser's history so that users can use the back and forward buttons to navigate between filter states.
- [ ] The filter settings should also be updated in the URL when the user navigates between pages within the web editor.

### Acceptance Criteria
- [ ] Filter settings persist in the URL when applied, removed, or updated.
- [ ] Filter settings are correctly applied to the editor when the page is reloaded or the URL is shared.
- [ ] Users can navigate between filter states using the back and forward buttons.
- [ ] Filter settings are updated in the URL when navigating between pages within the web editor.

**Comment by samuelstroschein** [comment]
Closing as stale/no priority. 

Feel free to re-open if you disagree.

**Comment by NilsJacobsen** [comment]
https://github.com/inlang/inlang/issues/893 This is kind of duplicate. Gonna close this for now. Will be done this week.
