### ISSUE TITLE
✖ Failed to generate config file.

### ISSUE THREAD

**Issue by OLM0** [inlang/inlang#642]
Struggeling to setup my project:

```sh
pnpm install @inlang/cli -g
inlang config init
✖ Failed to generate config file.
undefined
```

**Comment by felixhaeberle** [comment]
Thank you for submitting this bug. @samuelstroschein Can you investigate further? 🙏

**Comment by OLM0** [comment]
@felixhaeberle i tried to set it up manually but then the editor started panicking once i point it to the repo  

```json 
[ { "code": "invalid_type", "expected": "function", "received": "undefined", "path": [ "readResources" ], "message": "Required" }, { "code": "invalid_type", "expected": "function", "received": "undefined", "path": [ "writeResources" ], "message": "Required" } ]
```

According to the docs (getting-started) i should import the following line:
```ts
const { pluginJson } = await env.$import("https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@1/dist/index.js")
```
however the the plugin repo says it should be the following one instead
```ts
const { default: jsonPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js"
  );
```
Neither is working for me at the moment!

**Comment by samuelstroschein** [comment]
Hi @OLM0, 

Is your repo public? If so, I could add the config for you. 

> According to the docs (getting-started) i should import the following line:

Thanks, the docs are referring to version 1 of the plugin json. I'll update them right away!

**Comment by samuelstroschein** [comment]
Will be solved as part of https://github.com/inlang/inlang/issues/544

**Comment by samuelstroschein** [comment]
The error message and auto gen capabilities have been improved with https://github.com/inlang/inlang/issues/662. Closing this.
