### ISSUE TITLE
Resources don't get reloaded if they change on disk

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#646]
same problem when changing the `referenceLanguage` or adding a new language

**Comment by samuelstroschein** [comment]
> we don't really know where resources are located  

You could add a proxy that tracks all `readFile` calls to derive what files need to be watched.

cc @araknast This is a similar problem to lazy cloning/loading where we need to know what files have been read from the filesystem.  

(We are getting into reactive programming territory :/)

**Comment by ivanhofer** [comment]
> You could add a proxy that tracks all `readFile` calls to derive what files need to be watched.

And how do I know where the files are located with the proxy?
