### ISSUE TITLE
hide generated files from file system

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#647]
Currently we need to create empty files so `SvelteKit` knows that e.g. a `+layout.server.js` file is present.

Ideally those files should be hidden, but this is currently only possible by patching the `fs` module.

We have already talked to the `SvelteKit` team and are looking for a solution.

**Comment by WarningImHack3r** [comment]
@samuelstroschein I'm sorry for the loss of Ivan, it is such shocking news...

Discussing with him and you through the multiple issues, PRs, and conversations we could have had has always been pleasant. Ivan seemed to be a passionate guy and the lead developer of Inlang, Prayers for his family and hope you'll find a way to continue this project despite this terrible announcement.

Best of luck.

**Comment by samuelstroschein** [comment]
@WarningImHack3r Thank you. The project (skd-js/paraglide js) will continue, no worries.

**Comment by karianpour** [comment]
While fixing the issue, please also fix the issue with the `/src/routes/[lang]` in a way that it also accept the group layout as mentioned [here](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group)
