### ISSUE TITLE
deployment to vercel (and other platforms) fails

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#657]
The `inlang.config.js` file cannot be found because the deployment is done in a different path then on a regular node app.

We probably need to directly import the file instead of using `fs.readFile`, to also bundle it together with the `SvelteKit` application.

We will have the same issues with the resources file, so we somehow also need to reference them.

**Comment by samuelstroschein** [comment]
Are you using an absolute path in fs.readFile?

**Comment by ivanhofer** [comment]
Nope, relative, but the bundled files are in another directory then on the node build. Probably each adapter uses a different path

**Comment by perdix** [comment]
@ivanhofer thanks for working so quickly on the issue! 
But there seems to be still an issue. This time with the languages folder. :/

`PluginSetupError: Failed to setup plugin 'inlang.sdk-js'
    at setupPlugins (file:///var/task/node_modules/@inlang/core/dist/plugin/setupPlugins.js:39:27)
    at async setupConfig (file:///var/task/node_modules/@inlang/core/dist/config/setupConfig.js:17:14)
    at async initState (file:///var/task/.svelte-kit/output/server/chunks/state.js:38:14)
    at async file:///var/task/.svelte-kit/output/server/chunks/wrappers2.js:51:48
    at async respond (file:///var/task/.svelte-kit/output/server/index.js:2491:22)
    at async default (file:///var/task/.svelte-kit/vercel-tmp/index.js:47:3)
    at async Server.handler (/var/task/___vc/__launcher.js:3804:16) {
  [cause]: [Error: ENOENT: no such file or directory, scandir './languages/'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: './languages/'
  }
}
ZodError: [
  {
    "code": "invalid_type",
    "expected": "function",
    "received": "undefined",
    "path": [
      "readResources"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "function",
    "received": "undefined",
    "path": [
      "writeResources"
    ],
    "message": "Required"
  }
]
    at get error [as error] (file:///var/task/node_modules/zod/lib/index.mjs:537:31)
    at ZodObject.parse (file:///var/task/node_modules/zod/lib/index.mjs:636:22)
    at setupConfig (file:///var/task/node_modules/@inlang/core/dist/config/setupConfig.js:18:34)
    at async initState (file:///var/task/.svelte-kit/output/server/chunks/state.js:38:14)
    at async file:///var/task/.svelte-kit/output/server/chunks/wrappers2.js:51:48
    at async respond (file:///var/task/.svelte-kit/output/server/index.js:2491:22)
    at async default (file:///var/task/.svelte-kit/vercel-tmp/index.js:47:3)
    at async Server.handler (/var/task/___vc/__launcher.js:3804:16) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'function',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'function',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'function',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'function',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}`

**Comment by ivanhofer** [comment]
Thanks for letting me know. I'll take a look at this issue tomorrow.

**Comment by ivanhofer** [comment]
@perdix we need to figure out a reliable way to make this wok for all adapters and for all inlang plugins soon.

As a **workaround** you can modify your build script to copy the resources folder into the directory that get's picked up by the adapter:
```json
	"build": "vite build && cp -r [RESOURCE_FOLDER] [SERVERLESS_CWD]",
```


where
 - `[RESOURCE_FOLDER]` is the folder your language files are located. If you haven't done any changes to the initial setup, this will be `./languages`
 - and `[SERVERLESS_CWD]` is
    - for `vercel`: `./.vercel/output/functions/fn.func` if you haven't done any modifications to the `adapter`
       - if you use `split: true`, then you need to copy the folder into all of the generated `fn*.func` folders
       - the option `runtime: 'edge'` is currently not supported
     - for other `adapters` the path will be different. Please let us know what adapter you use and we will add it here.

**Comment by ivanhofer** [comment]
We are early in the development and there are still some rough edges. Feedback from outside helps us to find issues we haven't encountered or to prioritize our development efforts. So thanks to you too!
