### ISSUE TITLE
make `@inlang/sdk-js` work on windows machines

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#658]
I haven't tested it yet, but we have hardcoded unix-paths, so it will probably not work on windows machines.

**Comment by samuelstroschein** [comment]
Given all the problems with deployment now, why is it important that the dev environment works in windows?

**Comment by ivanhofer** [comment]
Because I could faster iterate to make the SDK work on windows machines.

Main question: Why does render `clean` during deployment?

Since this only does not work on Render.com, we could
 - introduce an alias 
	```sh
	shx => ./node_modules/.bin/shx
	```
 - or install `shx` globally
right after `npm install`. Could you try that?
Note: we have the same problem in our github actions: https://github.com/inlang/inlang/blob/main/.github/workflows/publish-ide-extension-plugin-to-npm.yml#L23

**Comment by ivanhofer** [comment]
> Are you referring to "work" as ppl can use the SDK on windows machines or people can develop the SDK on windows machines?

"people can use the SDK", but in order to test it in an easy way I also had to develop it on a windows machine.

**Comment by samuelstroschein** [comment]
@ivanhofer got it. Okay, I'll try to find a solution to the issue!

Closing this one in favor of https://github.com/inlang/inlang/issues/741
