### ISSUE TITLE
[Question] about en.json

### ISSUE THREAD

**Issue by shinokada** [inlang/inlang#664]
## Problem

I use en as ref and add language files, ja.json, de.json, no.json, etc.
Do I still need to make the same words in en.json as well?
Without an en.json file, a page has nothing to display.

**Comment by felixhaeberle** [comment]
@shinokada Hello, nice to see you here! Are you using the inlang sdk-js together with svelte?

@ivanhofer Can you help with that? 🙏

**Comment by ivanhofer** [comment]
@shinokada I'm not sure what you want to achive. Can you please tell give us some more details?

**Comment by shinokada** [comment]
It seems I need to create en.json and add the following content:

```
// ./languages/en.json
{
	"flowbite-svelte": "Flowbite Svelte",
	"home-hero": "Speed up your web development with ",
// more lines
}
```

```
//./languages/ja.json
{
	"flowbite-svelte": "Flowbite Svelte",
	"home-hero":"早く",
// more lines
}
```

It will be helpful to have this info in the docs.

**Comment by ivanhofer** [comment]
It is not required to specify english strings. If you never set english as the language, then you will never need that file.
If you have set `en` as your reference langauge then it is your "fallback" language. So make sure to specify all strings there too.
You can change the `referenceLanguage` in your `inlang.config.js` file to be something different.
