### ISSUE TITLE
improve docs for integrating inlang with svelte

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#670]
## Problem
The docs are already a really great resource, but we also heard that people had minor issues setting things up.
I think there could be a slightly better format to really start with inlang, setup your project from a not-localized repo to a localized one. 

Out of head currently missing:
- Should have Node installed (with version x)
- Should have Svelte installed (with version x)
- In general more steps, like "start your dev server" for real beginners.
- Advertise the editor and the IDE extension in the process.

## Collection of feedback
- What language files do I need? How should they look like?
https://github.com/inlang/inlang/issues/664#issuecomment-1538192801
- Confusing with lang folder creation
https://discord.com/channels/897438559458430986/1083724234142011392/1104715414581297172
- How should my file structure be set up?
https://discord.com/channels/897438559458430986/1083724234142011392/1105097506850877540

## Solution 
A step-by-step tutorial from a blank svelte project to a fully localized one where you literally can't miss a step or go on the wrong direction. This is a great example: https://nextjs.org/learn/basics/create-nextjs-app/setup

**Comment by felixhaeberle** [comment]
@NilsJacobsen I saw you work on the docs, this could be helpful.

**Comment by felixhaeberle** [comment]
@NilsJacobsen Did you see my collection of feedback? 
I would be happy if those could be inlcluded in your improvement of the docs. 
I already saw that you tackled lang folder and file structure (json). 

Can you also add my "out of head missing topics", the most top list above?

**Comment by NilsJacobsen** [comment]
Yes I saw it and linked it. I would welcome your commits on it. I changed the stuff that I knew.

**Comment by shinokada** [comment]
Please add about it creates `en` and `de` file when you run `pnpm dev` as well.

**Comment by felixhaeberle** [comment]
@NilsJacobsen please also look at the feedback we got here: https://github.com/samuelstroschein/inlang-plugin-json/issues/16#issuecomment-1540590238

**Comment by NilsJacobsen** [comment]
But that should only appear in the svelte sdk docs right?

**Comment by ivanhofer** [comment]
yes

**Comment by ivanhofer** [comment]
recommended SvelteKit version is  `>=1.16.3`

**Comment by NilsJacobsen** [comment]
Added the versions, gonna close it now. (feel free to reopen if u disagree)
