### ISSUE TITLE
improve header of website

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#675]
Hey, I like our header, but I think there is room for improvement.

For example:
- we show social icons first, I would put them last like on all other sites.
- add a search bar where people can directly jump to the editor / docs / blog etc.
- remove "open editor". this button is important, but should maybe only be a regular nav entry
- resort navigation order to put Docs first
- maybe add dropdowns to nav items navigate quicker. Especially for Docs -> see screenshot

## Research

<img width="1276" alt="Bildschirmfoto 2023-05-08 um 13 34 07" src="https://user-images.githubusercontent.com/34959078/236815112-5827f0b6-f640-44c6-8084-efbf4aee7d94.png">
<img width="1277" alt="Bildschirmfoto 2023-05-08 um 13 34 41" src="https://user-images.githubusercontent.com/34959078/236815117-f65e1ed9-b351-4b52-8728-7e4793404226.png">
<img width="668" alt="Bildschirmfoto 2023-05-08 um 13 35 29" src="https://user-images.githubusercontent.com/34959078/236815129-5fa3766c-ae0e-4752-a759-758279cdf1d6.png">
<img width="1278" alt="Bildschirmfoto 2023-05-08 um 13 33 08" src="https://user-images.githubusercontent.com/34959078/236815108-c5d89c74-66d9-49c6-aab3-3ba97f1ddffb.png">

**Comment by felixhaeberle** [comment]
@hariFED This already looks great! Thank you! 🎉
Maybe we move the navigation items to the left like Blitz.js ?

And the search would be cool centered with lesswhite, maybe a border only on the same gray background would be nice!

@samuelstroschein 
I changed my mind, let's keep the button in place at the most right side, next to the icons.

@hariFED Do you want to to the changes? Do you work in Figma, can I access the file? 😊

**Comment by felixhaeberle** [comment]
Thank you!! :)

@hariFED @NilsJacobsen Do you want to do an onboarding call with us in the next days? 
https://cal.com/nils-jacobsen/30min

We would be really happy to get some help (also for future designs) – do you want to contribute more to @inlang? 😊

**Comment by tarunsamanta2k20** [comment]
@felixhaeberle Is this issue still open?

**Comment by samuelstroschein** [comment]
Closing because not a priority. If you disagree, please reopen.
