### ISSUE TITLE
purge jsdelivr caches when deploying 

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#678]
jsdelivr offers an enpoint to purge it's cache: https://www.jsdelivr.com/tools/purge

We should call it whenever we make a release to npm. So we need to update out GitHub Actions.

For plugins this will look different as they don't get published to npm. I havent deeply thought about a solution to this problem yet.

**Comment by samuelstroschein** [comment]
> For plugins this will look different as they don't get published to npm. I havent deeply thought about a solution to this problem yet. 

Github Action. We want to provide a github action to automatically create a release on github. The same github action can purge jsdelivr

**Comment by ivanhofer** [comment]
I have tested the cache purging in the last few days and it happens not always instant. sometimes you need to wait a few minutes.  This is an issue when testing, but it will probably not effect production.

**Comment by ivanhofer** [comment]
I don't like jsdelivr. Its cache purging is not reliable and there is nothing we can do about it. I already clreared the cache 10+ times and it still shows an older version and not the latest release.

**Comment by ivanhofer** [comment]
using `2.3.0` instead of `2.3` fixed the problem 👍

How do we make sure that nobody runs into the same issue again? It is so easy to mess this up..

**Comment by samuelstroschein** [comment]
@ivanhofer we should make a github action [that we control and ensure that releases are coorect] and insert it into the plugin template, see https://github.com/inlang/plugin-template/issues/12

**Comment by samuelstroschein** [comment]
Closing as we likely switch to NPM as part of #884
