### ISSUE TITLE
SvelteKit: Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by shinokada** [inlang/inlang#679]
## Problem

When I add `inlangPlugin()` to `vite.config.ts, I get the following errors.

```
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-vercel
✘ [ERROR] Top-level await is not available in the configured target environment ("es2020")

    .svelte-kit/output/server/chunks/state.js:4174:15:
      4174 │ const config = await initConfig();
           ╵                ~~~~~

✘ [ERROR] Top-level await is not available in the configured target environment ("es2020")

    .svelte-kit/output/server/chunks/state.js:4182:0:
      4182 │ await reloadResources();
           ╵ ~~~~~

✘ [ERROR] Could not resolve "node:fs/promises"

    .svelte-kit/output/server/chunks/state.js:1:15:
      1 │ import fs from "node:fs/promises";
        ╵                ~~~~~~~~~~~~~~~~~~

  The package "node:fs/promises" wasn't found on the file system but is built into node. Are you
  trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this
  error.

✘ [ERROR] Could not resolve "node:path"

    .svelte-kit/output/server/chunks/state.js:2:24:
      2 │ import { resolve } from "node:path";
        ╵                         ~~~~~~~~~~~

  The package "node:path" wasn't found on the file system but is built into node. Are you trying
  to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

## What I noticed

- Without this plugin, it builds without problems.
- It works on a browser

## What I have tried

- I used Node v19 and v20
- I tried [vite-plugin-top-level-await](https://github.com/Menci/vite-plugin-top-level-await)
- I change/modify `vite.confilg.ts`
- I changed `build target` in ` vite.config.ts`:

```
build: {
    target: 'esnext' //browsers can handle the latest ES features
  }
```

## Steps to reproduce

```
// clone the repo
git clone git@github.com:shinokada/flowbite-svelte.git
cd flowbite-svelte
// checkout a branch and pull
git checkout languages
git pull
pnpm i
pnpm build
```

### Additional information (screenshots?)

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/147320/236932842-6b4830fc-0543-42f4-bd8c-536a3a013a09.png">

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/147320/236932897-ef3e0c05-8df1-483e-9610-950b6071771a.png">

**Comment by samuelstroschein** [comment]
@shinokada Thank you for the elaborate issue! @ivanhofer is the man for the sdk-js. 

I did a bit of debugging: 

- If you tried to see the build target to `esnext`, seems like the adapter-vercel is overwriting the build target to `es2020`? 
- The sdk-js contains `node:*` dependencies that seem unavailable in vercel's runtime. 

<img width="1152" alt="CleanShot 2023-05-08 at 18 12 04@2x" src="https://user-images.githubusercontent.com/35429197/236949458-d71cc7d6-bbce-4782-ad31-9b87b50814cc.png">

**Comment by samuelstroschein** [comment]
Surprise :D 

https://github.com/inlang/inlang/blob/d2faa15b14585a02880a8324a47d3cdcb6d7d949/source-code/sdk-js/tsup.config.ts#L27-L29

@ivanhofer why do you bundle the sveltekit adapter with tsup instead of tsc? Related https://github.com/inlang/inlang/issues/680

**Comment by shinokada** [comment]
It could be something to do with `import fs from "node:fs/promises";` in `config/config.js`.

**Comment by shinokada** [comment]
If I change `adapter-vercel`, `edge` to `adapter-aut`, then it builds.

From:

```
import { mdsvex } from 'mdsvex';
import mdsvexConfig from './mdsvex.config.js';
import adapter from '@sveltejs/adapter-vercel';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  extensions: ['.svelte', ...mdsvexConfig.extensions],

  // more lines
  preprocess: [
    preprocess({
      postcss: true
    }),
    mdsvex(mdsvexConfig)
  ],
  vitePlugin: {
      inspector: {
        holdMode: true
			}
  },
  kit: {
    adapter: adapter({ runtime: 'edge' })
  }
};

export default config;

```

To:

```
import { mdsvex } from 'mdsvex';
import mdsvexConfig from './mdsvex.config.js';
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  extensions: ['.svelte', ...mdsvexConfig.extensions],

  // more lines
  preprocess: [
    preprocess({
      postcss: true
    }),
    mdsvex(mdsvexConfig)
  ],
  vitePlugin: {
      inspector: {
        holdMode: true
			}
  },
  kit: {
    adapter: adapter()
  }
};

export default config;
```

So I assume it is due to adapter-vercel, edge.

**Comment by shinokada** [comment]
This is a deployment error on Vercel:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/inlang.config.js' imported from /var/task/.svelte-kit/output/server/chunks/state.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:331:11)
    at moduleResolve (node:internal/modules/esm/resolve:994:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)
    at defaultResolve (node:internal/modules/esm/resolve:1202:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: 961b0bc7-cd0a-404f-85a5-5de53fd2d04f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by ivanhofer** [comment]
@shinokada I'm currently working on the vercel issue: https://github.com/inlang/inlang/issues/657

**Comment by ivanhofer** [comment]
We just have released version `0.2.1` which should fix the issue

**Comment by shinokada** [comment]
Thank you for the update. I have tried it with `runtime edge`. Unfortunately, it fails.

svelte.config.js:

```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-vercel';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [
		vitePreprocess(),
		preprocess({
			postcss: true
		})
	],

	kit: {
		adapter: adapter({ runtime: 'edge' }),
	}
};

export default config;
```

**Comment by shinokada** [comment]
And when I deploy to Vercel without `edge` runtime, the deployment fails.

![image](https://github.com/inlang/inlang/assets/147320/28d5363d-c9a5-4fea-800f-01a0b11b52ae)

- [repo](https://github.com/shinokada/i18n-sveltekit-lib)
- [demo](https://i18n-sveltekit-lib.vercel.app/)

It works locally and build but deployment doesn't work.

**Comment by ivanhofer** [comment]
Will take another look at this tomorrow

**Comment by ivanhofer** [comment]
@shinokada I made a PR in your repository that adds a workaround to fix the issue: https://github.com/shinokada/i18n-sveltekit-lib/pull/1

I'll close this in favor of #657 where we will post updates
