### ISSUE TITLE
can't run `npm run dev` because turborepo has issues

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#680]
## Problem

I can't run `npm run dev` because `plugin:dev` is blocking turborepo from proceeding somehow. I tried:

- replacing `npm run-all` with `concurrently`
- mac os and dev container environment

### Expected behavior

`npm run dev` should start a server at localhost:3000.

## Steps to reproduce

1. run `npm run dev` from the root of the monorepo.

### Additional information (screenshots?)

<img width="796" alt="CleanShot 2023-05-08 at 19 32 16@2x" src="https://user-images.githubusercontent.com/35429197/236958823-8d9f6ce1-e610-4ca8-b852-cede1670bace.png">

**Comment by samuelstroschein** [comment]
It might be worth it to remove tsup. 

I had numerous other issues with tsup before. A separation like `ide-extension` and [ide-extension-plugin](https://github.com/inlang/inlang/tree/main/source-code/ide-extension-plugin) might be an easy way to: 

1. avoid different environment-build-related issues, see https://github.com/inlang/inlang/issues/679 which should be solved by separating the inlang plugin from the vite plugin
2. the inlang plugin build system from `plugin-template` can be used, ensuring that the SDK plugin will work
3. the version mismatching is (maybe) improved because inlang won't import from @inlang/sdk-js anymore but `@inlang/sdk-js-plugin` for example.  I am reluctant about the benefit of 3 though.

**Comment by samuelstroschein** [comment]
@ivanhofer given that you started on #690, you agree on separating the inlang plugin from the vite plugin?

**Comment by ivanhofer** [comment]
Yes, it makes things easier and more consistent.
But it is not the problem of this issue. So splitting it had no impact on the `npm run dev` bug.

**Comment by ivanhofer** [comment]
Like I already mentioned in the discord: `@inlang/sdk-js` is not the issue. It just happens to be (mosten times) the last log line that get's written. Delete the `dev` script from any random `package.json` and `npm run dev` will work again. I think `turborepo` is the issue here

**Comment by samuelstroschein** [comment]
I can confirm that removing any `dev` script resolves the issue. What an odd bug. Investigation is pending.

**Comment by araknast** [comment]
Using `turbo run dev --parallel` seems to have fixed it for me. Can anyone verify?
