### ISSUE TITLE
unclear blue dot in pattern editor

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#681]
## Problem

I (users) don't understand what the blue dot is for. 

![CleanShot 2023-05-08 at 19 49 24@2x](https://user-images.githubusercontent.com/35429197/236960658-b891d47e-fd3e-4b49-911b-5836319a8821.png)

## Proposal

1. If the blue dot should indicate that the message contains a placeholder, the placeholder itself is highlighted already -> remove the dot. 

2. If the blue dot expresses something else -> make it clear what the blue dot expresses.

**Comment by NilsJacobsen** [comment]
Absolutely correct that you are confused. This is a bug: Messages with placeholder at the end used to produce a miss match through the parsing in the frontend. This was due to an issue in the plugin. It is already fixed and is waiting for jsdelivr to be released. Gonna purge it now.

**Comment by NilsJacobsen** [comment]
Can you try it again now?

**Comment by felixhaeberle** [comment]
Maybe offtopic here but that confuses me, plugins should never influence the behavior of the editor in any other way than spilling out a valid AST right? Just to understand this: How do we monitor that the functionality in the editor is always in sync with our plugin system / like inlang-plugin-yaml which doesnt support placeholder yet? Is this all like bullet proof modular?

**Comment by NilsJacobsen** [comment]
As long as you return a valid ast that should be fine. But handling placeholders need to be handled in your plugin.
