### ISSUE TITLE
toJson and fromJson are broken

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#683]
## Problem

No test in rpc/generateConfig.test.ts pass. Example: 

https://github.com/inlang/inlang/blob/3550fcbe40814cae69d26e2cfcd5d5866a8819d1/source-code/rpc/src/functions/generateConfigFile.test.ts#L7-L27

```bash

DOMException [InvalidCharacterError]: Invalid character
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:520:10)
    at atob (node:buffer:1349:13)
    at Module.fromJson (file:///Users/samuel/Documents/GitHub.nosync/inlang/source-code-git/fs/dist/utilities/fromJson.js:13:34)
```

Changing the test case to use `writeFile` directly yields the same error.

```ts

			await fs.writeFile("/locales/en.json", JSON.stringify({ hello: "hello from en" }))
			await fs.writeFile("/locales/fr.json", JSON.stringify({ hello: "bonjour via fr" }))
			await fs.writeFile("/locales/de.json", JSON.stringify({ hello: "hallo von de" }))
			await fs.writeFile("/locales/utils.js", JSON.stringify("jibberish"))
			await fs.writeFile("/main.js", "export function hello() { return 'hello' }")

```

## Reproduction

Add the following test case to `fromJson.test.ts`:

```ts


it("should be able to import files from JSON encoded as string", async () => {
	const fs = createMemoryFs()

	await fromJson({
		fs,
		resolveFrom: "/",
		json: {
			"file1.txt": "content1",
			"file2.js": "content2",
			"node_modules/file3.js": "content3",
			"node_modules/file4.json": `{ "hello": "hello from en" }`,
		},
	})
	expect(await fs.readFile("/file1.txt", { encoding: "utf-8" })).toEqual("content1")
	expect(await fs.readFile("/file2.js", { encoding: "utf-8" })).toEqual("content2")
	expect(await fs.readFile("/node_modules/file3.js", { encoding: "utf-8" })).toEqual("content3")
	expect(await fs.readFile("/node_modules/file4.json", { encoding: "utf-8" })).toEqual(
		`{ "hello": "hello from en" }`,
	)
})
```

## Additional information

- I found https://www.npmjs.com/package/js-base64 which could be helpful. I already played around with it, it doesn't throw when a json string is encountered.
- files can only be written as string, yet `fromJson` reads a file with `{ encoding: "binary" }`. I don't understand how this should work. 
- this issue is blocking https://github.com/inlang/inlang/issues/661

**Comment by araknast** [comment]
Content passed to 'fromJson' must be base64 encoded see: https://github.com/inlang/inlang/pull/600#discussion_r1181118476 

So we would need to do
```
 		const filesystemAsJson = { 
 			"locales/en.json": btoa(JSON.stringify({ hello: "hello from en" })), 
 			"locales/fr.json": btoa(JSON.stringify({ hello: "bonjour via fr" })), 
 			"locales/de.json": btoa(JSON.stringify({ hello: "hallo von de" })), 
 			"locales/utils.js": btoa(JSON.stringify("jibberish")), 
 			"main.js": btoa("export function hello() { return 'hello' }"), 
 		} 
```

Considering how easily of a mistake this would be to make, we should probably catch and rethrow a more helpful error message here. We also need to make it _**very clear**_ in the dev docs that 'fromJson' only accepts base64 encoded file contents. Passing a string will result in an error, or even worse, work in unexpected ways if the string happens to be valid base64.

**Comment by araknast** [comment]
> Will throw because btoa can't handle jsons. An "invalid character" error is thrown.
Hmm, seems to work for me. i get
```
 > btoa(JSON.stringify({ hello: "hello from en" }) 
eyJoZWxsbyI6ImhlbGxvIGZyb20gZW4ifQ==
```

There should be no reason `btoa` would throw an error with a JSON string.

**Comment by samuelstroschein** [comment]
Follow up: `btoa` and `atoa` have been replaced by https://www.npmjs.com/package/js-base64 due to #811
