### ISSUE TITLE
make `$import` typesafe

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#689]
We have found a way to make `$import` typesafe.🎉

![image](https://github.com/inlang/inlang/assets/21335119/6053db9e-0e79-4d1a-9c27-4e1c316a56f2)

1. Given the following import
	```ts
	env.$import('https://cdn.jsdelivr.net/npm/@inlang/sdk-js@0.2/dist/plugin/index.js')
	```
2. and the type definition for it
	```ts
	// this type will be located in it's own file inside `node_modules`
	type ImportMap = {
		'https://cdn.jsdelivr.net/npm/@inlang/sdk-js@0.2/dist/plugin/index.js': typeof import('./4879348743.js')
	}

	//@ts-ignore
	const $import = <T extends `https://${string}`>(s: T): ImportMap[T] => // implementation
	```
3. we need to parse the `inlang.config.js` file for `$import` statements
4. extract its url
5. add it to the `ImportMap` entries where the `key` is the url and the value is `typeof import('./{{hash(url)}}.js')`
6. replace the `.js` at the end of the url with `.d.ts`
7. download that file
8. store the text result in a `./{{hash(url)}}.js` file
9. if the url is not found than `any` should be chosen as the value of the map entry

The VS Code extension is reponsible for executing this process

This also means that we need to update all plugins and the plugin template to also generate `.d.ts` files.
We will probably also need to use https://api-extractor.com/ in order to bundle all declaration files into a single file.

**Comment by samuelstroschein** [comment]
Closing as "collected in https://github.com/orgs/inlang/projects/22 which will be worked on as part of an week initiative; closing issues with no immediate priority"
