### ISSUE TITLE
i18n next plugin

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#696]
## Problem

Multiple repositories use i18n next and ask for plugins.

https://github.com/LAION-AI/Open-Assistant/issues/3077
https://github.com/calcom/cal.com
https://github.com/ToolJet/ToolJet

## Proposal

Develop an inlang-plugin-i18nnext that automatically configures the editor and ide extension. 

```ts
// filename: inlang.config.js

export async function defineConfig(env) {

  const { default: i18nNextPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/gh/inlang/plugin-i18n-next@1/dist/index.js"
  );

  return {
    referenceLanguage: "en",
    plugins: [
      i18nNextPlugin()
    ]
  };
}

```

**Comment by felixhaeberle** [comment]
@samuelstroschein I'm on it! 
Let's see how far we can get with the current state of inlang. 
Development happens here: https://github.com/inlang/plugin-i18next

**Comment by samuelstroschein** [comment]
Completed. The plugin can be found at https://github.com/inlang/plugin-i18next
