### ISSUE TITLE
Multiple exports with the same name `handle`

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#705]
The issue occurs when someone uses the `sequence` helper function.

Example repo: https://github.com/jmandzik/inlang-repro/

Code:
```ts
import { sequence } from "@sveltejs/kit/hooks";

const seq1 = async ({ event, resolve }) => {
  return resolve(event);
};

export const handle = sequence(seq1);
```

We need to improve the AST detection.

**Comment by benjaminpreiss** [comment]
Just to clarify, how should the transform work in this case?

Before:
```js
import { sequence } from "@sveltejs/kit/hooks";

const seq1 = async ({ event, resolve }) => {
  return resolve(event);
};

export const handle = sequence(seq1);
```

After ?

**Comment by ivanhofer** [comment]
After:
```ts
import { sequence } from "@sveltejs/kit/hooks";
import { initHandleWrapper } from "@inlang/sdk-js/adapter-sveltekit/server";

const seq1 = async ({ event, resolve }) => {
  return resolve(event);
};

export const handle = initHandleWrapper({
	inlangConfigModule: import(\\"../inlang.config.js\\"),
	getLanguage: () => undefined,
}).wrap(sequence(seq1));
```

**Comment by benjaminpreiss** [comment]
So, then, just to add some more complexity here 🥲, how do we handle the imports from `@inlang/sdk-js`? https://github.com/inlang/inlang/issues/694

**Comment by ivanhofer** [comment]
like in `load` the wrapper passes `i` and other variables as the second argument.

In all other cases, we can do `getRuntimeFromLocals(event.locals).i`, but it will probably be harder detect, right?

If not easily possible we can also just throw an error saying the user has to do it manually.

**Comment by benjaminpreiss** [comment]
... But how? I am not sure if `sequence` allows for more than one parameter?

```js
import { sequence } from "@sveltejs/kit/hooks";
import { initHandleWrapper } from "@inlang/sdk-js/adapter-sveltekit/server";

const seq1 = async ({ event, resolve }, {i, language}) => {
  return resolve(event);
};

export const handle = initHandleWrapper({
	inlangConfigModule: import(\\"../inlang.config.js\\"),
	getLanguage: () => undefined,
}).wrap(({ event, resolve }, {i, language}) => sequence(({ event, resolve }) => seq1({ event, resolve }, {i, language})));
```

**Comment by ivanhofer** [comment]
No it doesn't, thats why we need to use `getRuntimeFromLocals(event.locals).i`

**Comment by benjaminpreiss** [comment]
Okey, so I propose the following rule:

#### Inline Arrow functions
```js
import {i} from "@inlang/sdk-js"
export const handle = () => {
    console.log(i)
}
// Becomes
export const handle = initHandleWrapper(/*...*/).wrap(({/*...*/}, {i, language}) => {
    console.log(i)
})
```

#### Inline Regular functions
```js
import {i} from "@inlang/sdk-js"
export function handle() {
    console.log(i)
}
// Becomes
export const handle = initHandleWrapper(/*...*/).wrap(function handle({/*...*/}, {i, language}) {
    console.log(i)
})
```

#### All other cases (presumably function definitions else where)
```js
import {i} from "@inlang/sdk-js"
function hndl() {
    console.log(i)
}
export const handle = hndl
```
// Becomes - we can just apply the normal *.js transforms (server side)
```js
import {getRuntimeFromLocals} from "@inlang/sdk-js/adapter-sveltekit/server"
function hndl() {
    console.log(getRuntimeFromLocals(event.locals).i)
}
export const handle = initHandleWrapper(/*...*/).wrap(hndl))
```

As the handle export has to be a function, we don't have to consider cases where the assignment would be a variable

**Comment by benjaminpreiss** [comment]
### Special cases / open questions

#### Imported function case
It might happen that a function is imported from elsewhere and then declared as the `handle` export.
Before:
```js
import {handle as hndl} from "../some/path.js"
export const handle = hndl
```

At the time when we resolve `../some/path.js` we have no way of knowing how we should transform the defined handle function within (as we don't know the context). Also, in the file where we export `handle` for sveltekit, the `hndl` definition is out of reach for transforming it.

**Comment by benjaminpreiss** [comment]
@ivanhofer Is there a performance reason for which we shouldn't just replace `i` with `getRuntimeFromLocals().i` everywhere?

**Comment by ivanhofer** [comment]
We can probably ignore the performance for this. So use `getRuntimeFromLocals(event.locals)` everywhere.

But we need to keep the `import { i } from '@inlang/sdk-js'` everywhere. Then we can throw a meaningful error message if `i` get's accessed somewhere where we didn't replace it

**Comment by benjaminpreiss** [comment]
Decision after a private discussion with @ivanhofer:

### Inline Arrow functions
```js
import {i} from "@inlang/sdk-js"
export const handle = () => {
    console.log(i)
}
```
Becomes
```js
export const handle = initHandleWrapper(/*...*/).wrap(({event, resolve}) => {
    console.log(getRuntimeFromLocals(event.locals).i)
})
```

### Inline Regular functions
```js
import {i} from "@inlang/sdk-js"
export function handle() {
    console.log(i)
}
```
Becomes
```js
export const handle = initHandleWrapper(/*...*/).wrap(function handle({event, resolve}) {
    console.log(getRuntimeFromLocals(event.locals).i)
})
```

### All other cases (presumably function definitions else where)
```js
import {i} from "@inlang/sdk-js"
function hndl() {
    console.log(i)
}
export const handle = hndl
```
Becomes - we can just apply the normal *.js transforms (server side)
```js
import {getRuntimeFromLocals} from "@inlang/sdk-js/adapter-sveltekit/server"
function hndl({event, resolve}) {
    console.log(getRuntimeFromLocals(event.locals).i)
}
export const handle = initHandleWrapper(/*...*/).wrap(hndl)
```

**Comment by benjaminpreiss** [comment]
AST transform strategy:

1. Find all occurrences of imports from `@inlang/sdk-js`
2. Keep the node reference to the identifier in memory as `identifier`
3. Find the next parent (arrow) function declaration (just climb up the AST)
4. If there is already `event` in the first fn parameter, save the alias as `eventAlias`. Otherwise, add `event` to fn parameter and save the alias.
5. Prefix the node references with `getRuntimeFromLocals(<eventAlias>.locals).`.

All this, while KEEPING the imports from `@inlang/sdk-js`

**Comment by ivanhofer** [comment]
This example currently also does not get detected correctly:
```ts
import type {LayoutLoad} from "./$types";

export const trailingSlash = "always";

export const load = (async ({fetch, data}) => {
    const res = await fetch('http://localhost:1337/api/menu/?populate[0]=menu_item.item.icon');
    const menuData = await res.json();

    return {
        menuData
    };
}) satisfies LayoutLoad;
```

**Comment by jmandzik** [comment]
Thanks for taking on this work!  Up thread, I saw a comment about `sequence` not taking more than one parameter.  Just a heads up,[ it definitely does ](https://kit.svelte.dev/docs/modules#sveltejs-kit-hooks-sequence) and its our approach to middleware pattern.  I hope the outcome of this work includes supporting multiple handlers as inputs to sequence, while still achieving inlangs wrapping.

**Comment by ivanhofer** [comment]
> Up thread, I saw a comment about `sequence` not taking more than one parameter

We were talking about something different, but thanks!
Currently the wrapper calls `handle` like this: `handle({ request, event}, inlangRuntime)` where we pass the inlang functionality as a second parameter sowe can easily access it inside handle. 

> I hope the outcome of this work includes supporting multiple handlers as inputs to sequence, while still achieving inlangs wrapping.

It will certainly support it, but we are thinking that developers would probably need to manually call a function if they want to use the inlang functionality in one of the `handle` functions passed to `sequence`.

**Comment by benjaminpreiss** [comment]
- [ ] Make sure that declaration chain only contains `sequence(...)` and no other function calls. Throw error on this code: `export const handle = otherfunction()`
