### ISSUE TITLE
Remove `fs` as a dependency of the SvelteKit plugin

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#707]
`SvelteKit` offers multiple `adapters` which are not node-based.
e.g. `cloudflare` or `vercel` with the `edge` setting

https://vercel.com/guides/how-can-i-improve-serverless-function-lambda-cold-start-performance-on-vercel#faster-performance-with-vercel-edge-functions

We need to remove the `fs` dependency in `source-code/sdk-js/src/config/config.ts` in order to make the sdk work on those platforms.

But some inlang plugins need `fs` to be able to read resource files from disk.

What we can do is per default `prerender` all resources during build. Then during runtime we don't need to load resources from disk, because they will be already stored as static assets. This would also fix #657.

We could introduce a new option to the `sdk`:

```js
resources: {
   cache: 'forever' | number /* in seconds */
}
```

If plugins don't rely on `fs` but instead read the resources from a DB, they can set the `cache` option to `600` to refetch the resources after 10 minutes.

**Comment by ivanhofer** [comment]
@samuelstroschein what is your opinion

**Comment by samuelstroschein** [comment]
@ivanhofer does vercel and cloudflare workers have their own fs? 

This issue is the same issue we are facing with fs in the browser. @araknast is working on a cross environment fs with `@inlang-git/fs`. That fs could have implementations for vercel edge and cloudflare if those environments have their own fs APIs.

**Comment by ivanhofer** [comment]
No, cloudflare workers and vercel's edge network don't have any solution to access files.

How will this work in the browser? Does it use the [`FileSystem`-api](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem)?

**Comment by samuelstroschein** [comment]
> How will this work in the browser? Does it use the [FileSystem-api](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem)? 

The filesystem can have different backends. What @araknast is doing right now is a minimal filesystem API that enables git operations. That minimal filesystem API can have different implementations like `node:fs/promises` or our own `createMemoryFs`, `createLocalStorageFs` etc. The filesystem API is a strict subset of `node:fs/promises` to ease DX when working in a node environment (devs can just use node:fs/promises).


> What we can do is per default prerender all resources during build. Then during runtime we don't need to load resources from disk, because they will be already stored as static assets. This would also fix https://github.com/inlang/inlang/issues/657. 

Sounds like the way to go then.

**Comment by ivanhofer** [comment]
> The filesystem can have different backends

Ok but then this is nothing for the `sdk`

> Sounds like the way to go then.

Preprocess everything! 🎉
