### ISSUE TITLE
Add branch support in the editor

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#712]
Hey folks, I wanted to add a feature request, that I noted down in the discussion with coleap.com

They found inlang and set it up, their biggest issue atm is that they need a two step deployment with inlang. 
1. Push/Merge code
2. Add translations for it

We discussed that topic several times, but to make it a open discussion I decided to open that issue.

**Suggestion:**
Add a way to change branches in the editor. 

**Goal:**
Decide when we want to ship this feature?
What kind of difficulties are on the way?

**Comment by samuelstroschein** [comment]
Let's discuss this in https://github.com/inlang/inlang/discussions/166 and use issues as immediate todo tasks. if you agree, please close this issue. If you disagree, keep this issue open.

**Comment by samuelstroschein** [comment]
Closing as "using #166" as discussion panel.
