### ISSUE TITLE
add machine translate to ide extension

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#721]
## Problem

Currently, our IDE extension does not provide the ability to machine translate code or text directly within the editor. This can be a hindrance to developers who need to work with code or text written in a language they are not familiar with.

## Solution 

 As a solution, we propose adding a machine translation feature to the IDE extension.

**Comment by felixhaeberle** [comment]
@samuelstroschein we heard a lot of people requesting this, like osmosis and others. we have to think on what is the best strategy and UX to approach this.

**Comment by samuelstroschein** [comment]
@felixhaeberle Osmosis is requesting this for the CLI as part of CI/CD. Not for the IDE extension. 

My backlog has the CLI machine translate command as a task.

**Comment by openscript** [comment]
@felixhaeberle:

Other tools offer this feature inside a context tool tip:

![image](https://github.com/inlang/inlang/assets/1105080/5244569a-aa7b-4037-a4e5-ba5c3b2632db)

I think this is the most simple and convenient way to provide this feature. 

Question:

-  Is there an API which the editor and ide extension can share, so the integration of translation services can be shared?

Estimate: 6-8h

**Comment by samuelstroschein** [comment]
(Replying because I get all the notifications haha)

> @openscript Is there an API which the editor and ide extension can share, so the integration of translation services can be shared?

Yes, https://github.com/inlang/inlang/tree/main/source-code/rpc. 

> I think this is the most simple and convenient way to provide this feature.

Is this feature worth the effort/important when the CLI can be run with `inlang machine translate`? 

Machine translations in the ide extension directly seems like a "nice to have" but not crucial feature. @openscript do you agree?

**Comment by samuelstroschein** [comment]
The weekly milestone hasn't been hit, indicating that this issue has low priority. 

Hence, I ask again. Is this feature important? Seems like the CLI can be used.

**Comment by felixhaeberle** [comment]
Not important right now, can be closed as not planned. 

### 2 available options as of now:
Editor: Machine translate button
CLI: `npx @inlang/cli machine translate` can be used in the build pipeline to avoid missing translations
