### ISSUE TITLE
add lints to ide extension

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#724]
## Problem

The IDE extension currently does not display any lints, which could be useful to identify and correct code issues quickly. The lack of this feature in the IDE extension is causing developers to have to switch between the editor and the IDE to check for lints, which is an unnecessary interruption to their workflow.

## Solution

Display lints in the ide extension under "Problems".

The addition of this feature will make it much easier for developers to identify and correct code issues without having to switch between the editor and the IDE, which will save time and improve the overall development experience.

<img width="549" alt="Bildschirmfoto 2023-05-11 um 11 58 40" src="https://github.com/inlang/inlang/assets/34959078/593a7705-0456-4537-8ea0-d0309e3d599e">

**Comment by felixhaeberle** [comment]
@samuelstroschein we already have this functionality in the editor called lints, when users have the standard lint plugin or any other lints defined, the could be displayed under the "problems" tab for example. what do you think about that?

**Comment by samuelstroschein** [comment]
@felixhaeberle sounds good. I would prob let the community vote on this one before we start to implement things.

**Comment by felixhaeberle** [comment]
@samuelstroschein I'm against voting for now. We do not have a big community right now and this could lead to the chicken egg problem where we do not do implementations because its not requested because users aren't using our solution because the features aren't there. 

Can I hop on this task and do it? 
This would perfectly align with also introduce lints in the CLI.

**Comment by felixhaeberle** [comment]
Short update: After the lints got implemented successfully into the CLI (yay 🎉 #862), we also want to continue here and support lints in the VS Code extension.

**Comment by felixhaeberle** [comment]
This will be part of the BETA release and is worked on this week. 
As @openscript is currently working on #960 and has limited resources this week, I will work on this.

**Comment by felixhaeberle** [comment]
Ergh, this got moved two times already. Will be done asap, no excuses anymore. 😄

**Comment by felixhaeberle** [comment]
closed by https://github.com/inlang/inlang/pull/1051
