### ISSUE TITLE
add link to web editor from within ide extension

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#725]
## Problem
Users of our IDE extension do not have a straightforward way to access our web editor from within the extension. This can be frustrating for users who prefer to use the web editor for certain tasks.

## Solution
Add a link to our web editor from within the IDE extension so that users can easily access it without having to navigate to our website manually.

## Technical Steps:

🎨 Design and implement a minimal user interface for the link to the web editor. This could be a button or a menu option within the IDE extension.

👨‍💻 Write code to handle the opening of the web editor in a new browser tab when the user clicks on the link.

🧪 Test the link thoroughly to ensure that it works correctly and that the web editor is displayed as expected.

🚀 Publish the updated version of the IDE extension to Visual Studio Marketplace and document the new feature in the release notes.

**Comment by felixhaeberle** [comment]
@samuelstroschein this should be pretty easy right? we just read from the .git folder the repo url and create a "inlang editor url" with the correct pattern and the message id. or are you against reading from the .git folder?

**Comment by samuelstroschein** [comment]
@felixhaeberle Yep, seems like it.

**Comment by openscript** [comment]
@felixhaeberle:
If it's possible to create and editor action for the code editor, I assume it's the right place to implement it:

![image](https://github.com/inlang/inlang/assets/1105080/a9f3f881-42c0-45b0-aed9-731cc0191c8b)

Estimate: 2h

**Comment by felixhaeberle** [comment]
@openscript I would suggest it in the context tooltip you proposed via DM too. 👍

**Comment by openscript** [comment]
@samuelstroschein @felixhaeberle agree, but this creates a dependency of this task to the context tooltip.

**Comment by felixhaeberle** [comment]
Related to context tooltip #960.

**Comment by samuelstroschein** [comment]
The weekly milestone is long passed. When is this issue planned?

**Comment by felixhaeberle** [comment]
This is now in the scope of #960 and can be closed.
