### ISSUE TITLE
fix deployment cross env permission denied issue

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#741]
## Problem

https://github.com/inlang/inlang/issues/658 introduced a regression bug that prevents deploying to render.

**Comment by ivanhofer** [comment]
we could pass arguments instead of setting env variables and read it with `process.argv`

**Comment by samuelstroschein** [comment]
@ivanhofer Hmm. The clean command makes issues now again (if node modules don't exist before running clean).

We could try to implement one workaround after another to make the dev environment Windows-compatible or drop Windows support [which makes testing on windows harder]. 

I'll investigate further but if we can drop windows support, our lives should be easier now and in the future

**Comment by ivanhofer** [comment]
what if we just run `rm ./node_modules/*` instead of `npm run clean`?

**Comment by ivanhofer** [comment]
I meant on render.com, the only place where it does not work currently.

**Comment by samuelstroschein** [comment]
The node modules are not the root problem of caching problems on render. The dist modules are. The bug was related to the markdown files being bundled via vite and not updating when editing them. 

Thus, the render caching problem will pop up again if `npm run clean` is not ran in (some) modules.

**Comment by ivanhofer** [comment]
then run `rm -rf **/node_modules **/dist`

**Comment by samuelstroschein** [comment]
Will do that. On that note, developers will run into `npm run clean` throwing because `shx` is not defined. Running `npm i` beforehand kinda defeats the purpose. Installing only one package is not possible with NPM

**Comment by ivanhofer** [comment]
wha should anyone want to clean if nocthing is there to clean?

**Comment by samuelstroschein** [comment]
THe command should run through, not fail with "shx package doesn't exist". Anyhow, let me fix the build. Seems like I am getting closer

**Comment by samuelstroschein** [comment]
:cry: 

<img width="752" alt="CleanShot 2023-05-12 at 15 24 17@2x" src="https://github.com/inlang/inlang/assets/35429197/f7d5204f-9d1c-4234-81c9-50cef1d06cf5">

**Comment by samuelstroschein** [comment]
Running `npm run clean` and manually deleting the remaining files in `node_modules` fixed the issue on my machine. 

This windows compatibility will hunt us.

**Comment by samuelstroschein** [comment]
Ergh. Had more deployment issues. Fixed them now too but took me another hour. Super unproductive day. 

I think nice to have changes that introduce dependencies are usually not worth it. If the sdk-js can be tested on windows machines now fine (what for actually? the sdk-js runs in node?). But, if more windows related issues pop up, we should probably remove windows dev support again.

**Comment by samuelstroschein** [comment]
@ivanhofer Can you elaborate on why Windows support is required for the dev environment? 

Testing the SDK-js should be environment independent as the sdk-js runs in node / what is windows testing support needed for? 

(We are facing hours of work because of debugging windows related stuff)

**Comment by ivanhofer** [comment]
If it causes troubles, then let's get rid of it. I'll figure out another way to test it on windows without needing to publish a new version to npm.

**Comment by samuelstroschein** [comment]
PR for removal will follow

**Comment by felixhaeberle** [comment]
`cli`, `ide-extension-plugin` and `sdk-js-plugin` are not deleting `node_modules` when running `npm run clean` because of missing script I guess.
