### ISSUE TITLE
`NodeishFilesystem` `rm` needs `force` option

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#744]
## Problem

The tests in https://github.com/inlang/inlang/pull/743 are failing because `rmdir` is used on a directory that contains files: 

https://github.com/inlang/inlang/blob/6b8f7c65309b8c9645e68a27c85cda1b94fdc70c/source-code-git/fs/src/utilities/fromJson.test.ts#L10-L13

Using `rmdir(path, { recursive: true })` is not an option because `recursive: true` is deprecated and (correctly) not exposed by `NodeishFilesystem`. [Node recommends](https://nodejs.org/api/fs.html#fspromisesrmdirpath-options) using `rm(path, { recursive: true, force: true })` instead: 

<img width="1145" alt="CleanShot 2023-05-12 at 17 02 50@2x" src="https://github.com/inlang/inlang/assets/35429197/0f6764f3-c746-4e8e-9aff-e931e4a29ef0">

## Proposal 

`NodeishFilesystem.rm` needs the force option.

**Comment by samuelstroschein** [comment]
PS man what an ugly API with way too many gotchas. But, let's get NodeishFilesystem in check first. Then, in a year or so introduce a sane `Filesystem` API.

**Comment by araknast** [comment]
As long as the directory is guaranteed to exist, you should be able to call `await fs.rm(rootTempDir, { recursive: true })` to accomplish the desired behavior. If there is a possibility the directory does not exist you should be able to do something like `await fs.rm(...).catch( e => e.code !== 'ENOENT' && throw e)` which replicates the behavior of the `force` option.

**Comment by samuelstroschein** [comment]
@araknast Yep, `await fs.rm(rootTempDir, { recursive: true })` works! Again, what an ugly API. Eventually, we should have the `force` option. But, closing this issue until then.
