### ISSUE TITLE
reduce required permissions for github auth (don't ask for private repos)

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#745]
## Problem

The OAuth flow requires permissions to all repositories, including private repositories. 

The oauth implementation is simple at the moment. To avoid additional logic flows of "user has given access to this repo", the implementation naively requests permissions to all repositories. Users are reporting the desire to grant access on a finer level.

## Proposal

Implement a "per repository" auth flow.  

## Additional information

Upvote this issue if you want this feature. This issue is not a priority at the moment. While a more fine-grained auth flow is nice to have, other features of the editor bring more value to a wider audience.

**Comment by felixhaeberle** [comment]
@NilsJacobsen @NiklasBuchfink This could be a potential drop-off of users because users don't want to open up their complete Github repository. This could be fixed during the website makeover.

**Comment by NilsJacobsen** [comment]
This is not related to website makeover it would have been related to the editor. 

Why not using a checkbox and call for access of public/ public and private repos?

**Comment by felixhaeberle** [comment]
Yes, just wanted to bring this up as an idea what causes the drop-off of users be less significant.

**Comment by samuelstroschein** [comment]
> Why not using a checkbox and call for access of public/ public and private repos? 

> **My reply from above:** To avoid additional logic flows of "user has given access to this repo", the implementation naively requests permissions to all repositories. 

The auth implementation becomes more complex because users need to re-authorize if they want to grant additional repositories permissions. 

> Yes, just wanted to bring this up as an idea what causes the drop-off of users be less significant.

@felixhaeberle Good point. We could take a look at the drop-off between "clicked on sign in" and actual sign in.

**Comment by samuelstroschein** [comment]
Closing as no priority.
