### ISSUE TITLE
example repo crashes editor

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#749]
https://inlang.com/editor/github.com/allinurl/goaccess

Message: "The reference language "en" must be included in the list of languages"

**Comment by ivanhofer** [comment]
https://inlang.com/editor/github.com/knadh/listmonk

This one crashes with a different error message: "The message with id "globals.months.10" does not match for the resource with languageTag.name "ca"."

**Comment by samuelstroschein** [comment]
1. Filed a bug in the po plugin https://github.com/jannesblobel/inlang-plugin-po/issues/5
2. Filed a bug in the json plugin https://github.com/samuelstroschein/inlang-plugin-json/issues/21

**Comment by samuelstroschein** [comment]
PS Glad that we are using `parseConfig` now. I bet there are more hidden issues that become visible now.
