### ISSUE TITLE
CLI `inlang machine translate` command

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#760]
## Context

Users are requesting a `machine translate` command for the CLI that can be embedded in CI/CD. 

## Proposal 

Have a `machine translate` command that: 

1. calls `readResources` to get all resources
2. iterate over the resources and finds all messages that are missing (I propose to not rely on the missingMessages rule because not every project is 100% certain to use the missingMessages rule). 
3. machine translates all missing translations
4. calls `writeResources` to persist updated resources   

## Blocked by

- [x] #76 
- [x] #777 

## Tasks after complete

- [ ] #782

**Comment by jonator** [comment]
@samuelstroschein will be waiting for a PR

**Comment by samuelstroschein** [comment]
@jonator Yes, for now at least via our API keys (no need for you to set up anything)

**Comment by jonator** [comment]
Tagging @maxmillington

**Comment by jonator** [comment]
We also have a chaggpt API key we can pass instead of a google API key already.

Looking great @samuelstroschein ! Keep me posted

This will be me for now:
<img width="855" alt="Screenshot 2023-05-16 at 3 45 28 PM" src="https://github.com/inlang/inlang/assets/4606373/1d634f7b-bf8e-4013-a20f-f7f94030c1fb">

**Comment by felixhaeberle** [comment]
@samuelstroschein Is there a mode needed where we "machine translate --hard" translate all messages, not respecting already translated keys? Could be with an additional prompt.

**Comment by samuelstroschein** [comment]
@felixhaeberle please no `--hard` flag :D Replacing human reviewed (hopefully) translations with machine translation = bad.

**Comment by felixhaeberle** [comment]
@samuelstroschein unfortunately, we have to fix the env setup in prod #777 😅

**Comment by samuelstroschein** [comment]
Fixed #777. @jonator PR is on my todo list for tomorrow in #782
