### ISSUE TITLE
extract machine translate from editor into an RPC

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#761]
## Problem 

The machine translate part in the editor is bound to the editor via `telefunc` and can therefore not be used by the CLI (or IDE extension https://github.com/inlang/inlang/issues/721)

## Proposal 

- Move machine translation into an RPC and thereby enable other apps to use machine translations. 
- Don't care about auth for now. We do that once we hit a budget limit :D

**Comment by felixhaeberle** [comment]
closing this in favor of #518
