### ISSUE TITLE
Npx config init commands fails on windows

### ISSUE THREAD

**Issue by BigDog1400** [inlang/inlang#763]
## Problem
I am trying to run the npx command to initialize the config for my project and it is throwing and error in the cli always.
### Expected behavior
The cli should create the config file without problems.
## Steps to reproduce

1. Open the console, paste `npx @inlang/cli config init`
2. Press enter, and should show the error

### Additional information (screenshots?)
![image](https://github.com/inlang/inlang/assets/63280663/f711e5de-c096-4f41-bc61-983896a430e2)
This is the current repository where i am trying to run the command. https://github.com/BigDog1400/pana
My OS is Windows 11, and i have nodejs v18.3.0

**Comment by samuelstroschein** [comment]
Should be fixed by https://github.com/inlang/inlang/commit/4fc27086dc605e417c1e3cddfca68910a35be362. Feel free to re-open if not.
