### ISSUE TITLE
Get rid of login confirmation screen

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#764]
If a user logs in into the editor, he will be greeted by this screen afterwards:

![image](https://github.com/inlang/inlang/assets/21335119/e2cb30dc-2e2f-43e5-bf4b-a3c46a190b7e)

I see 2 issues here:
1. it says "You can close this window".
   If a user does so, he will close the tab where he previously opened the editor. So he will need to open it up again.
2. Why does this screen even exist?
   It is an unecessary step to go back to the editor. Just redirect directly and show a notification on the bottom right instead.

**Comment by samuelstroschein** [comment]
The login flow doesn't store the previous site the users visited. Thus, upon redirecting from GitHub, the simplest solution was to nudge the user to close the window.

**Comment by ivanhofer** [comment]
If I click "Return to app" I get back to the page I was before, so the state is already here. So the computer just has to click that button for me automatically and I'm happy :)

**Comment by samuelstroschein** [comment]
> If I click "Return to app" I get back to the page I was before, so the state is already here. So the computer just has to click that button for me automatically and I'm happy :)

I remember looking into automatically clicking the button for the user but encountered some obstacles. Don't remember what it was though.

**Comment by ivanhofer** [comment]
Ah I somehow thought that it opened the link in the same tab. But it does so in a new tab.
What if we instead open the login in the same tab and afterwards just navigate back? Or store the redirect-to url in localStorage? Usually you can also pass a state parameter to the auth flow, which could also be used to store the url information.

**Comment by samuelstroschein** [comment]
> What if we instead open the login in the same tab and afterwards just navigate back?  

Oauth flows require a new tab to be opened. 

> Or store the redirect-to url in localStorage? Usually you can also pass a state parameter to the auth flow, which could also be used to store the url information. 

You see now things get complicated :D I would leave this issue as is and eventually when the auth is reworked someone should look into this. The UX improvement is minimal.
