### ISSUE TITLE
Move @inlang/core into dependencies 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#776]
## Problem 

_From Discord https://discord.com/channels/897438559458430986/1070750156644962434/1108312554532519967_:

Edit: Resolved, I forgot to install `@inlang/core`

Followed the svelte submit and installed inlang, got these errors instantly after configuring the project as per the video instructions:

```bash
Failed to load url @inlang/core/config (resolved id: @inlang/core/config). Does the file exist?
Failed to load url @inlang/core/environment (resolved id: @inlang/core/environment). Does the file exist?

Error: Cannot find module '@inlang/core/config' imported from '/home/ak4zh/CodeProjects/sveltekit-auth-starter/node_modules/.pnpm/@inlang+sdk-js@0.4.5_@sveltejs+kit@1.16.3_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/config/config.js'
    at nodeImport (file:///home/ak4zh/CodeProjects/sveltekit-auth-starter/node_modules/.pnpm/vite@4.3.7/node_modules/vite/dist/node/chunks/dep-1f986b87.js:54435:25)
    at ssrImport (file:///home/ak4zh/CodeProjects/sveltekit-auth-starter/node_modules/.pnpm/vite@4.3.7/node_modules/vite/dist/node/chunks/dep-1f986b87.js:54337:30)
    at eval (/home/ak4zh/CodeProjects/sveltekit-auth-starter/node_modules/.pnpm/@inlang+sdk-js@0.4.5_@sveltejs+kit@1.16.3_svelte@3.59.1/node_modules/@inlang/sdk-js/dist/config/config.js:3:50)
    at instantiateModule (file:///home/ak4zh/CodeProjects/sveltekit-auth-starter/node_modules/.pnpm/vite@4.3.7/node_modules/vite/dist/node/chunks/dep-1f986b87.js:54399:15) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

## Proposal 

Move `@inlang/core` from a dev dependency to regular dependency, ensuring that `@inlang/core` is installed when using the sdk-js. 

https://github.com/inlang/inlang/blob/c1db8e3f9b3dc4985592c91668e493fcc2c62f78/source-code/sdk-js/package.json#L38

**Comment by ivanhofer** [comment]
`@inlang/core` is required and it is also mentioned in the installation guide: https://inlang.com/documentation/sdk/sveltekit

**Comment by samuelstroschein** [comment]
Why not move @inlang/core into the regular dependencies?

**Comment by ivanhofer** [comment]
Adding `@inlang/core` to the `dependencies` does not change anything.

> If the user installed @inlang/core themselves, and the versions differ, node should be able to resolve the correct version for sdk-js regardless

I'm not sure if this is possible..

---

What we really need to do is to also bundle `@inlang/sdk-js/config` instead of just transpiling it.
We will probably have similar issues in the future, so bundling each entry point will probably make sense too.

What do you think?

**Comment by samuelstroschein** [comment]
> Adding @inlang/core to the dependencies does not change anything.

It ensures that `@inlang/core` is installed.  

This issue is open because `@inlang/core` is a `devDependency` that does not get installed. Manually prompting users to install `@inlang/core` makes the getting started process more difficult because (as we can see) users forgot to install `@inlang/core`. 

>> If the user installed @inlang/core themselves, and the versions differ, node should be able to resolve the correct version for sdk-js regardless

> I'm not sure if this is possible..

I double-checked. It works, see https://stackoverflow.com/a/63987935. 

I would be surprised if it wouldn't work. The web ecosystem would collapse. I don't wanna know how many dependencies rely on `lodash` with different versions :D

> What we really need to do is to also bundle @inlang/sdk-js/config instead of just transpiling it.
We will probably have similar issues in the future, so bundling each entry point will probably make sense too.

Since we can define `@inlang/core` as a regular dependency (as long as no package conflicts arise), we should do so. Agree?

**Comment by ivanhofer** [comment]
Oh, I misunderstood something from your comment above. I'll add `@inlang/core` to the regular `dependencies`!
