### ISSUE TITLE
plugin setup should emit a warning if plugin set the same config property

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#779]
## Problem

Users use multiple plugins that set the same config properties which can lead to bugs. 

See https://github.com/ivanhofer/inlang-plugin-typesafe-i18n/issues/4#issuecomment-1547644965 as an example.

## Proposal 1: Emit a warning via the console [less explicit/lower DX but easier to implement]

Emit a `console.warn` when a plugins sets a config property which has been set before to educate users. 

## Proposal 2: Refactor setupPlugins and setupConfig to return warnings [apps can show warnings/better DX, more effort to implement]

Apps can't show warnings when the setup of plugins and the config partially goes wrong. Developers will likely not go into the console to see setup warnings. Thus, refactoring setupPlugins and setupConfig to be of `[data: InlangConfig, warnings: x[]` seems to make sense. I am not using `Result` here because `Result` implicates an either or which is not the case here, similar to lint which should return errors during the lint process but should succeed regardlessly https://github.com/inlang/inlang/blob/7ffb13b7e1b0878f8a5673224f1fc743068030ec/source-code/core/src/lint/linter.ts#L25-L29

**Comment by samuelstroschein** [comment]
@ivanhofer do you want to take this one over? 

The issue has been created because Nils is working on refining the communication of getting started. Users using multiple plugins that do the same thing was a recurring theme. Hence, the reason for opening this issue and implementing this.

**Comment by ivanhofer** [comment]
> See https://github.com/ivanhofer/inlang-plugin-typesafe-i18n/issues/4#issuecomment-1547644965 as an example.

What is the issue there? Someone should be able to use the `typesafe-i18n` plugin with the `sdk` plugin without getting a warning.

**Comment by samuelstroschein** [comment]
> What is the issue there? Someone should be able to use the typesafe-i18n plugin with the sdk plugin without getting a warning. 

That makes no sense. Both plugins define the same properties `readResources`, `writeResources`, and `languages`. The last plugin used wins, overwriting the previous plugin for functions. Users faced bugs where `languages` had duplicates because two plugins defined `languages` and the results have been merged.

**Comment by ivanhofer** [comment]
The `sdkPlugin` only sets `readResources` and the other properties, if they are not defined already.

The issue described in the linked issue was that the plugin was configured incorrectly and therefore the plugin did not set anything.

**Comment by samuelstroschein** [comment]
My bad! I forgot that the SDK-JS only defines `readResources` etc. as a fallback if they don't exist.

The underlying issue remains. If plugins define the same property, unexpected things will happen. Develoeprs should be warned, agreed?

**Comment by ivanhofer** [comment]
Yes I agree, I just didn't get why you linked the other issue ^^

So the `setupPlugins` outputs warings [before this line](https://github.com/inlang/inlang/blob/82f9a6f389ece5b6f015ac1d846b9077dc11bf56/source-code/core/src/plugin/setupPlugins.ts#L49) if something get's overridden

**Comment by samuelstroschein** [comment]
> So the setupPlugins outputs warings [before this line](https://github.com/inlang/inlang/blob/82f9a6f389ece5b6f015ac1d846b9077dc11bf56/source-code/core/src/plugin/setupPlugins.ts#L49) if something get's overridden 

Yep. Problem: We need a custom merge callback that checks this.

**Comment by samuelstroschein** [comment]
Closing as "collected in https://github.com/orgs/inlang/projects/22 which will be worked on as part of an week initiative; closing issues with no immediate priority"
