### ISSUE TITLE
Editor error

### ISSUE THREAD

**Issue by shinokada** [inlang/inlang#794]
## Problem

I tried to add https://github.com/shinokada/flowbite-svelte-i18n on https://inlang.com/editor but I got the following error:

> ERROR DURING RENDERING
> 
> Check the console for more information and please [report the bug.](https://github.com/inlang/inlang/issues/new/choose)
> 
> Error: The inlang.config.js is invalid. # The following errors occurred during the setup of plugins: None ✅ # The following errors occurred during the validation of the config: Unexpected end of JSON input --- If plugins return errors, chances are high that the plugin errors are the root cause for the config errors. Try to fix the plugin errors first.

### Additional information (screenshots?)

![image](https://github.com/inlang/inlang/assets/147320/7472a145-a797-4294-a6f2-40a217026974)

`inlang.config.js`

```

/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2.2.0/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.5.1/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
		],
	}
}
```

**Comment by samuelstroschein** [comment]
@shinokada your JSON files are empty https://github.com/shinokada/flowbite-svelte-i18n/blob/main/languages/de.json which is invalid JSON. Try adding `{}` to every file.

**Comment by shinokada** [comment]
Thank you. You are correct.
