### ISSUE TITLE
Error on SvelteKit

### ISSUE THREAD

**Issue by shinokada** [inlang/inlang#795]
## Problem

This may be only for my repo. But when I try to run `pnpm dev` it returns the following error.

> Tt [Error]: The inlang.config.js is invalid.
> 
> # The following errors occurred during the setup of plugins:
> 
> None ✅
> 
> # The following errors occurred during the validation of the config:
> 
> Unexpected end of JSON input
> 
> ---
> 
> If plugins return errors, chances are high that the plugin errors are the root cause
> for the config errors. Try to fix the plugin errors first.
> 
>     at Cc (file:///Users/shinichiokada/Flowbite/flowbite-svelte-i18n/node_modules/.pnpm/@inlang+sdk-js@0.5.1_@sveltejs+kit@1.16.2_esbuild@0.17.18_svelte@3.59.0/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:166:1922)
>     at async file:///Users/shinichiokada/Flowbite/flowbite-svelte-i18n/node_modules/.pnpm/@inlang+sdk-js@0.5.1_@sveltejs+kit@1.16.2_esbuild@0.17.18_svelte@3.59.0/node_modules/@inlang/sdk-js/dist/adapter-sveltekit/index.js:170:764
> 
> Node.js v18.16.0

## Steps to reproduce

1. clone the repo

```
git clone git@github.com:shinokada/flowbite-svelte-i18n.git
```

2. install dependencies

```
pnpm i
```

3. Run the server

```
pnpm dev
```

## inlang.config.js

```
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2.2.0/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.5.1/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
		],
	}
}
```

**Comment by samuelstroschein** [comment]
I recall that I replied to this bug already, stating that the JSON files were empty (which is an invalid JSON). @shinokada  Is this issue still relevant?
