### ISSUE TITLE
big refactor of AST transforms

### ISSUE THREAD

**Issue by benjaminpreiss** [inlang/inlang#797]
See [here](https://github.com/inlang/inlang/blob/main/source-code/sdk-js/src/adapter-sveltekit/vite-plugin/transforms/refactoring.md) for more information.

The current implementation has some issues we will address in a refactoring task. This should make the implementation more simple, easier to maintain, reusable and bullet-proof.

**Comment by samuelstroschein** [comment]
@ivanhofer closing because outdated?
