### ISSUE TITLE
`inlang machine translate` logs incorrect number of languages

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#807]
## Problem

_From https://github.com/osmosis-labs/osmosis-frontend/pull/1575#issuecomment-1554695982_

<img width="910" alt="CleanShot 2023-05-19 at 16 56 42@2x" src="https://github.com/inlang/inlang/assets/35429197/88cc4255-791b-42cc-bde6-2fd1b0aaeb6a">

**Comment by felixhaeberle** [comment]
fixed in [1b9c9f6](https://github.com/inlang/inlang/commit/1b9c9f6803e7bed756f4a68df1cb8cb0e77bcdd9).
