### ISSUE TITLE
Inconsistency in the wording

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#814]
## Problem
If I want to use the CLI, then I have to write {languagecode} 
creating the config by myself it is {language} 

### Expected behavior
It highly confusing to use different wording for the same meaning

### Additional information (screenshots?)
![CleanShot 2023-05-21 at 15 10 16@2x](https://github.com/inlang/inlang/assets/72493222/21743fcb-baf1-41a3-8a2e-74b1bc1be9c4)

**Comment by samuelstroschein** [comment]
@jannesblobel I need the reproduction steps. I don't know how to replicate the bug

**Comment by jannesblobel** [comment]
There a two ways to generate a Config. 
first use `npx @inlang/cli init  `
If you use this way, you will be asked for a `_languageCode_ `in the path pattern `_'./translations/{languageCode}.json'_ `

If You create the Config by yourself, 
you must specify the `_language_ `instead of the `_languageCode_`
`_pathPattern: './lang/{language}.json',_
`

**Comment by samuelstroschein** [comment]
@jannesblobel haha same solution as in https://github.com/inlang/inlang/issues/815. your CLI version is over a year old. try `npx @inlang/cli@latest`

**Comment by samuelstroschein** [comment]
Improved the docs in [0bae0f9](https://github.com/inlang/inlang/commit/0bae0f9bbbe75dfd8365eeb4e00dbc744f9fc364) to use @latest
