### ISSUE TITLE
Docs for CLI config  init are wrong

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#815]
## Problem
I guess the docs are wrong. Docs are mentioned 
`npx @inlang/cli config init
`

Cli itself say `npx @inlang/cli init`

### Additional information (screenshots?)
![CleanShot 2023-05-21 at 15 12 09@2x](https://github.com/inlang/inlang/assets/72493222/f6c196ce-a934-468b-ba68-eb06e8a79f7f)

![CleanShot 2023-05-21 at 15 12 33@2x](https://github.com/inlang/inlang/assets/72493222/1ef598d1-fb2f-427a-9601-8addab675f8e)

**Comment by samuelstroschein** [comment]
@jannesblobel needs reproduction steps. 

Searching for "npx @inlang/cli init" leads to 0 results, indicating that there is no inconsistency. 

<img width="508" alt="CleanShot 2023-05-21 at 18 02 35@2x" src="https://github.com/inlang/inlang/assets/35429197/ab33f496-fce9-44db-8362-1dd7dfed5e93">

**Comment by jannesblobel** [comment]
![CleanShot 2023-05-21 at 19 56 03@2x](https://github.com/inlang/inlang/assets/72493222/8702507d-9e51-4122-b326-d529ace0cec8)
Sorry, there was a failure in the upload with the second image

**Comment by samuelstroschein** [comment]
Lol haha. Your CLI is the cli from over a year ago! try using `npx @inlang/cli@latest`.

**Comment by samuelstroschein** [comment]
Improved the docs in [0bae0f9](https://github.com/inlang/inlang/commit/0bae0f9bbbe75dfd8365eeb4e00dbc744f9fc364) to use @latest
