### ISSUE TITLE
Should the server be a superset of the client instead of being a separate application? 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#822]
### On the client-server aspects of the next git

Should the server be a superset of the client instead of being a separate application?

The distributed aspect of git led to great applications like Heroku by being able to sync repos with ease. Generally, the aspect of syncing multiple repos seems to be a superpower in the world of distributed software. If the server is a superset of the client, a server itself could be "just another client of a repo" making applications like Heroku or Vercel, build on the next git, a no-brainer. Heroku and Vercel could spin up distributed servers that act as streaming instances for the clients "on the edge" but the servers themselves sync (as a client) with one main server. Seems like distributed data would be solved on the barebone denominator. Someone storing a .sqlite database could suddenly get "distributed sqlite" for free.

**Comment by NilsJacobsen** [comment]
**Opinion about the server:**

 This was the biggest unknown spot for me. I knew that we need to manage subscription, maybe faster syncs or even real time and lazy loading. I also knew that the GitHub servers are not really build for that so I was also trying to find a solution for that in my mind. I also came across the server idea. So if we can architect the server we can also make this requirements happen. But the downside of it would be that we need engineering, maintenance and also user management for that server. This would lead to a small threshold. But ultimately this can be the first step of being apply to make the new git profitable somehow. So maybe that is the right way.

Now I red about Samuel's idea of having the server living distributed on the clients. Actually it would be great to have something like that. I mean device power is getting better and better so that shouldn't be a problem in the future I guess. But I'm not sure how to make that reliable and a fit to our requirements. Maybe @samuelstroschein you can elaborate a bit more on that.

**Comment by NilsJacobsen** [comment]
@samuelstroschein can you share a resource where you red about the distribution of Heroku? I actually never knew that.

**Comment by samuelstroschein** [comment]
@NilsJacobsen 

> Now I red about Samuel's idea of having the server living distributed on the clients. 

There seems to be a misunderstanding. Clients can't be servers but servers can be clients. Hence, the notion of a server being a superset of a client. 

> So if we can architect the server we can also make this requirements happen. But the downside of it would be that we need engineering, maintenance and also user management for that server. This would lead to a small threshold. 

Don't tell anyone. We already started. The git-proxy is acting as auth server. We can incrementally build the inlang-git server as a proxy that turns into a dedicated server over night. 

> @samuelstroschein can you share a resource where you red about the distribution of Heroku? I actually never knew that.

I am referring to Heroku's innovation of setting up another remote that is pushed to, see https://devcenter.heroku.com/articles/git#create-a-heroku-remote. Vercel & Co. automated that step by listening to changes in a git repo and cloning on the user's behalf. Listening to changes in a git(hub) repo requires GitHub apps though. The world would be better if a git server can act as a client of a repo, making GitHub apps for such use cases redundant.

**Comment by araknast** [comment]
> If the server is a superset of the client, a server itself could be "just another client of a repo" making applications like Heroku or Vercel, build on the next git, a no-brainer. Heroku and Vercel could spin up distributed servers that act as streaming instances for the clients "on the edge" but the servers themselves sync (as a client) with one main server. Seems like distributed data would be solved on the barebone denominator. Someone storing a .sqlite database could suddenly get "distributed sqlite" for free.

If I'm understanding correctly, this functionality is already built into Git. A git server is just a regular git repo which also happens to be running the`git-send-pack`, and `git-upload-pack` processes. The only extra thing would be keeping these servers in sync, which comes for free with the "everything is a branch" methodology outlined in my vision 23 paper.  

> Now I red about Samuel's idea of having the server living distributed on the clients.
>
> > There seems to be a misunderstanding. Clients can't be servers but servers can be clients. Hence, the notion of a server being a superset of a client.

Hmm, this actually sounds interesting though. Consider the following:
- A Git server is a Git client
- A commit in Git is a Merkle tree
- A branch in Git is a hash chain
- Everything is an object, and every object has a unique hash

All that's needed is a peer-to-peer networking protocol, and a distributed hash table based on object hashes. Suddenly we have a fault-tolerant distributed filesystem with versioning as a bonus. I think I will do a write-up about this, in fact.

**Comment by samuelstroschein** [comment]
> @araknast  If I'm understanding correctly, this functionality is already built into Git. A git server is just a regular git repo which also happens to be running thegit-send-pack, and git-upload-pack processes. 

Correct. This issue has the intention of formalizing this design principle. Otherwise, the risk is higher that we deviate from the "server is a superset of the client" design principle (if we desire it to be valuable). 

> Suddenly we have a fault-tolerant distributed filesystem with versioning as a bonus. I think I will do a write-up about this actually. 

Very well! :D 

I had the realization that inlang-git seems to boil down to distributed files(system) which subsequently enables distributed data. Remember, a file can be a JSON, a (sqlite) database, a Word document, a design document, etc. If we enable distributed files that can be collaborated on and a "filesystem" that can be built upon, we suddenly enable new applications and render applications like https://www.dolthub.com/ redundant (because you can just store an sqlite in the repo and get the same benefits with less effort).

_See the 30 seconds snippet from the "Mother of all presentations" given in April 2023 https://youtu.be/CZr6A5gwmFs?t=3060_

<img width="1442" alt="CleanShot 2023-05-24 at 10 02 49@2x" src="https://github.com/inlang/inlang/assets/35429197/251a9f4a-339c-4bfb-af41-e88472b21d58">

**Comment by samuelstroschein** [comment]
Closing as "the requirement did not emerge yet in inlang. Thus, decision is not required at the moment."

Feel free to re-open if you disagree.
