### ISSUE TITLE
Should we drop direct support for "legacy" git hosts and instead build a proxy feature into inlang-git/server?  

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#823]
## Problem

Current git server implementations like GitHub don't support short and long-term requirements we have for inlang-git. 

_An example taken from @araknast [git vision 2023 document](https://gist.github.com/araknast/d80f8b64b2777e42b49fd9e89e5a1b13) in which he describes that a lazy filesystem would not be supported by GitHub_:

> Besides the obvious additions, one notable change is that the lazy filesystem has been moved much further down the roadmap, and has been replaced with sparse checkout. The reasoning for this is simply that GitHub does not support the filter option to git fetch-pack, and thus lazy cloning from a GitHub repo would not be possible. Sparse checkout should provide similar performance improvements while remaining more widely supported both by Git hosts and Git itself.

## Proposal 

1. Keep the client (operations on `.git`) conical but drop support for non `inlang-git/server` "remotes". 
2. `inlang-git/server` can act as a proxy to legacy git servers like GitHub. 

Cloning a repository from GitHub on the client would require a different url but ensure a "streamlined" experience with streaming, auth, lazy cloning, etc. For example, the inlang-git/server could serve as proxy to legacy git servers. Example usage:

```ts
// resolves from spec 
await git.clone("https://git.inlang.com/v1/inlang/inlang-new")

// resolves as proxy 
await git.clone("https://git.inlang.com/legacy/https://github.com/inlang/inlang")
```

### Pros

- no breaking change in the future/we already know that a proxy solution must come for auth etc. 
- we are not held back by legacy git server implementations and are free to iterate and experiment
- better UX and DX because no "warning: streaming doesn't work for github. warning: auth doesn't work for gitlab" etc.". We control the client and server and can therefore ensure compatibility.  

### Cons

- another thing that needs to be built and maintained (is it worth it?). Seems redundant to ask when looking at auth. 
- a step away from existing git solutions

## Question 

Q1. How do we weigh the benefits and cons of keeping short-term "direct support" of legacy git servers given that we need to diverge with higher confidence in the future? 

Q2. If we decide that forcing our server protocol is of best interest for the next git, should we drop isomorphic git compatibility to increase our iteration speed (incremental TypeScript migration, streamlined build tools, no hacky cloning, etc.)? It seems clear that we don't expect a canonical git implementation.

**Comment by NilsJacobsen** [comment]
That is actually a pretty interesting question. 
I feel like other software is facing a similar issue. Currently I was working with tiptop for example. 
They have an open source rich text editor but also [tiptap collab](https://tiptap.dev/collab) which is a paid service. Under the hood they had collaborative requirements that deeded a separate server like we do with the git and now they made it possible to use the editor with non collaborative features for free but paid when there is additional infrastructure needed. 

What can we learn form that approach:
Maybe we can keep legacy git as a fallback for free, and in the future people can use the new git server like they use vercel on top of GitHub to access the power of our new features. 
Disadvantage -> a lot of overhead maintaining both

I'm not convinced by that theory yet :D What do you think?

**Comment by samuelstroschein** [comment]
@NilsJacobsen the git client and server should be OSS and free of charge. Imagine paying for a database in 2023 :D Monetization of inlang-git will happen through other services.

**Comment by samuelstroschein** [comment]
Closing as "the requirement did not emerge yet in inlang. Thus, decision is not required at the moment."

Feel free to re-open if you disagree.
