### ISSUE TITLE
How to "reach" the next git?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#825]
## Context

@araknast shared a [document](https://gist.github.com/araknast/d80f8b64b2777e42b49fd9e89e5a1b13) about the vision of inlang-git for 2023. 

## Discussion

We should agree on a way to reach the next git.  

## My proposal

While "everything is branch" sounds good at the moment, we have a superior ingredient to any other git improvement over the previous decade: The inlang editor is targeting (mostly) non-developers. We are free to experiment with a concrete use case that entails requirements. 

> The problem with this is the [switching cost](https://www.investopedia.com/terms/s/switchingcosts.asp) involved. While these flows may indeed be easier for users, the cost of learning a new interface instead of Git simply seems to be "not worth it" in the long run. 

We do not necessarily have a switching cost problem. The editor doesn't try to lure developers away from their git workflows. The opposite is true. We are building an editor that works on git. But, building the editor on git does not mean that the mental model has to be identical. We are already seeing UX issues because of the mental model that we are changing like staging and the need to commit everything. Those changes are desired by developers too. But, in contrast to the git CLI, they are not switching from another app or tool. The inlang editor is competitionless in that regard.  

I propose to reach "the next git" by building and experimenting with workflows in the editor. Requirements and workflows for the next git will emerge automatically and organically, as they already did. We don't have to try to come up with better git workflows now that might or (likely) not be a breakthrough. Build the editor, see what technical limitations we are running into, analyze UX barriers, and incrementally develop inlang-git based on the technical and UX requirements of the editor.

**Comment by NilsJacobsen** [comment]
@samuelstroschein @araknast I also agree that we should go in an experimental direction with small steps. But I actually like the branch idea. So I would suggest having a roadmap with small steps that is working towards that goal. But after every step the goal can be questioned or even left aside when needed. That we can also achieve bigger goals and not only jumping from sprint to sprint fixing and tuning aspects of it but never dealing with the big fish. But I guess the vision 23 is exactly that big fish :D

**Comment by NilsJacobsen** [comment]
**Opinion about the branch flow:**

The solution sounds great. Everything as a branch takes out a lot of complexity. I think we have to make sure to not lead to confusion when git users a facing our new flow. This can be solved by wording I guess. Usually people are not concerned about pushing something because most of the time in open source projects that is pushed on your fork. But in our case that would mean that people are interacting with the common remote so that needs to be communicated correctly.

**Comment by samuelstroschein** [comment]
> Opinion about the branch flow:

> The solution sounds great. Everything as a branch takes out a lot of complexity. I think we have to make sure to not lead to confusion when git users a facing our new flow. This can be solved by wording I guess. 

Seems like I am the one tapping the brake paddle :D 

If we decide on incremental improvements _based on the requirements of the editor_, there is no need to implement the concept of everything is a branch. It doesn't seem like any product metric would improve at the moment. The pressing git-related issues are: 

1. Being able to clone larger repositories
2. Auth

**Comment by NilsJacobsen** [comment]
Don't get me wrong. I think if we think that brings big improvements in the future why not working towards it but we shouldn't be shy switching paths :D So in generell I would say first thing first and instant improvements are higher in prio list.

**Comment by samuelstroschein** [comment]
I opened https://github.com/inlang/inlang/issues/835 which should illustrate the incremental approach I am pushing for, and why everything is a branch is a concept that seems nice but is not required. Please take a look.

**Comment by samuelstroschein** [comment]
Also read #836, please. It proposes a design guideline as a direct result of the observations from #835
