### ISSUE TITLE
z-index of header is to low

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#833]
## Problem

![image](https://github.com/inlang/inlang/assets/21335119/5663e2d5-6000-42db-a088-b45ccc4a87da)

### Expected behavior

The header should stay on top of all other elements.

## Steps to reproduce

1. Go to https://inlang.com/
2. Scroll down

**Comment by NilsJacobsen** [comment]
Thanks @ivanhofer gonna fix that in the next styling fixes round.
