### ISSUE TITLE
Commit causes reload of the page

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#838]
## Problem

Commit causes reload of the page which leads into bad UX.

### Expected behavior

No reload.

https://github.com/inlang/inlang/assets/58360188/56466a96-48ea-424e-ba8e-7b77e888ab61

**Comment by NiklasBuchfink** [comment]
@samuelstroschein After investigation, this issue was introduced with the following commit https://github.com/inlang/inlang/commit/a47ac5d942388f0718e48f36cd22ced3b01f73cd

**Comment by samuelstroschein** [comment]
@NiklasBuchfink oh dear. We need a reactive filesystem that only reacts on certain paths that have been changed. I created an issue https://github.com/inlang/inlang/issues/839#issue-1723575493. 

I will remove the auto generation of the config in the editor in the meantime. A PR will follow in approx 30 minutes.

**Comment by samuelstroschein** [comment]
> Oh no, not the auto generation 😢 

Okay, then just disable the line of code causing this issue/deactiving the auto generation of the config.
