### ISSUE TITLE
CLI Autogeneration config Iteration steps

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#841]
## Problem
It seems that the command `npx inlang config init` asks GPT for more than three iterations to generate a configuration
Looks like a money-burning machine 
 ### Expected behavior
Throw an error after the third iteration: "Sorry, the config could not be generated automatically"
## Steps to reproduce

1. Open the Terminal in a Repo ( I tried this in the inlang main repo) 
2. execute the command `npx inlang config init`

### Additional information (screenshots?)
![CleanShot 2023-05-24 at 20 28 27@2x](https://github.com/inlang/inlang/assets/72493222/99f18637-7243-4ebc-9870-50287ebe1a8e)

**Comment by jannesblobel** [comment]
If this is not a bug, we should improve the messages in the shell

**Comment by samuelstroschein** [comment]
This is a "i ignored it because who cares" bug haha. Why do you deem it of high importance?

**Comment by jannesblobel** [comment]
That was only because it could have been a cost trap

**Comment by buhodev** [comment]
I hit ctrl+c after the 3th iteration several times trying to generate the config automatically, then I got frustrated with the CLI not working as expected and had to set inlang manually. Does the CLI generate the config eventually at some point or is it still a WIP?

**Comment by samuelstroschein** [comment]
@buhodev It is WIP!

I added an information when running the command that the command is work in progress,see [43a00f8](https://github.com/inlang/inlang/commit/43a00f838162724e391ec546fe99fcd66c1aa4bd). Thank you for your comment!

**Comment by samuelstroschein** [comment]
Closing this as "the config init command has been marked as WIP. solving this bug will be succeeded by a re-implementation of the command without chatgpt"

Re-open if you disagree.
