### ISSUE TITLE
cli machine translate should show a warning that the command should be used in the build step

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#844]
## Problem

_From https://github.com/osmosis-labs/osmosis-frontend/pull/1575#discussion_r1199159951_

> Yeah I'd rather have translations be present and not be perfect, then for them to be missing and the user would see the JSON key path instead. 

If you run machine translate right before the build step (in the build script), users would never face missing translations. 

> IMO the point of the online editor is for native speakers to easily improve translations that they find one that's off that likely originated by AI. 

Agree.

We can't flag machine translated content yet though to nudge native speakers to review machine translated translations. The workaround is to keep them as missing but machine translate on the fly to still show contributors that translations are missing. 

It's up to you. I would optimize for increasing the chance that contributors contribute translations rather than saving a few API calls. But, this will add the CLI command "as a dependency" to the build script. Can be removed easily but is still "a dependency". 

```diff

"start": "turbo start",
    "start:frontier": "dotenv -v NEXT_PUBLIC_IS_FRONTIER=true -- yarn start",
    "start:testnet": "dotenv -v NEXT_PUBLIC_IS_TESTNET=true -- yarn start",
    "build": "turbo build", 
+   "build": "yarn machine-translate && turbo build",
    "build:frontier": "dotenv -v NEXT_PUBLIC_IS_FRONTIER=true -- yarn build",
    "build:testnet": "dotenv -v NEXT_PUBLIC_IS_TESTNET=true -- yarn build",
    "build:libs": "turbo build --parallel --filter @osmosis-labs/math --filter @osmosis-labs/pools --filter @osmosis-labs/stores",
```

## Proposal

Show a warning before machine translate that the machine translations should not be committed e.g. use the command in the build step to avoid bad machine translations to decrease the quality of the project. 

- The proposal entails that a force flag must be available for the machine translate command. Otherwise, machine translate can't be used in the build step.

**Comment by felixhaeberle** [comment]
@samuelstroschein I think of the CLI more like a tool like a 🔨, we shouldn't introduce too much policies around it "how" it should be used. The people using the CLI know what they are doing. For good UX sake, we can check for process.env development alike and provide a warning if we think so.

**Comment by samuelstroschein** [comment]
@felixhaeberle machine translating every message leads to no lints working, the editor and other solutions providing no value.

We don't know what messages are machine translated and which ones are not. As long as we don't have that information, committing machine translations makes every other inlang app/tool and therefore the user think the "project is perfectly translated" which is incorrect. Machine translations without human review are bad. 

The interim solution I propose here is to show a warning and nudge users to use machine translations without committing them, thus in the build step.
