### ISSUE TITLE
ide extension should inform the user that an inlang config exists but does not define ide extension properties

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#852]
## Problem

Users think that adding _some_ plugin makes the ide extension work. It is unclear that plugins need to specify the ide extension properties. 

## Proposal

If an inlang.config.js file exists, and the ide extension properties are missing, provide the user with information that the config is missing ide extension-specific properties. 

Ideally, the information would not be a pop-up that a user clicks away out of annoyance. Maybe showing inline information in the inlang.config.js file provides a good way to inform the user that the config has missing properties: 

- the information is always shown (not just once like pop-up, or an annoying pop-up that is clicked away and forgotten)
- at the location that hast to do with inlang (discoverability) 
- can be used to show more information in the future

### Mock of showing inline information in the config

![CleanShot 2023-05-28 at 13 08 58@2x](https://github.com/inlang/inlang/assets/35429197/34155eb3-d83d-495e-83f0-7a730458fbd5)

**Comment by felixhaeberle** [comment]
This is related to #855

**Comment by felixhaeberle** [comment]
This has been added! 🎉

<img width="870" alt="Bildschirmfoto 2023-05-30 um 16 19 15" src="https://github.com/inlang/inlang/assets/34959078/7d61c21b-d8f6-4fb2-963f-3ccee90c6da1">
