### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'referenceLanguage')

### ISSUE THREAD

**Issue by ezynda3** [inlang/inlang#854]
## Problem

When building a SvelteKit app using adapter-node I get the following error:
`TypeError: Cannot read properties of undefined (reading 'referenceLanguage')`

### Expected behavior
The app should build successfully

## Steps to reproduce

1. Install the SDK for SvelteKit as defined in the docs
2. Run `pnpm run build`

### Additional information (screenshots?)
- Operating system: Linux

**Comment by ezynda3** [comment]
`vite.config.ts`
```
import inlangPlugin from '@inlang/sdk-js/adapter-sveltekit'
import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [inlangPlugin(), sveltekit()]
})
```

`inlang.config.js`
```
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
  const { default: jsonPlugin } = await env.$import(
    'https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js'
  )
  const { default: sdkPlugin } = await env.$import(
    'https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.1/dist/index.js'
  )

  return {
    referenceLanguage: 'en',
    plugins: [
      jsonPlugin({
        pathPattern: './languages/{language}.json'
      }),
      sdkPlugin({
        languageNegotiation: {
          strategies: [{ type: 'localStorage' }]
        }
      })
    ]
  }
}
```

**Comment by samuelstroschein** [comment]
Hi @ezynda3 👋,

Thanks for opening the issue! @ivanhofer will take over this one. But, he is on vacation right now. It might take a few days till he is able to reply.

**Comment by ezynda3** [comment]
Thank you.

**Comment by ezynda3** [comment]
I actually figured it out. I was using an old version of SvelteKit. Upgrading to latest works.

**Comment by samuelstroschein** [comment]
Closing as complete then.

**Comment by ivanhofer** [comment]
@ezynda3 which version did you use before?

**Comment by ezynda3** [comment]
> @ezynda3 which version did you use before?

^1.5.0

I was building from an old template
