### ISSUE TITLE
ide extension always gives warnings that some config props don't exist

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#855]
## Problem

The IDE extension always gives warnings that some config props don't exist every time a file is opened.

https://github.com/inlang/inlang/assets/35429197/8f5cbca8-f5bf-42a2-a0cb-d8caafc4ba9d

### Expected behavior

Show the warning once.

## Steps to reproduce

1. Open a repository with an inlang config file that doesn't define messageReferenceMatchers.

**Comment by samuelstroschein** [comment]
@felixhaeberle this issue will lead people to deactivate the ide extension. Thus, high priority.

**Comment by samuelstroschein** [comment]
Holy sh*it. This happens on every keystroke. Related to https://github.com/inlang/internal/issues/16

https://github.com/inlang/inlang/assets/35429197/493a83e2-20c1-4d17-920b-35383380a23f

**Comment by felixhaeberle** [comment]
@samuelstroschein This wasn't the case when I tested it but I'll have a look.
