### ISSUE TITLE
Remove plugin-specific functions from the editor

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#860]
## Problem
A metadata check is used to determine if the Add Language feature is enabled. This was done temporarily to speed up the introduction of new features without crashing unsupported plugins. In general, the editor should not introduce plugin-specific code, as users should create their own plugins or modify existing plugins.

## Proposal
Remove plugin specific functions and handle errors with an error message like "this function is not supported by the current plugin / plugin version".

**Comment by NilsJacobsen** [comment]
If you support that or don't produce an error we can remove the exception from the editor.

**Comment by felixhaeberle** [comment]
@NilsJacobsen csn you please open an issue in the respective plugins with a description what should be done?

**Comment by felixhaeberle** [comment]
@NilsJacobsen ping, can you point me to code where it's already implemented in the json-plugin? I'm still not understanding why this isn't also build into the json or i18next plugin.

**Comment by NilsJacobsen** [comment]
Is there a working project with yaml?

**Comment by felixhaeberle** [comment]
Yes, but I do not remember the name.
So if that's the case what you described above, is it enough to provide such a test:

```ts
test("inlang's config validation should pass with new language", async () => {
  // create random string as new language
  const randomLanguageName = Math.random().toString(36).substring(7);

  const env = await mockEnvironment({
    copyDirectory: {
      fs: fs,
      paths: ["./dist", "./example"],
    },
  });

  const module = await import("../inlang.config.js");

  const config = await setupConfig({ module, env });

  const resources = await config.readResources({ config });

  // add new language
  await config.writeResources({config, resources: [
    ...resources,
    {
      type: "Resource",
      languageTag: {
        type: "LanguageTag",
        name: randomLanguageName,
      },
      body: [],
    }]
  })

  const newConfig = await setupConfig({ module, env });
  
  // check if new language is added
  expect(newConfig.languages).toContain(randomLanguageName);

  const [isOk, error] = await testConfig({ config: newConfig });
  if (error) {
    throw error;
  }

  expect(isOk).toBe(true);
});
```

**Comment by felixhaeberle** [comment]
@NilsJacobsen This should then be added to the plugin-template to make sure every plugin does have this test.

**Comment by jannesblobel** [comment]
the best reason why @samuelstroschein should start with this task 
https://github.com/inlang/internal/issues/19

**Comment by NilsJacobsen** [comment]
https://github.com/inlang/plugin-i18next/blob/main/src/tests/example08.test.ts

Example test

**Comment by samuelstroschein** [comment]
@jannesblobel I added task https://github.com/inlang/internal/issues/19 to week 23. 

@NilsJacobsen @NiklasBuchfink I vote for removing add language from the editor. The overhead of ensuring this works is too high

**Comment by NilsJacobsen** [comment]
I don't see the problem to keep it actually. It's a feature that was already used by projects and it works. We could also just throw an error if an empty body is recived in yaml and po.

**Comment by felixhaeberle** [comment]
I added a test to ensure this behavior in `inlang-plugin-yaml`. 

@NilsJacobsen Can you please add a proper test to the `plugin-template` repository here: https://github.com/inlang/plugin-template/blob/main/src/plugin.test.ts

**Comment by samuelstroschein** [comment]
> @NilsJacobsen  I don't see the problem to keep it actually. It's a feature that was already used by projects and it works. We could also just throw an error if an empty body is recived in yaml and po.

Strong disagree. The feature of adding a language in the editor has been used by which projects? Probably 0. Leaving this in makes this feature only work for specific plugins which will lead to either: 

a) Overhead in developing and managing plugins. 
b) The feature crashing/not working for projects that use an incompatible plugin. 

Both a) and b) seem not worth the effort of supporting the feature. I would remove it for now. But, you decide what to do. I unsubscribe from this issue now.

**Comment by NilsJacobsen** [comment]
I know that Appflowy was using it. Actually adding a message is also adding an element without metadata. Basically the same issue. But we still support that. 

I feel like add language is such a basic feature and even when not everybody is using it i feel like this is proving how apps and plugins come together. I guess that is the longterm thought. But also short-term, i think removing it is more effort then removing the workaround. So the. I would just keep it as it is an postpone the discussion until this gets urgent. What do you think about that?

**Comment by NilsJacobsen** [comment]
Update: The i18next plugin is not using metadata anymore. jsonPlugin could follow (if we see that as necessary). Since yaml and po is kind depricated we could completely remove this add language condition and have metadata completely out of the editor again?

What do you think?

**Comment by samuelstroschein** [comment]
@NiklasBuchfink is this complete?

**Comment by NiklasBuchfink** [comment]
It's done ✅
