### ISSUE TITLE
update inlang README

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#863]
## Problem

The current README is really out of date & doesn't do us a great favor. It's a bit a shame that we didn't update it more regularly as it is our most important "Aushängeschild".

## Proposal

This issue aims to update the README file for Inlang with the following changes:

- [x] Update images to new ones: Replace the existing images in the README with new ones that accurately represent the current version of Inlang.
- [ ] Notify users about IDE extension and CLI working: Add information and relevant links in the README to notify users about the availability and usage of Inlang's IDE extension and CLI. Additionally, send newsletter to keep users informed about any updates or new features.
- [x] Remove "Notify Now" on CLI and IDE extension
- [x] Link CLI and IDE extension to the correct sources: Update the links in the README to correctly point to the official sources for downloading and installing the CLI and IDE extension.
- [x] do a better job at showing what the apps can do and not speaking about the features -> show don't tell 
- [x] Make all headlines clickable as links to respective content
- [x] introduce the Svelte SDK. Provide a brief description and highlight its ease of use and integration with Svelte. Link it to the relevant documentation.

**Comment by samuelstroschein** [comment]
Ups, I forgot about the waitlist for the ide extension. We have a couple of people interested and should send a mail.

**Comment by felixhaeberle** [comment]
let's wait until we moved the ide extension config back to core for this mail shoutout. how many are on the list?

**Comment by NiklasBuchfink** [comment]
@felixhaeberle can you add a new image for the CLI in the README? Then this should be complete.

**Comment by NilsJacobsen** [comment]
Is this ready? @felixhaeberle @NiklasBuchfink

**Comment by NiklasBuchfink** [comment]
A new CLI image is still missing

**Comment by felixhaeberle** [comment]
@NiklasBuchfink please go ahead and do a screenshot simply by executing `npx inlang@latest --help`. or any of the other commands which can be executed for example in the test app from the sdk-js.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Thank you!! 😽 Yep, will do that – already have something open in the internal issue list :)
