### ISSUE TITLE
starting the `dev` server removes newline at the end of json lang files

### ISSUE THREAD

**Issue by buhodev** [inlang/inlang#875]
## Problem

When I start the development server, any blank newlines at the end of the lang files (ex. `en.json`) in the resources folder are removed. But if prettier is installed and I run the `format` command, they are added again, causing those files to be in the working directory forever.

### Expected behavior

Follow the prettier config defaults if enabled in the repo and do not remove newlines at the end of the lang files

## Steps to reproduce

1. Create a new SvelteKit project with prettier enabled
2. Install `@inlang/sdk-js` and set up inlang manually with the json plugin
3. Add a `en.json` file in the resources folder at the root of the repository with some translations
4. Run the `format` command and see a newline added by prettier at the end of the `en.json` file (as the default behavior of prettier with any file)
5. Run the `dev` command and watch the last newline of the `en.json` file disappear
6. Repeat the last two steps

### Additional information (screenshots?)
![image](https://github.com/inlang/inlang/assets/105121122/01135ec6-86be-4464-ab68-20f03e77d9e3)

- Browser: Chrome
- Operating system: Windows 11

**Comment by ivanhofer** [comment]
This is an issue with the json plugin. I have added a comment there: https://github.com/samuelstroschein/inlang-plugin-json/issues/2

**Comment by samuelstroschein** [comment]
This issue is complete. The bug @ivanhofer mentioned is tracked in https://github.com/samuelstroschein/inlang-plugin-json/issues/28#issue-1740521966
