### ISSUE TITLE
SvelteKit adapter does not respect custom base path

### ISSUE THREAD

**Issue by aMediocreDad** [inlang/inlang#876]
## Problem

When setting a base-path in `svelte.config.js` (see example below), the inlang client still looks for the language route at root `/`. 

```js
# Example `svelte.config.js`

const config = {
  kit: {
    // ...
    // adapter: adapter(),
    paths: {
      base: '/my-path',
    },
  },
};
```

As pointed to me by @ivanhofer in the community Discord the offending code is here: https://github.com/inlang/inlang/blob/c9b542824c96fa0a034c9f0d6901d41711223a42/source-code/sdk-js/src/adapter-sveltekit/runtime/client/runtime.ts#L19

### Expected behavior

Using the `paths:base` example above, we would expect the client to look for langauges at `/my-path/inlang/[lang].json`.

## Steps to reproduce

1. Add inlang sdk to a new or existing SvelteKit project.
2. Set a base path in the `svelte.config.js` file. 
3. Run `dev` or `build && preview` and confirm that fetching language files return 404.

### Additional information (screenshots?)
- Browser: N/A
- Operating system: N/A

**Comment by ivanhofer** [comment]
fixed in version `0.6.4`
