### ISSUE TITLE
move plugins to monorepo

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#884]
## Problem

See https://github.com/inlang/inlang/discussions/857

- users are filing issues in the monorepo
- we have overhead with the multi-plugin repo setup

## Proposal

1. Move inlang maintained plugins (i18next and standard-lint-rules) into the monorepo. 

- [x] I propose to create a directory called `plugins` in `source-code` which contains sub-directories per plugin to find all plugins in `source-code/plugins` but also scope the plugins with dedicated package.json's etc.  

```
.
└── source-code/
    ├── plugins/
    │   ├── i18next/
    │   ├── standard-lint-rules/
    │   └── ...
    └── ...

```

2. [x] We need to use NPM for publishing. Should I register a new namespace `@inlang-plugin/*` ?
3. [ ] deprecate github plugins with console.warn message

**Comment by NilsJacobsen** [comment]
Sounds good.
Does it mean a breaking change of can it be accessed the old way too?

**Comment by samuelstroschein** [comment]
> Does it mean a breaking change of can it be accessed the old way too?

Nope. Those projects wouldn't receive updates but that should be okay. 

> We need to use NPM for publishing. Should I register a new namespace @inlang-plugin/* ?

Actually, this makes deployment more complicated. Thus, let's name plugins `@inlang/plugin-*`
