### ISSUE TITLE
Add id's in the editor url to quickly jump to respective key in editor

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#893]
## Problem

Currently, we don't add id's in the editor url to quickly jump to respective key in editor. This is needed for the ide extension to quickly jump into the editor.

### Expected behavior

I would like to visit some kind of url `https://inlang.com/editor/github.com/inlang/example#key.nestedKey` and jump right to the message I want to edit.

**Comment by felixhaeberle** [comment]
@openscript is soon working on #960 and needs this also 👍

**Comment by NiklasBuchfink** [comment]
Closed with merge of https://github.com/inlang/inlang/pull/1037

**Comment by openscript** [comment]
Great @NiklasBuchfink :) Will be used in the context tooltip!

**Comment by NiklasBuchfink** [comment]
@openscript credits go to @NilsJacobsen. We can't wait to see this :)

**Comment by NilsJacobsen** [comment]
Gonna add a small docs section for that today. So you see how to use it. @openscript
