### ISSUE TITLE
If a page is not found in the docs, the user receives a blank page 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#909]
## Problem
the user will get an Empty page without any informations
### Proposal 
We should display an error message or redirect the user to getting-started and display a toast 
## Steps to reproduce

1. Go to 'https://inlang.com/documentation/PageNotFound'

 

### Additional information (screenshots?)
- Browser: chrome
- Operating system: macOS Ventura

![CleanShot 2023-06-09 at 17 51 12@2x](https://github.com/inlang/inlang/assets/72493222/9abfaa58-d0e8-41da-a12c-0824f51d0f85)

**Comment by samuelstroschein** [comment]
This should be enabled by default https://github.com/inlang/inlang/blob/6eb26319357afbfb195761dbd714784bc0596200/source-code/website/src/renderer/_error.page.tsx. Seems like a bug in vite-plugin-ssr?

**Comment by jannesblobel** [comment]
We got two different status codes  
`https://inlang.com/documentation/PageNotFound' === 411 `
`https://inlang.com/documen === 404`
Probably the `_error.page.tsx` handles only 404

**Comment by samuelstroschein** [comment]
I see. @jannesblobel can you fix this?

**Comment by jannesblobel** [comment]
I will try my best :)

**Comment by felixhaeberle** [comment]
#923 related.

**Comment by jannesblobel** [comment]
sorry this has been left behind.  Thanks for taking over @NilsJacobsen
