### ISSUE TITLE
feedback button rendering issues

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#911]
## Problem

1. The feedback button does weirdly overlap with the footer & 

2. does **not reset** when switching pages so if I once pressed the button the thank you message gets rendered on each page. should be reset when another page is loaded or should be displayed page specific. 

![image](https://github.com/inlang/inlang/assets/34959078/54b0edbd-127c-4fa0-adfb-0a0beede3315)

(getting started in docs)

3. Also, as it can be observed here, the spacing is off (margin-top) and the alignment in the button seems broken:

![image](https://github.com/inlang/inlang/assets/34959078/272cc7e6-8b07-4f75-ad66-6b3c520f8c1d)

(web editor page in docs) 

### Expected behavior

Should work on multiple pages & should not overlap. Should have proper outer and inner spacing.

**Comment by samuelstroschein** [comment]
That's my bad. I changed the feedback button to be in the layout without checking for mobile.

**Comment by NilsJacobsen** [comment]
Fixed ✅
