### ISSUE TITLE
New Approaches to Lazy Loading

### ISSUE THREAD

**Issue by araknast** [inlang/inlang#915]
@inlang/team 
I've outlined a new potential approach for achieving lazy loading in Project Lisa [here](https://gist.github.com/araknast/8c26b4a356bb7aa85bde5b6287723a79). Let me know what you think.

**Comment by araknast** [comment]
Copying @samuelstroschein 's original reply here: 
> @araknast
> 
> > In other words, we have 3 solutions for each case:
> > 
> > 1. We are working with entirely remote data - remoteObjectStoreFs
> > 2. We are working with a local git repository, and don't need to sync to the filesystem - objectStoreFs
> > 3. We are working with a local git repository, and want to sync to the filesystem - NodeishFilesystem provider and standard git apis.
> 
> Let's discuss ways to have a unified API for all three use cases.
> 
> First, let's agree on the appeal of project lisa/building on git to align the discussion. To me, files as "the universal data API" is the appeal, see [this loom](https://www.loom.com/share/f3beba7d8ee444c5bc0dde8b5ad41624). An appeal that requires collaboration (enabled by version control [git]; but doesn't exist outside of software engineering) and an API to build apps on top of (project lisa) to reach market adoption.
> ### Idea 1 - `clone` returns a repository
> 
> Extending what @araknast proposed above. It seems clear(er) that we have to break project lisa from the constraints and design goals of a CLI.
> 
> **Description**
> 
> * Have an entry point into a repo.
> * The entry point has been named `load` instead of `clone` beneath to a) illustrate that a repo doesn't need to be cloned if it exists locally, b) break away from git glossary since this is not working like clone and c) explaining load instead of clone to people new to project lisa seems easier.
> 
> * The entry point returns all operations that can be conducted and (optionally) sync filesystem operations to a local filesystem.
> 
> * If a local repository is opened, repository filesystem operations resolve internally first and sync to the filesystem when resources are freed up (avoid performance problems but keep the upside of sync).
> 
> 
> ```ts
> import { load } from "@project-lisa/client"
> 
> // 1. remote repository
> const repository = await load("https://github.com/inlang/inlang.git")
> 
> // 2. local repository that auto-syncs 
> const repository = await load("/user/inlang", {
>   // defaults to nodefs if not provided but is exposed to allow any filesystem to be plugged in
>   // fs: nodeFs,
>   // or 
>   // fs: browserFilesystemAccessApi,
> })
> 
> // interestingly, the "current working directory problem" seems to be eliminated.
> // filesystem operations operate on the repo scope, not the host scope
> // "/README.md" will always resolve from the repository root. 
> const file = repository.readFile("/README.md", { encoding: "utf-8" })
> 
> repository.commit( { } )
> ```
> 
> **Pros**
> 
> * improvement performance by containing file systems operations as part of lisa
> 
> * better DX because we can control all "repository flows". E.g. `repository.readFile` which works everywhere is better than debugging host environment filesystems
> 
> * The constant "current working directory problem" seems to be solved.
>   The "current working directory problem" refers to the lack of a current working directory in application contexts. The inlang editor has no working directory. Neither does the ide extension, leading to constant file path problems when trying to resolve files.
> 
> 
> **Cons**
> 
> * Extension of the (proxy) server is required
> * ???
> 
> 
> **Open Questions**
> 
> * Filesystem operations should likely not obey `NodeishFilesystem` because of terrible DX.
>   Aka, we should likely use a custom filesystem API that doesn't drag 50 years of UNIX baggage with it (have sane error messages, etc.).
> 
> * Seems like this idea would make isomorphic-git redundant?

**Comment by araknast** [comment]
Overall I like the flow proposed by @samuelstroschein . The way I would implement it would be to keep `objectStoreFs` and `remoteObjectStoreFs` as low level apis which `@project-lisa/client` builds on top of. 

Two questions:

> If a local repository is opened, repository filesystem operations resolve internally first and sync to the filesystem when resources are freed up (avoid performance problems but keep the upside of sync).

How do we determine "when resources are freed up?" Unless we can do this performantly and deterministically, I think it's better to sync the object store to the filesystem as soon as it is written.

> Extension of the (proxy) server is required

Is it? Not quite clear on where the need to extend the proxy server comes from, but maybe I'm not understanding fully.

> Open Questions
>
> Filesystem operations should likely not obey NodeishFilesystem because of terrible DX.
    Aka, we should likely use a custom filesystem API that doesn't drag 50 years of UNIX baggage with it (have sane error messages, etc.).

I think its fine to keep `NodeishFilesystem`, if we are creating a user-facing filesystem api I think it would be good to stick with what people are comfortable with.

> Seems like this idea would make isomorphic-git redundant?

It would make the high level apis redundant, but the low level apis for thinks like the wire protocol, reading packfiles, caching, etc. would still probably come from isomorphic-git. If we do want to do large changes like rewriting to typescript and removing `Buffer`, this would drastically decrease the amount of effort required though, since we are now only working with a small subset of `isomorphic-git`.

**Comment by samuelstroschein** [comment]
> How do we determine "when resources are freed up?" Unless we can do this performantly and deterministically, I think it's better to sync the object store to the filesystem as soon as it is written.

Yeah sorry, "[sync the filesystem] when resources are freed up" is a performance optimization problem for the future. Hence, ignore for now.  

>> @samuelstroschein  Extension of the (proxy) server is required
> @araknast  Is it? Not quite clear on where the need to extend the proxy server comes from, but maybe I'm not understanding fully.

Great if not. 

I thought you wanted to ignore pack files, git wire procotol, etc altogether by fetching objects directly. Hence, my question if isomorphic git became redundant. If the proxy doesn't need be extended (for now), great.

>> @samuelstroschein  Open Questions
>>
>> Filesystem operations should likely not obey NodeishFilesystem because of terrible DX.
Aka, we should likely use a custom filesystem API that doesn't drag 50 years of UNIX baggage with it (have sane error messages, etc.).

> @araknast I think its fine to keep NodeishFilesystem, if we are creating a user-facing filesystem api I think it would be good to stick with what people are comfortable with.

Are you sure? The filesystem API would become a first-class citizen of lisa with this idea that can't easily be changed in the future. 

The desire to have `NodeishFilesystem` was rooted in the assumption that the filesystem API and "git API" are de-coupled (`git.commit()` and `fs.readFile()`). Developers are both familiar with git and fs APIs. For the sake of simpler adoption, not changing the fs API from `node:fs/promises` made sense. Especially because developers are free to use any filesystem API that maps to node's fs API under the hood. 

However, the discussed idea defines one API for repositories which couples traditional filesystem (`repository.readFile`) and version control APIs (`repository.commit()`) _(leading to our vision of distributed filesystem with built-in version control btw)_. The coupling leads to a) filesystem API changes being difficult without breaking changes and b) developers won't distinguish node's "bad" filesystem API from lisa (are more inclined to think lisa has bad APIs). 

```ts
// changing this API is difficult
repository.readFile()

// opossed to directly consuming a file from a de-coupled fs
nodefs.readFile()
memoryfs.readFile()
```

We could try to make the filesystem API configurable to mitigate the risk of being locked-in to a specific API:

```ts
const repository = load("https://github.com/some-repo.git, { 
  fsApi: NodeishFilesystem
})

// @araknast btw loading multiple repos should be possible as the badge already requires this
// loading the same repo multiple times should also not crash lisa or lead to bugs. 
const repository2 = load("https://github.com/another-repo2.git", {
  fsApi: DenoFilesystem
})

await repository.readFile("/README.md", { encoding: "utf-8" })

await repository2.readTextFile("/README.md)
```

But, the benefit seems net negative. A) The internal complexity grows, and b) developers using lisa will potentially use different APIs which will lead to confusion. Given that a filesystem API seems straightforward, see [VSCode's FS API](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), for the needs we have, a "sane" fs API from the start seems to be the better design choice. Changing the fs API in the future will be a headache, and working around nodes inherently incompatible with our requirements filesystem API is another problem at the moment.
 
---

@araknast We need to figure out how confident we are about the proposal being the right one. This seems to be a major decision, which can ofc be reversed/adjusted in the future, but we ideally make the right choice now. 

1. Can we/you think of another API to interact with repos that solve the performance problems with both local and remote repos? 
2. If not, how confident are you that the discussed idea is the right move forward given the information we currently have?

**Comment by ivanhofer** [comment]
I like the idea, but I have some questions.

 - If not all files are fetched from the server directly, a metadata object needs to be created and kept in sync so everyone knows what files are present, right? Or how would a `doesPathExist` operation work?
 - Do I need to be connected to the internet all times? If my local filesystem does not have all files loaded, I can probably not work when offline. Does it make sense to initially load just the first files needed and then load everything else in the background (opt-out)?
 - If files are not really written to disk, existing tools can't work with them right? They always need to use the lisa api in order to discover them.

My 2 cents to the discussion before:
I would not use the file system API from node. It shows it's age and misses a lot of neat features (mostly when it comes to nested folders). I would start from fresh, which means we can easily implement improvements to the design flaws the node implementation has.

**Comment by NilsJacobsen** [comment]
Hey folks, I feel like pulling data directly from remote sounds like a great performance upgrade. Thinks like pushing changes, or getting data of a single file will get a better DX.

Input from the editor side:
Right now we need all resources in the beginning to calculate the total number and get the lint report, but I assume that the big bite are the rest if the files that are not relevant to read from right?

**Comment by samuelstroschein** [comment]
> @NilsJacobsen Right now we need all resources in the beginning to calculate the total number and get the lint report, but I assume that the big bite are the rest if the files that are not relevant to read from right?

Correct. The proposal fetches files automatically if they are read but not the entire repository. 

> @ivanhofer If files are not really written to disk, existing tools can't work with them right? They always need to use the lisa api in order to discover them.

> @felixhaeberle Most important on a user perspective: Keeping remote and local in-sync then should be put well together

Obeying to "files (systems) are the universal data API" is crucial and considered in the proposal. I opened a pull request to reflect this crucial aspect https://github.com/inlang/inlang/pull/916. 

> I would not use the file system API from node. It shows it's age and misses a lot of neat features (mostly when it comes to nested folders). I would start from fresh, which means we can easily implement improvements to the design flaws the node implementation has.

I agree.

**Comment by araknast** [comment]
> @samuelstroschein I thought you wanted to ignore pack files, git wire procotol, etc altogether by fetching objects directly. Hence, my question if isomorphic git became redundant. If the proxy doesn't need be extended (for now), great.

The git wire protocol would still be necessary for this, as well as packfiles. We just don't need support for special promisor remotes/packfiles. With wire protocol v2 we are able to fetch arbitrary objects, but any system which allows us to do this (including the github+gitlab api) will enable this functionality. In that case I think it makes sense to have some sort of abstraction of all of the various 'object-fetching' protocols.

> @ivanhofer 
> - If not all files are fetched from the server directly, a metadata object needs to be created and kept in sync so everyone knows what files are present, right? Or how would a doesPathExist operation work?

The current approach is simply to query the server with the object id for each tree in the path. So to check if 'path/to/file' exists, we fetch HEAD to see if '/path' exists there, if so, then we fetch '/path' to see if '/to', exists there, and if that exists we fetch '/to' to check if '/file' exists there. 

> - Do I need to be connected to the internet all times? If my local filesystem does not have all files loaded, I can probably not work when offline. Does it make sense to initially load just the first files needed and then load everything else in the background (opt-out)?

Yes, lazy cloning would require a constant network connection. If you want to work with the files offline you would need to clone the full repo as normal. 

> - f files are not really written to disk, existing tools can't work with them right? They always need to use the lisa api in order to discover them.

This was brought up in one of @samuelstroschein 's original responses (not copied here). The solution would essentially be to have an option to copy files to the local filesystem once they are read from the (local or remote) git object store. 

It seems like the prevailing opinion is to break with the node filesystem api. I'm fine with that, it would potentially allow us to implement specific optimizations for git and remote filesystems.

Speaking of which, one concern that arises with this approach is the amount of network operations required to fetch individual tree objects like this. The worst case scenario would be heavy folder nesting, e.g. each each resource and each language is its own folder. We could optimize for this by reading the inlang config, and then specifying the desired tree depth to the git server accordingly -- the only issue is that GitHub's server implementation does not support this option. Perhaps another user for the proxy?

**Comment by araknast** [comment]
> @samuelstroschein We need to figure out how confident we are about the proposal being the right one. This seems to be a major decision, which can ofc be reversed/adjusted in the future, but we ideally make the right choice now.
> - Can we/you think of another API to interact with repos that solve the performance problems with both local and remote repos?
> - If not, how confident are you that the discussed idea is the right move forward given the information we currently have?

At the moment this approach seems like the best one that fits all the requirements, most importantly, backwards compatibility with traditional clients. I think `objectStoreFs` and `remoteObjectStoreFs` should be flexible enough to build something that meets our requirements, even if the larger design of lisa begins to shift.

**Comment by samuelstroschein** [comment]
> @araknast  We could optimize for this by reading the inlang config, and then specifying the desired tree depth to the git server accordingly -- the only issue is that GitHub's server implementation does not support this option. Perhaps another use for the proxy?

Exactly why I opened https://github.com/inlang/inlang/issues/823 a while ago. Feel free to re-open the issue to re-ignite the discussion.

We should not build project lisa around features/limitations that a git host like GitHub, Gitlab, or Azure have. For enterprise readiness which becomes important in a year, lock-in to a specific git host is unfeasible.

**Comment by araknast** [comment]
@samuelstroschein 
In that case the proxy may be very useful then. The issue I think is that in order to do this we will need to  begin storing git objects on our own server to maintain the performance benefits. Thus it ceases to become a "proxy" and becomes more of a pseudo-git host. Thoughts?

**Comment by samuelstroschein** [comment]
> Thus it ceases to become a "proxy" and becomes more of a pseudo-git host. Thoughts? 

I am aware. If we can avoid it, great. If we can't, well we wanna build LisaHub in the long run ;)

**Comment by NiklasBuchfink** [comment]
I'm a little late in reading all of this. It really seems like we can make massive improvements in this area with the proposed features that come with this. I think we've addressed a lot of things that should be considered in the design of the API, that it's time well spent to plan for this. On the other hand, it seems almost inevitable that something will need to be redesigned in the future.

It sounds like a "proxy" will be required at some point anyway:
- Enterprise Support
- Seemless introduction of lisa-specific features, like our own version of [Git Large File Storage](https://git-lfs.com/)
- Growing a MVP of LisaHub in the background
- Full transion for repos from other Git Providers

On the topic of lazy loading, it would be interesting to load by priority as we see with fonts, images, and videos to improve "time to interaction" or from a UX perspective "time to useful application". This besides automatic prioritization and ignoring files based on the definition of an entry point.
I thought of experiences like response streaming and scoping of responses from an AI chatbot and lazyloading features introduced by Vercel with NextJS as a reference for what the user experience of apps built on top of Lisa should look like and what we can learn from these examples.

**Comment by samuelstroschein** [comment]
@araknast Proposal for a safe way regarding the filesystem api. 

Don't expose fs APIs on the repository object. Instead, have a nested `nodeFs` object that will be succeeded by a sane `fs` API in the future.   

```ts
// node fs API that will be deprecated over the long run
repository.nodeFs.readFile()
repository.nodeFs.rm()

// new API introduced at a later point
repository.fs.readFile()
reposirory.fs.remove()

```

**Pros**

- Short run: provide developers with a familiar API 
- Short run: don't need to design a new fs API  
- Long run: easy deprecating possibility 
- Long run: ensuring that the later introduced `fs` API will be good through user feedback 

**Cons**

- Short run: cumbersome node fs API with lower DX

**Comment by araknast** [comment]
@samuelstroschein 
How about 3 APIs?
```
// nodeish api  which writes to the object store and filesystem
repository.nodeishFs.readFile()
repository.nodeishFs.rm()
... 

// new api which writes to the object store and filesystem
repository.fs.read()
reposirory.fs.write()
reposirory.fs.remove()

// object store api which operates on git objects directly without sync
repository.objects.read()
reposirory.objects.write()
reposirory.objects.remove()
```
I think this could be better DX as opposed to specifying an option to enable/disable fs sync.

**Comment by samuelstroschein** [comment]
> @araknast  How about 3 APIs?

What does the objects API enable that the fs API wouldn't support?

> I think this could be better DX as opposed to specifying an option to enable/disable fs sync.

Disagree. The objects API as "don't sync API" introduces a new concept that needs to be explained. 

Multiple developers will use different APIs in the same application. Some developers will use `fs` which will implicitly be syncing, some might use `objects` which will implicitly not sync. Developers will likely not understand why some things are syncing and why some things are not syncing. Thus specificing if syncing should happen on initializing/loading a repo seems much clearer. I think that generally if a repo exists locally on a machine, I deem that syncing will always be desired to enable interop with other apps.

**Comment by araknast** [comment]
> @samuelstroschein  Multiple developers will use different APIs in the same application. Some developers will use fs which will implicitly be syncing, some might use objects which will implicitly not sync. Developers will likely not understand why some things are syncing and why some things are not syncing. Thus specificing if syncing should happen on initializing/loading a repo seems much clearer. I think that generally if a repo exists locally on a machine, I deem that syncing will always be desired to enable interop with other apps.

Fair enough. In that case the 'fs/nodeishFs' api sounds good to me.

**Comment by araknast** [comment]
Seems like we've agreed on:
- `lisa/client` built on top of `objectStoreFs`/`remoteObjectStoreFs`
- client provides 2 apis, fs` and `nodeishFilesystem` apis
- Don't build around limitaitons in git hosts, use the proxy server

Closing this for now, feel free to re-open.

**Comment by samuelstroschein** [comment]
@araknast Thanks for taking the initiative to close this discussion. It ensures that we are making decisions quickly and move on to the next thing!

One thing to note: Did we also agree on the API or do we skip that for now? 

```ts
const repository = load("https://github.com/some-repo.git", { 
  fsApi: NodeishFilesystem
})

// @araknast btw loading multiple repos should be possible as the badge already requires this
// loading the same repo multiple times should also not crash lisa or lead to bugs. 
const repository2 = load("https://github.com/another-repo2.git", {
  fsApi: DenoFilesystem
})

await repository.fs.readFile("/README.md", { encoding: "utf-8" })

await repository2.readTextFile("/README.md)
```

**Comment by araknast** [comment]
@samuelstroschein 
I think that API is fine, if issues come up we can address them later when we go to implement.
