### ISSUE TITLE
remove decoration set and code action provided telemetry events

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#917]
## Problem

We get to many telemetry events for "decoration set" and "code action provided" that provide close to no benefit.

## Proposal

Remove "decoration set" and "code action provided" from the telemetry events.

## Additional information

Both telemetry events can be triggered by each keystroke which is the underlying reason for the massive amount of events.

**Comment by felixhaeberle** [comment]
@samuelstroschein Thank you for open the issue 🫶

**Comment by felixhaeberle** [comment]
✅ Done!
