### ISSUE TITLE
Duplicate "Support large repository" projects

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#920]
## Problem

We have two duplicate projects "support larger repositories projects" https://github.com/orgs/inlang/projects/19/views/1 and https://github.com/orgs/inlang/projects/9/views/1.

## Proposal

Merge the projects. 

I propose to use https://github.com/orgs/inlang/projects/9/views/1 because it has been used previously. 

## Additional information 

@araknast seems like you created project 19 because you didn't see project 9?

FYI the goals of inlang and project lisa are now identical with https://github.com/inlang/internal/issues/55: Support large repositories. Thus, both inlang and lisa issues will appear in the same project "support large repos".

**Comment by NilsJacobsen** [comment]
I would also use that one https://github.com/orgs/inlang/projects/9/views/1 ans add also the none lisa related tasks. @araknast does this work for u?

**Comment by araknast** [comment]
@NilsJacobsen 
Yes, that's fine. Actually the original project was mostly created as a test during the ams off-site. The goals in the second project are more aligned with what I'm actually working on now, so no need to merge. I've also closed the old project for now.
