### ISSUE TITLE
i18next plugin is not handling escapes.

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#921]
https://github.com/tournesol-app/tournesol/pull/1610

According to this PR. The project wants to keep the `:`. But the parser in the plugin is cleaning it up. We should handle it in the plugin. Cause this is valid JSON.

**Comment by samuelstroschein** [comment]
@NilsJacobsen please default assign the person who you think is responsible for this issue to ensure that issues get worked on or closed if the responsible person deems this to be of no priority. 

PS I default assigned you :P

**Comment by NilsJacobsen** [comment]
We can leave it like that for now:)

**Comment by samuelstroschein** [comment]
Closing as "doesn't need to be fixed right now". 

Re-open if you disagree

**Comment by NilsJacobsen** [comment]
I would keep it open to see if others also need that and if that is a blocker

**Comment by samuelstroschein** [comment]
@NilsJacobsen if users have the problem, they will comment on this issue and we can re-open it. 

I think it's best to keep open issues as "will be worked on in the near feature". This provides us with a clear "this needs be done" overview. The alternative is an endless backlog of issues that won't be worked on "but someone might have the problem". I take the stance that if a person has the problem, they will find this issue and comment on it.

**Comment by NilsJacobsen** [comment]
How do we track then what they are telling us?

**Comment by samuelstroschein** [comment]
> How do we track then what they are telling us?

It's in the project "support for large repos" now for tracking purposes. Re-open this issue once the priority is upped? If so, please close as not planned.

**Comment by NilsJacobsen** [comment]
We want to work on it in the the future. But not planned for the next weeks. Please follow the roadmap here:
https://github.com/orgs/inlang/projects/9
