### ISSUE TITLE
Flashing content on page load resulting in broken page

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#924]
## Problem

When visiting the deployed page at 

https://github.com/inlang/inlang/assets/34959078/e1dd24a2-4f8a-4db7-afc0-6c13f4dfa044

a flash occurs, and the page content is momentarily appears before it is missing. However, the content seems to be present and should load properly without any flashing.

### Expected behavior

The page should load smoothly without any flashing, and the content should be immediately visible to the user upon page load.

## Steps to reproduce

1. Deploy page
2. Visit it after deployment in a deeper nested level like `/documentation/apps/inlang-cli` or `/documentation/sdk/configuration` **and not `/documentation` first** – or simply reload those pages

## Additional Information

It is worth noting that if I first navigate to the `/documentation` route on the website, everything loads properly without any flashing.

**Comment by NilsJacobsen** [comment]
Can not reproduce it
![image](https://github.com/inlang/inlang/assets/58360188/d41e22be-86e1-4b95-952c-0398d6ed4e29)

**Comment by felixhaeberle** [comment]
@NilsJacobsen Please look at the reproduction steps.

**Comment by NilsJacobsen** [comment]
I did

**Comment by felixhaeberle** [comment]
@NilsJacobsen It worked because I went there first? I don't know. I simply see this error too often and wnated to raise an issue to investigate and ultimately fix it.

**Comment by NilsJacobsen** [comment]
I feel like it happened because the page is not part of the docs but of the readme of the cli. Maybe you can take a look at it, cause you implemented that.

**Comment by felixhaeberle** [comment]
No there is actually no difference I visited the web editor too and there was the same error.

**Comment by NilsJacobsen** [comment]
CLI problem is not related to deployment.

https://github.com/inlang/inlang/assets/58360188/03e5fc3b-9357-463c-b24c-cb9c3d52521d

**Comment by felixhaeberle** [comment]
@NilsJacobsen As I said, this happens for the web editor also right after deployment and **not loading any page before**. There could be a special case for CLI aswell but nevertheless that's not my building block.

I'm heavily invested in the CLI and IDE extension & Hiring and therefore I assign you back because you are the main drivers of docs, website & editor.

**Comment by NilsJacobsen** [comment]
Thanks for reporting the issue @felixhaeberle.

**Comment by felixhaeberle** [comment]
Also happens on `/documentation/sdk/configuration`. & potentially more.

**Comment by NilsJacobsen** [comment]
@felixhaeberle should be fixed now. Can you double check?

**Comment by felixhaeberle** [comment]
@NilsJacobsen Perfect 🫶🥰
