### ISSUE TITLE
VS Code Extension: command 'inlang.extractMessage' not found

### ISSUE THREAD

**Issue by anaclumos** [inlang/inlang#933]
## Problem

The VS Code Extension

### Expected behavior

- Command 'Inlang: Extract Message' resulted in an error
- command 'inlang.extractMessage' not found

## Steps to reproduce

1. Open Command Palette

![image](https://github.com/inlang/inlang/assets/31657298/129aaaa2-3e4f-47cc-ad52-3fafd48566d2)

**Comment by felixhaeberle** [comment]
Hey @anaclumos – Can you share your config file with us that we can further debug?
And maybe also some spec to your system. Are you working on Windows? Which framework / libraries are you using?

**Comment by anaclumos** [comment]
https://github.com/anaclumos/inlang-extension-bug/tree/main

This is a clone of https://github.com/redwoodjs/redwood-tutorial with an `inlang.config.js` from inlang.com website. Inlang Extract Message command, after installing the extension, does not work in such case. Is there any further commands I need to make?

**Comment by wentallout** [comment]
![image](https://github.com/inlang/inlang/assets/76118931/7a05c957-f87f-4dc7-9d39-2a3793d62fc6)
I'm having the same error on Windows 10 VSCode.

```

/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.5/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
		],
	}
}

```

**Comment by felixhaeberle** [comment]
@wentallout @anaclumos Can you both share your output of `npx @inlang/cli config validate` ?

We are currently investigating this bug, sorry for the inconvenience.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink can you help me with debugging this? 🫶

**Comment by felixhaeberle** [comment]
Probably related #904.

**Comment by felixhaeberle** [comment]
@openscript Can you have a look at this bug and the related one in #904 and provide an estimate too?

**Comment by openscript** [comment]
@felixhaeberle This and #904 are likely related. I suggest to create a failing integration test first. Right now it's hard to estimate. I think we can reach reproduction within 2-3h. Maybe fixing it is easy after.

**Comment by felixhaeberle** [comment]
@openscript Go ahead! 🤗
