### ISSUE TITLE
`inlang/cli` lint report too long. 

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#935]
## Problem

The cli lint report is too long. They can get up to over 1000 errors in a repo and I would consider that normal. 

## Solution

It would be great to get a summary at the end, kind of like the badge information. Otherwise the only information that i can extract is that i have a lot of errors. The actionable should be to show say that they can machine translate or that they know in which language resource they need to take action. In the future we can add a link to the editor ...

> I would consider this as a improvement maybe not extremely high prio but I leave it to you.

**Comment by samuelstroschein** [comment]
> @felixhaeberle  getLintReport function of core which should therefore be improved. 

Sounds good. 

I don't need to do this task. Lint report is not related to changing the AST or config. Happy to hand this one off. I see two options: 

1. Close as not planned and work on this is part of the Q&A improvement project. 
2. @felixhaeberle @NilsJacobsen you complete this issue in the next weeks given that you worked with the lint reports and understand the pains. 

I vote for 1. If you both agree on 1 too (indicate with 👍), last person closes the issue as not planned for now.

**Comment by samuelstroschein** [comment]
How about moving this to discussions "Feature Requests & Improvements"? 

- signal that this is in the backlog and not "closed" 
- let users vote

**Comment by NilsJacobsen** [comment]
We can do that. But keep in mind it is harder to get notifications in discussions. Can you not just send them this issue and ask them if we should reopen it when they need it (reopening means done in less then 4 weeks)?

**Comment by NilsJacobsen** [comment]
I would push for the discussion if you think that pushes engagement with devs (cal.com, ...)
