### ISSUE TITLE
move plugin-json to monorepo 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#936]
## Problem

Some users want IDE extension support in the plugin json. Specifically, https://github.com/inlang/internal/issues/61. 

## Proposal

Move the plugins json to the monorepo and thereby enable code sharing between the i18next plugin which already has ide extension support.

**Comment by felixhaeberle** [comment]
@samuelstroschein Would it then be smart to also move po and yaml plugin to the monorepo – to not have a Kuddelmuddel?

**Comment by samuelstroschein** [comment]
@felixhaeberle maybe. Delay the decision until large repos use plugin yaml and po? The reason to move the plugin-json to the monorepo is that we have some large repos that want support.

**Comment by samuelstroschein** [comment]
@felixhaeberle I got data now. I strongly vote for "No, don't move plugin yaml to the monorepo". 

Plugin yaml usage is non-existent with 2 repos only. Not worth it to maintain the yaml plugin (for now).

<img width="1141" alt="CleanShot 2023-06-16 at 13 30 46@2x" src="https://github.com/inlang/inlang/assets/35429197/b0543829-90bc-400b-a477-0e8d682abdaa">

**Comment by NilsJacobsen** [comment]
Resolved all failing tests and plublished it in the monorepo.
-> https://www.npmjs.com/package/@inlang/plugin-json

**Comment by NilsJacobsen** [comment]
I put this disclaimer on top:
This plugin is planned to be depricated in the future, it should be replaced by sdk or framework specific plugins.

Is that too much or fine?

**Comment by samuelstroschein** [comment]
> This plugin is planned to be depricated in the future, it should be replaced by sdk or framework specific plugins.

Probably rephrase to "the plugin is complicated to set up. We highly encourage alternative i18n library focused plugins like the i18next plugin, typesafe-i18n or similar.

**Comment by NilsJacobsen** [comment]
Gonna close this. For json plugin related tasks I open new issues in the monorepo.
