### ISSUE TITLE
Stacking of error messages in editor 

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#939]
## Problem

You can't read all the messages because the positioned error message window is simply too big when you have a lot of languages & missing messages.

<img width="1251" alt="Bildschirmfoto 2023-06-16 um 10 03 04" src="https://github.com/inlang/inlang/assets/34959078/30fb6140-bc07-4696-aa9f-128f239daebf">

### Expected behavior

First solution: Create an expandable / scollable window when there are multipe messages (up until 2-3).
Second solution: Rethink the concept of showing that many errors in general.

## Steps to reproduce

1. Go to [https://inlang.com/editor/github.com/felixhaeberle/AppFlowy](https://inlang.com/editor/github.com/felixhaeberle/AppFlowy)
2. Select all languages
3. Go to error message

**Comment by NilsJacobsen** [comment]
Thanks for handing in. We need some kind of stacking/extendable there. I guess we are not focusing on that for the next weeks. Gonna close that as not planned

**Comment by felixhaeberle** [comment]
It would probably be an easy fix, just give it a max height of two messages and make it overflow scroll.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Unfortunately, it is not so simple. I tried it and to scroll you have to keep the notification open. This takes a little longer than just.
