### ISSUE TITLE
Deprecate `ast.metadata` to avoid bugs

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#945]
## Problem

The metadata field in the inlang AST leads to bugs when CRUD operations are executed. 

Plugins rely on metadata to serialize messages. However, creating new messages or resources (ofc) does not include metadata. The add language button in the editor is one of the most prominent examples of a regression bug entailed by the metadata feature. 

## Proposal

Deprecate and remove metadata from the AST because the new plugin API allows scoped state. The refactored i18next plugin (#937) already makes use of the plugin state to avoid metadata, see the code beneath. 

- It works flawlessly
- avoids bugs
- increases DX because the concept of metadata does not have to be explained

https://github.com/inlang/inlang/blob/0093c4b8ccd90f06d6442da3285e6f58cebb0410/source-code/plugins/i18next/src/plugin.ts#L21-L45

## Additional information 

Metadata exists because information about the structure of resources and messages needed to be preserved. The new plugin API enables scoped state rendering the metadata field redundant and thereby a class of regression bugs.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink @NilsJacobsen and @ivanhofer, you worked with plugins. Do you agree?

**Comment by felixhaeberle** [comment]
Related #874 — machine translate can't figure out the nesting because of missing metadata when creating a message from scratch.

**Comment by samuelstroschein** [comment]
> how does that work when new messages are creating using the machine translate process? how is the state of the plugin exposed to the machine translate command in this case? 

What are you referring to with "that"? 

**If you refer to metadata:** 

As written, "The metadata field in the inlang AST leads to bugs when CRUD operations are executed.". 

**If you refer to the proposed plugin state:** 

The state is not exposed. It's the job of the plugin to set defaults. Not relying on metadata makes this easier. See for example https://github.com/inlang/inlang/blob/75ad2c7dfe3f6c365ee442e082aeb5e81581efbe/source-code/plugins/i18next/src/plugin.ts#L52-L59

**Comment by ivanhofer** [comment]
`ast.metadata` could be useful to store the type of a variable placeholder and not show it in the Editor. But this information could also be stored in a `Map` in the scope of the whole plugin.

**Comment by felixhaeberle** [comment]
@samuelstroschein For the issue I mentioned above, the root cause of having metadata was to distinguish between a "this.this" and this: { this } as original resource structure to insert it back in the right structure. How will this be done in the future, when creating a message with machine translate, but don't know in which format it has to be inserted. 

This will then be handled by the plugin automatically? Because when for example creating a message for hello.world in ES, it will look up the structure for it in the EN resource? And decide if "hello.world" or hello: { world } applies?

Same for all the other variable formatting, such as spaces, empty lines etc.

**Comment by samuelstroschein** [comment]
@felixhaeberle Correct, the plugin needs to handle formatting of unknown messages. 

The key differentiator between ast.metadata and plugin state is that ast.metadata can be mutated/removed by inlang apps while plugin state is never corrupted. Thus, storing "metadata" in plugin state seems a safer way to avoid bugs related to corrupted ast.metadata. 

The discussion seems to agree with deprecating `ast.metadata`. I will close this issue in a few days and deprecate `ast.metadata`. Comment if you disagree.

**Comment by samuelstroschein** [comment]
Deprecated in commit 4460a451a3deba4711aefcfc34112e5ec2cee0e6
