### ISSUE TITLE
rework bug report template to include better information for debugging

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#951]
## Problem

the current bug template could be improved with config file and cli config validate output for debugging

### Expected behavior

Everything which is currently in place + 

1 attached config file
2 output of config validate
3 installed i18n libs

**Comment by felixhaeberle** [comment]
@inlang/team Do you have a opinion on this? We already have two bugs where we later had to ask for the specific information. #933 and #904

**Comment by NilsJacobsen** [comment]
Seams like a quick win 👍

**Comment by felixhaeberle** [comment]
Alright, I update the bug template. 🏗️
