### ISSUE TITLE
documentation links are copied wrongly

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#956]
## Problem

Links are copied without "https://" prefix leading to apps not identifying copied links as links. 

`inlang.com/documentation/apps/ide-extension#features`

### Expected behavior

```
// instead of 
inlang.com/documentation/apps/ide-extension#features

// this
https://inlang.com/documentation/apps/ide-extension#features

```

## Steps to reproduce

1. https://inlang.com/documentation/apps/ide-extension
2. Click on a headline

## Additional information 

I recommend showing the `#` all the time to signal that headlines can be copied.  

![CleanShot 2023-06-19 at 15 19 32@2x](https://github.com/inlang/inlang/assets/35429197/13a0fc73-5051-4695-80f0-6e4fc064b9ac)

**Comment by NiklasBuchfink** [comment]
@samuelstroschein The hashtag on hover is a one-to-one copy from the Vue, Astro and NextJS documentation. @NilsJacobsen & I feel that this breaks the alignment of the page and makes it harder to read. Therefore we suggest to leave it as it is. (See below)

<img width="958" alt="image" src="https://github.com/inlang/inlang/assets/59048346/ef465855-69c6-41f1-8cd8-e5910ca8b951">

**Comment by samuelstroschein** [comment]
@NiklasBuchfink makes sense
