### ISSUE TITLE
error 404  after forking a repo in the editor

### ISSUE THREAD

**Issue by jannesblobel** [inlang/inlang#962]
## Problem 
I want to fork a repo in the editor  and  got a 404 Error after the forking prozess
### Expected behavior
forward to my fork 
After reloading the page it works, but this should not happen 
## Steps to reproduce

1. Go to 'a new project that you didn't fork yet'
2. Click on 'open in editor`
3. click on " fork" 

### Additional information (screenshots?)
https://www.loom.com/share/7cd35ff6ecee474e9fe0daa6ebc44c8f
- Browser:Chrome
- Operating system: MacOS

**Comment by NiklasBuchfink** [comment]
@jannesblobel It's live; you can test it now 😄

**Comment by jannesblobel** [comment]
@NiklasBuchfink, it is still there :( 
<img width="859" alt="CleanShot 2023-07-05 at 15 09 13@2x" src="https://github.com/inlang/inlang/assets/72493222/a2a7aac2-836b-4001-a614-9ead494f5280">
