### ISSUE TITLE
Backslashes in pathPattern after `npx inlang config init` (Windows issue)

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#964]
## Problem
Executing `npx inlang config init` creates a `inlang.config.js` with the following pathPattern: `"public\locales\{language}.json"` The backslashes are recognized as escape characters, not a path, and were removed from my prettier settings on save.

Operating system: Windows 11

<img width="671" alt="image" src="https://github.com/inlang/inlang/assets/59048346/a58f26c7-c2b3-487f-93c6-6ed6780dfffe">

### Expected behavior

Windows paths work with forward slashes instead of backward slashes.

## Steps to reproduce

1. Clone a valid `i18next` repo
2. Install the `@inlang/cli`
3. Execute `npx inlang config init`

**Comment by samuelstroschein** [comment]
I hate windows

**Comment by felixhaeberle** [comment]
Auto-closing doing is thing 😄

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Can you test the behavior now if it has been fixed on Windows? Fingers crossed 😅

**Comment by NiklasBuchfink** [comment]
Looks good 👍
