### ISSUE TITLE
`npx inlang init` chooses wrong plugin by default

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#968]
## Problem

I used the CLI command `npx inlang init` to setup inlang for https://github.com/TryGhost/Ghost
By default a `inlang.config.js` with the older `inlang-plugin-json` was created instead of the monorepo `plugin-i18next`. 

Maybe this is a result because the **wrong pathPattern** is setup inside a **monorepo**

Repo: https://github.com/TryGhost/Ghost
Operating System: Windows 11

### Expected behavior

If it is an i18next setup, the latest majoy version of `plugin-i18next` inside the inlang/inlang monorepo should be used.

## Steps to reproduce

1. Fork https://github.com/TryGhost/Ghost
2. Run `npx inlang init` of the `@inlang/cli`

**Comment by felixhaeberle** [comment]
We do not have monorepo support for `config init` atm. 

Please execute the `config init` in the respective root (where the package.json is) to get the correct library detection.

It would be hard to choose which repository you want to globalize in a monorepo structure when multiple package.json's are found and therefore for examples multiple i18next packages / multiple resource folders are found.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Should the `samuelstroschein/inlang-plugin-json` still be used in the setup instead of the `inlang/plugin-json` of the monorepo?

**Comment by felixhaeberle** [comment]
@NiklasBuchfink No, but this change was after the config init was released 😄 Will update it 👍

**Comment by NiklasBuchfink** [comment]
Perfect 😄👍

**Comment by felixhaeberle** [comment]
@NiklasBuchfink I fixed the plugin linking & automatic versions in https://github.com/inlang/inlang/pull/970

**Comment by NiklasBuchfink** [comment]
@felixhaeberle I have tested it. It pins to `npm/@inlang/plugin-json@3.0.7`, but in the interest of automatic updates we should pin to the major version `3` instead.

What do you think?

**Comment by felixhaeberle** [comment]
Great finding! <3

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Fixed major version pinning instead of general version pinning.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle It's done 👍

**Comment by felixhaeberle** [comment]
@NiklasBuchfink  Nice, fixing 3 bugs in an unrelated issue – this issue is ruined. 😄 Let's remove our comments here. Do you agree?
