### ISSUE TITLE
Badge shows wrong translation percentage & missing message value 

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#974]
## Problem

1. The number of missing messages in the headline of the badge is wrong (way to low)
2. This results in the wrong translation percentage
3. False statistics do not set the incentives

It is wrong in several documentations and gives the impression that the translations are better than they are. 
Moreover, it cannot be used to show the urgency of inlang in PR.

### Expected behavior
1. The number of missing messages is the same as in the editor
2. The calculation should be correct afterwards

## Steps to reproduce

Compare missing messages & errors:

[![translation status](https://inlang.com/badge?url=github.com/NiklasBuchfink/Ghost)](https://inlang.com/editor/github.com/NiklasBuchfink/Ghost?ref=badge)

**Comment by felixhaeberle** [comment]
@NiklasBuchfink The badge does not render in the description?

**Comment by felixhaeberle** [comment]
@jannesblobel Changed the calculation a while ago, I will assign him for now.

**Comment by felixhaeberle** [comment]
This is the repository: https://github.com/TryGhost/Ghost

**Comment by jannesblobel** [comment]
All the badges are broken 
I will fix it tomorrow

<img width="673" alt="CleanShot 2023-06-22 at 20 56 12@2x" src="https://github.com/inlang/inlang/assets/72493222/6b95f0f6-e248-451f-b40b-08d3f72e3575">

**Comment by NiklasBuchfink** [comment]
@jannesblobel The badge of Open-Assistant seems to be ok. Maybe this will help you to find the error:

[![translation badge](https://inlang.com/badge?url=github.com/LAION-AI/Open-Assistant)](https://inlang.com/editor/github.com/LAION-AI/Open-Assistant?ref=badge)

Sometimes the older version is also shown on GitHub / in the documents because it is cached. The direct web link is the most accurate:
https://inlang.com/badge?url=github.com/LAION-AI/Open-Assistant

**Comment by felixhaeberle** [comment]
@jannesblobel Could be that only the error handling is off when there is an error / edge case?

**Comment by NiklasBuchfink** [comment]
@jannesblobel What is the status of this? Could you fix this, or should I look into this?

**Comment by jannesblobel** [comment]
Good question, but I think you should use your resource for more relevant tasks :). 
It is on my list and I will try to fix it Asap after the other stuff with the note ASAP :D

**Comment by NilsJacobsen** [comment]
@jannesblobel I feel like this should be done asap. So the people are not gonna remove it.

**Comment by NilsJacobsen** [comment]
I would also vote for that 👍 if that is fine for you @jannesblobel

**Comment by NiklasBuchfink** [comment]
When opening PRs, this is crucial for adoption because it is our way to showcase the linting directly within GitHub, including the link to the editor (2x wow-effect). Let's fix this asap.

@jannesblobel We know it's bad timing with the end of the semester and moving back to Berlin.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink can you update the milestone?

**Comment by jannesblobel** [comment]
https://discord.com/channels/897438559458430986/1087469464406212648/1134180583971487875

Let's fix this after the big refactoring. People adopt the badge

**Comment by NilsJacobsen** [comment]
Updated the implementation of the badge with https://github.com/inlang/inlang/commit/55a8e4b58f0ff3bb4c2264b2e3d4f4dc22f9f7a5

This will be merged in this PR with the refactoring: https://github.com/inlang/inlang/pull/1142

The percentages should be fixed. (100 - number of variants with (missingMessages/emptyPattern) / all possible variants * 100)

-> so you don't get a 0% when adding a new language

TODO for the future: with selector variants we need to take them into account when calculating the possible amount of variants

Gonna close this when the PR is merged.

**Comment by samuelstroschein** [comment]
Should be fixed with armageddon
