### ISSUE TITLE
Can't commit with `plugin-i18next`

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/inlang#976]
## Problem

If I change something in the editor and commit the translation:
1. The change is reverted back to the old copy
2. An empty commit is pushed to the remote repository

Related to: https://github.com/samuelstroschein/inlang-plugin-json/issues/26

As works for the latest version of the `inlang/plugin-json` I suspect that it is a "plugin-i18next" and not an editor.

### Expected behavior

After push:
1. The commit is created correctly with the changes
2. By pulling after this commit, the copy remains unchanged

## Steps to reproduce

1. Open editor with a project using i18next (https://inlang.com/editor/github.com/NiklasBuchfink/nextjs-i18next)
2. Make a change & save
3. Push and commit
4. Review commit in your fork

Working `plugin-json` repository:
https://inlang.com/editor/github.com/NiklasBuchfink/example

**Comment by samuelstroschein** [comment]
Investigation pending. 

A test case has been added to the plugin in https://github.com/inlang/inlang/commit/9dbf79c6583d034eb2845d8ca782c51d739a316d which does not indicate that the problem is plugin related.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink The bug seems editor-state-related. 

A few indicators: 

1. `setupConfig` roundtrip tests pass, meaning serialization works as expected.
2. The bug occurs the moment push changes is pressed. (On that note, rename the button to commit & push?)

Can you investigate the editor state?

https://github.com/inlang/inlang/assets/35429197/447ff6a4-d2ca-4184-92dc-4b31de478b76

**Comment by NiklasBuchfink** [comment]
I'm on it 👍

**Comment by NiklasBuchfink** [comment]
@samuelstroschein Results of my investigation:

This issue also happens with the `plugin-json` for path patterns like `app/i18n/locales/{language}/*.json`.

Everything is correct till the `writeResources` function in the State.tsx is executed. The `resources` argument contains the changes.

After that the `pushChanges` function is triggered and the value `filesWithUncommittedChanges` after executing `raw.statusMatrix` is empty for the mentioned path pattern.

**Comment by samuelstroschein** [comment]
Okay, gotta have to add unit tests for paths like `app/i18n/locales/{language}/*.json` tomorrow.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink as discussed on the call, would be great of you can fix this

**Comment by NiklasBuchfink** [comment]
Closed with #987
