### ISSUE TITLE
VSCode extension: Extension removing blank lines at the end of languages JSON files

### ISSUE THREAD

**Issue by WarningImHack3r** [inlang/inlang#998]
## Problem

The VSCode extension periodically (frequently) removes the empty line at the end of all the JSON files containing my Inlang key/value pairs. It's really annoying because it creates VCS changes, randomly, and does not comply with general good practices nor my ESLint rules.

### Expected behavior

To not modify any of my files, except eventually my `inlang.config.js` when I update the NPM Inlang SDK.

## Steps to reproduce

1. Install the VSCode extension
2. Wait a bit or move around across your files
3. Your `/your/inlang/path/{language}/*.json` all get their last empty line deleted

### Additional information

- `inlang.config.js` file:

```js
/**
 * @type {import("@inlang/core/config").DefineConfig}
 */
export async function defineConfig(env) {
	const { default: pluginJson } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@latest/dist/index.js"
	);

	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.3/dist/index.js"
	);

	const { default: standardLintRules } = await env.$import(
		"https://cdn.jsdelivr.net/gh/inlang/standard-lint-rules@latest/dist/index.js"
	);

	return {
		referenceLanguage: "en",
		plugins: [
			pluginJson({
				pathPattern: "./src/locales/{language}/*.json",
				variableReferencePattern: ["{", "}"]
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
			standardLintRules()
		]
	};
}
```

- `npx @inlang/cli config validate` output:

```sh
ℹ 🔎 Validating the config file...                                    23:31:31
✔ 🎉 Inlang config is valid!                                          23:31:31
```

- Browser: Arc
- Operating system: macOS
- Screenshots? None

**Comment by NilsJacobsen** [comment]
Hey @WarningImHack3r thanks for handing in the bug.

We moved the [jsonPlugin](https://github.com/inlang/inlang/tree/main/source-code/plugins/json/) in the monorepo so we got a new path to the package. 
-> "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js"

In that version that shouldn't be an issue anymore.

**Comment by WarningImHack3r** [comment]
Good to know! Will check ASAP. Is it the only plugin that has been moved?

**Comment by samuelstroschein** [comment]
@WarningImHack3r standard lint rules changed too

**Comment by WarningImHack3r** [comment]
I indeed don't seem to encounter this issue anymore. Thanks for the fix!

N.B.: I directly used the `latest` versions instead of `@3`

**Comment by samuelstroschein** [comment]
@WarningImHack3r > N.B.: I directly used the latest versions instead of @3

You are running into the risk of breaking changes if you don't pin the major version.
