### ISSUE TITLE
Replace deprecated tsconfig

### ISSUE THREAD

**Issue by openscript** [inlang/inlang#999]
## Problem

![image](https://github.com/inlang/inlang/assets/1105080/b82028f7-1f9d-4d1e-b85f-c937c5c518ee)

## Proposal

Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

**Comment by openscript** [comment]
This is not so easy to fix, as in the design system cjs and mjs is quite mixed up.

**Comment by samuelstroschein** [comment]
1. TailwindCSS finally supports ESM, we could migrate the design system to ESM.
2. @NilsJacobsen @NiklasBuchfink are you using the design system, or can we remove it?

**Comment by NilsJacobsen** [comment]
We are using the color system. No components, as far as I know.

**Comment by samuelstroschein** [comment]
fixed
